/*
  THE AUDITED FACTBASE, laid over the table in `twentyThings.ts`.

  Seventy-two things were researched from Wikipedia, Wikidata and Sõnaveeb and then audited by
  separate readers, which changed 105 cells, nearly all of them from a flat yes or no to
  "sometimes" or "not known". Each thing here lists, per field, what is a plain yes (`y`), a
  "sometimes" (`s`) and what the research could not settle (`u`). Anything else in the covered
  vocabulary is a plain no, so a closed-world "no" now rests on a checked fact instead of on
  silence. A cell marked `u` is left as the table already had it, because "not known" is not a
  reason to take a fact away or to invent one.

  This file holds English tokens and the headwords the table already uses, and no Estonian
  sentence. What it deliberately does not touch: sizes (48 of 72 were never verified), smell and
  "natural", which have one rule each in `widen`, and the weights and shapes the audit has no
  column for.
*/

/** The tokens each field's audit covers. A token in here that a thing does not list is a plain no. */
export const AUDIT_VOCAB: Readonly<Record<string, readonly string[]>> = Object.fromEntries(
  Object.entries({
  has: "jalg tiib saba ratas uks aken sulg karv leht nokk silm kõrv nina suu pea hammas kõht selg sarv nahk koor seeme juur oks rool ekraan nupp klaviatuur kaas uim käpp kabi kael küünis soomus õis tüvi lont",
  can: "move fly swim jump run climb",
  does: "bark grow burn shine ring work wash buy sell play scratch sleep walk",
  use: "drink read write eat ride wear sit",
  where: "water sea sky fridge home kitchen school shop bed street city country garden forest outdoors",
  colour: "roheline lilla must valge pruun hall punane kollane oranž roosa sinine",
  made: "puit metall klaas paber kivi raud kumm vill puuvill plast kangas kuld",
  trait: "sweet sour salty sharp round long wide thick thin wet dry dangerous",
  feel: "hard soft cold warm fast slow",
  isa: "loom lind imetaja putukas taim jook puuvili köögivili sõiduk mööbel hoone ese riideese toit",
  }).map(([k, s]) => [k, s.split(" ")]),
);

/** Per thing: `field y=a,b s=c u=d ; field ...`. */
export const AUDIT: Readonly<Record<string, string>> = {
  "hobune": "has y=hammas,jalg,kabi,kael,karv,kõht,kõrv,nahk,nina,pea,saba,selg,silm,suu ; can y=jump,move,run s=climb,swim ; does y=grow,sleep s=buy,play,sell,wash ; use y=ride s=eat,sit ; where s=city,country,forest,garden,outdoors,street ; colour s=hall,kollane,must,pruun,punane,valge u=oranž,roosa,sinine ; made ; trait s=dangerous u=dry,round,sharp,thick,wet,wide ; feel y=fast,warm s=soft u=hard ; isa y=imetaja,loom s=toit",
  "kass": "has y=hammas,jalg,kael,karv,käpp,kõht,kõrv,küünis,nahk,nina,pea,saba,selg,silm,suu ; can y=climb,jump,move s=run,swim ; does y=grow,play,scratch,sleep s=buy,sell,wash ; use s=eat,wear ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,must,oranž,pruun,valge u=kollane,punane,roosa,sinine ; made ; trait s=dangerous,sharp u=dry,round,thick,wet,wide ; feel y=warm s=fast,soft u=hard,slow ; isa y=imetaja,loom",
  "koer": "has y=hammas,jalg,kael,karv,käpp,kõht,kõrv,küünis,nahk,nina,pea,saba,selg,silm,suu ; can y=move s=climb,jump,run,swim ; does y=bark,grow,play,sleep s=buy,scratch,sell,wash ; use s=eat,ride,wear ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,must,pruun,punane,valge u=oranž,roosa,sinine ; made ; trait s=dangerous,sharp u=dry,round,thick,wet,wide ; feel y=warm s=fast,soft u=hard,slow ; isa y=imetaja,loom s=toit",
  "lammas": "has y=hammas,jalg,kabi,kael,kõht,kõrv,nahk,nina,pea,saba,selg,silm,suu s=karv,sarv ; can y=jump,move,run s=climb,swim ; does y=grow,sleep s=buy,play,sell,wash ; use s=eat,ride,sit,wear ; where y=country s=city,forest,garden,outdoors,street ; colour s=must,pruun,valge u=hall,kollane,oranž,punane,roosa,sinine ; made ; trait s=dangerous u=dry,round,sharp,thick,wet,wide ; feel y=warm s=fast,soft u=hard,slow ; isa y=imetaja,loom s=toit",
  "lehm": "has y=hammas,jalg,kabi,kael,karv,kõht,kõrv,nahk,nina,pea,saba,selg,silm,suu s=sarv ; can y=move,run s=climb,jump,swim ; does y=grow,sleep s=buy,play,sell,wash ; use s=eat,ride,sit ; where y=country s=city,forest,garden,outdoors,street ; colour s=must,pruun,punane,valge u=hall,kollane,oranž,roosa,sinine ; made ; trait s=dangerous u=dry,round,sharp,thick,wet,wide ; feel y=warm s=fast,soft u=hard,slow ; isa y=imetaja,loom s=toit",
  "siga": "has y=hammas,jalg,kabi,kael,kõht,kõrv,nahk,nina,pea,saba,selg,silm,suu s=karv ; can y=move s=climb,jump,run,swim ; does y=grow,play,sleep s=buy,sell,wash ; use s=eat,ride,sit,wear ; where s=city,country,forest,garden,outdoors,street ; colour s=must,pruun,punane,roosa,valge u=hall,kollane,oranž,sinine ; made ; trait s=dangerous u=dry,round,sharp,thick,wet,wide ; feel y=warm s=fast,soft u=hard,slow ; isa y=imetaja,loom s=toit",
  "elevant": "has y=hammas,jalg,kael,kõht,kõrv,lont,nahk,pea,saba,selg,silm,suu s=kabi,karv,käpp,küünis,nina ; can y=move,swim s=run u=climb ; does y=grow,sleep s=bark,burn,play,wash u=scratch ; use s=ride,sit u=eat ; where y=outdoors s=country,forest,water u=city,street ; colour y=hall s=pruun,punane u=kollane,must,oranž,roosa,valge ; made ; trait s=dangerous u=dry,long,round,sharp,thick,thin,wide ; feel y=warm u=hard,soft ; isa y=imetaja,loom",
  "hiir": "has y=hammas,jalg,kael,karv,käpp,kõht,kõrv,nahk,nina,pea,saba,selg,silm,suu s=küünis ; can y=climb,jump,move,run,swim ; does y=grow,sleep s=burn,scratch u=bark,buy,play,sell ; use s=wear u=eat ; where s=city,country,garden,home,kitchen,outdoors u=forest,street,water ; colour s=hall,must,pruun,roosa,valge u=kollane,oranž,punane,sinine ; made ; trait u=dangerous,dry,long,round,sharp,thick,thin,wide ; feel y=warm u=fast,hard,slow,soft ; isa y=imetaja,loom",
  "hunt": "has y=hammas,jalg,kael,karv,käpp,kõht,kõrv,küünis,nahk,nina,pea,saba,selg,silm,suu ; can y=jump,move,run u=climb,swim ; does y=grow,play,sleep s=bark,burn,scratch ; use u=eat ; where y=outdoors s=country,forest u=city,garden,street,water ; colour s=hall,must,pruun,sinine,valge u=kollane,oranž,punane,roosa ; made ; trait s=dangerous,sharp u=dry,long,round,thick,thin,wide ; feel y=warm u=fast,hard,soft ; isa y=imetaja,loom",
  "jänes": "has y=hammas,jalg,kael,karv,kõht,kõrv,nahk,nina,pea,saba,selg,silm,suu s=käpp,küünis ; can y=jump,move,run s=swim u=climb ; does y=grow,sleep s=burn,buy,scratch,sell u=bark,play ; use s=eat ; where y=outdoors s=country,forest,garden u=city,street,water ; colour s=hall,kollane,must,pruun,punane,valge u=oranž ; made ; trait u=dangerous,dry,long,round,sharp,thick,thin,wide ; feel y=fast,warm u=hard,soft ; isa y=imetaja,loom s=toit",
  "karu": "has y=hammas,jalg,kael,karv,käpp,kõht,kõrv,küünis,nahk,nina,pea,saba,selg,silm,suu ; can y=move,run,swim s=climb u=jump ; does y=grow,play,sleep s=burn,scratch u=bark ; use u=eat ; where y=outdoors s=country,forest u=city,garden,street,water ; colour s=pruun,punane u=hall,kollane,must,oranž,valge ; made ; trait s=dangerous,sharp u=dry,long,round,thick,thin,wide ; feel y=warm u=fast,hard,soft ; isa y=imetaja,loom",
  "lõvi": "has y=hammas,jalg,kael,karv,kõht,kõrv,küünis,nahk,nina,pea,saba,selg,silm,suu s=käpp ; can y=jump,move,run s=climb,swim ; does y=grow,play,sleep s=burn,scratch u=bark ; use u=eat ; where y=outdoors s=country,forest ; colour s=hall,kollane,must,pruun,punane,valge u=oranž ; made ; trait s=dangerous,sharp u=dry,long,round,thick,thin,wide ; feel y=fast,warm u=hard,soft ; isa y=imetaja,loom",
  "rebane": "has y=hammas,jalg,kael,karv,käpp,kõht,kõrv,küünis,nahk,nina,pea,saba,selg,silm,suu ; can y=jump,move,run,swim u=climb ; does y=grow,sleep s=bark,burn,play,scratch ; use s=wear u=eat ; where y=outdoors s=city,country,forest,garden,street u=water ; colour s=hall,kollane,must,pruun,punane,valge u=oranž ; made ; trait s=dangerous,sharp u=dry,long,round,thick,thin,wide ; feel y=fast,warm u=hard,soft ; isa y=imetaja,loom",
  "kala": "has y=nahk,pea,saba,selg,silm,suu,uim s=hammas,nina,nokk,soomus u=kael,kõht ; can y=move,swim s=fly,jump u=climb ; does y=grow s=buy,sell,shine,sleep,wash u=play ; use s=eat,wear ; where y=water s=city,country,forest,fridge,garden,home,kitchen,outdoors,school,sea,shop ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made ; trait y=wet s=dangerous,long,salty,sharp u=round,thick,thin,wide ; feel s=cold,fast,slow,warm u=hard,soft ; isa y=loom s=toit",
  "kana": "has y=jalg,kael,kõht,küünis,nahk,nokk,pea,saba,selg,silm,sulg,tiib s=käpp,nina,soomus,suu ; can y=move,run s=fly,jump u=climb,swim ; does y=grow,scratch,sleep s=buy,sell u=play ; use s=eat,wear ; where s=city,country,forest,fridge,garden,home,kitchen,outdoors,shop,street ; colour s=hall,kollane,must,pruun,punane,sinine,valge u=lilla,oranž,roheline,roosa ; made ; trait s=round u=dangerous,dry,sharp,thick,thin,wet,wide ; feel y=warm u=fast,hard,slow,soft ; isa y=lind,loom s=toit",
  "konn": "has y=jalg,kõht,nahk,pea,selg,silm,suu s=hammas,käpp,küünis,nina u=kael ; can y=jump,move,swim s=climb,run ; does y=grow s=buy,sell u=play,sleep ; use s=eat,wear ; where s=city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street,water ; colour s=hall,kollane,must,oranž,pruun,punane,roheline,sinine,valge u=lilla,roosa ; made ; trait y=wet s=dangerous,dry,round,thick u=thin,wide ; feel s=cold,slow u=fast,hard,soft,warm ; isa y=loom s=toit",
  "liblikas": "has y=jalg,kõht,silm,soomus,tiib s=karv,koor,nahk,pea,saba,selg,suu u=küünis ; can y=fly,move s=climb u=jump,run,swim ; does s=grow u=buy,play,scratch,sell,sleep ; use s=wear u=eat ; where s=city,country,forest,garden,home,outdoors,sky,street ; colour s=kollane,must,oranž,pruun,punane,roheline,sinine,valge u=hall,lilla,roosa ; made ; trait u=dry,long,round,thick,thin,wet,wide ; feel s=fast u=cold,hard,slow,soft,warm ; isa y=loom,putukas u=toit",
  "mesilane": "has y=jalg,karv,kõht,silm,tiib s=hammas,koor,nahk,pea,selg,suu u=küünis,soomus ; can y=fly,move s=climb,run u=jump,swim ; does s=grow u=buy,play,scratch,sell,sleep ; use s=wear u=eat ; where s=city,country,forest,garden,home,outdoors,sky,street ; colour s=kollane,must,pruun u=hall,oranž,valge ; made ; trait s=dangerous,sharp u=dry,long,round,thick,thin,wet,wide ; feel u=cold,fast,hard,slow,soft,warm ; isa y=loom,putukas u=toit",
  "part": "has y=jalg,kael,kõht,nahk,nokk,pea,saba,selg,silm,sulg,tiib s=käpp,nina,soomus,suu u=küünis ; can y=move,swim s=climb,fly,run u=jump ; does y=grow,sleep s=buy,sell u=play,scratch ; use s=eat,wear ; where s=city,country,forest,fridge,garden,home,kitchen,outdoors,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,roheline,sinine,valge u=punane,roosa ; made ; trait s=round,wet,wide u=dangerous,dry,long,sharp,thick,thin ; feel y=warm u=fast,hard,slow,soft ; isa y=lind,loom s=toit",
  "banaan": "has y=koor s=kaas,nahk,seeme ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,must,pruun,punane,roheline,roosa,valge u=hall,lilla,oranž,sinine ; made ; trait y=long,sweet s=dry,sour,thick,wet u=thin,wide ; feel s=cold,hard,slow,soft,warm ; isa y=puuvili,toit s=ese,taim",
  "juust": "has s=kaas,koor,seeme,silm ; can s=swim ; does y=buy,sell s=burn ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,oranž,pruun,punane,roheline,sinine,valge u=hall,lilla,must,roosa ; made ; trait s=dangerous,dry,long,round,salty,sharp,sour,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese",
  "jäätis": "has s=koor,seeme ; can s=swim ; does y=buy,sell s=burn ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made ; trait y=sweet s=dry,long,round,salty,sour,thick,thin,wet,wide ; feel y=cold s=hard,slow,soft ; isa y=toit s=ese",
  "kartul": "has y=koor s=juur,kaas,leht,nahk,oks,seeme,silm,tüvi,õis ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,lilla,pruun,punane,roheline,sinine,valge u=hall,must,oranž,roosa ; made ; trait s=dangerous,dry,long,round,thick,wet,wide u=salty,sour,sweet,thin ; feel s=cold,hard,slow,soft,warm ; isa y=köögivili,toit s=ese,taim",
  "kook": "has s=kaas,koor,seeme ; can s=swim ; does y=buy,sell s=burn ; use y=eat s=wear,write ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made ; trait y=sweet s=dry,long,round,salty,sour,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese",
  "leib": "has y=koor s=seeme ; can s=swim ; does y=buy,sell s=burn ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,must,pruun,valge u=hall,lilla,oranž,punane,roheline,roosa,sinine ; made ; trait s=dry,long,round,salty,sour,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese",
  "muna": "has y=koor s=kaas,nahk ; can s=swim ; does y=buy,sell s=grow,wash ; use y=eat s=drink,wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,oranž,pruun,roheline,roosa,sinine,valge u=hall,lilla,must,punane ; made ; trait s=dangerous,dry,round,wet u=salty,sour,sweet,thick,thin,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese",
  "supp": "has ; can s=swim ; does y=buy,sell ; use y=eat s=drink,wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,lilla,must,oranž,pruun,punane,roheline,roosa,valge u=hall,sinine ; made ; trait y=wet s=salty,sharp,sour,sweet,thick,thin u=wide ; feel s=cold,slow,warm u=soft ; isa y=toit s=ese,jook",
  "õun": "has y=koor,seeme s=kaas,nahk,tüvi ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,lilla,must,oranž,pruun,punane,roheline,roosa,valge ; made ; trait s=dry,round,sour,sweet,thick,wet,wide u=thin ; feel s=cold,hard,slow,soft,warm ; isa y=puuvili,toit s=ese,taim",
  "apelsin": "has y=koor s=juur,leht,nahk,oks,seeme,tüvi,õis ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=bed,city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour y=oranž s=kollane,punane,roheline,valge u=hall,lilla,must,pruun,roosa,sinine ; made ; trait s=dry,long,round,sour,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=puuvili,toit s=ese,jook,taim",
  "kohv": "has ; can ; does y=buy,sell ; use y=drink s=wear ; where s=bed,city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=must,pruun u=hall,kollane,lilla,oranž,punane,roheline,roosa,sinine,valge ; made ; trait y=wet s=sour,sweet,thick,thin,wide ; feel s=cold,slow,soft,warm ; isa y=jook s=ese,toit",
  "liha": "has s=koor,nahk ; can s=swim ; does y=buy,sell s=burn,wash ; use y=eat s=wear ; where s=city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=pruun,punane,roosa,valge u=hall,kollane,lilla,must,oranž,roheline,sinine ; made ; trait s=dangerous,dry,long,round,salty,sour,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese",
  "maasikas": "has s=juur,koor,leht,nahk,seeme,tüvi,õis ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour y=punane s=roheline,roosa,valge u=hall,kollane,lilla,must,oranž,pruun,sinine ; made ; trait y=sweet s=dry,long,round,sour,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese,jook,puuvili,taim",
  "piim": "has s=nahk ; can ; does y=buy,sell ; use y=drink s=eat ; where s=bed,city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,valge u=hall,lilla,must,oranž,pruun,punane,roheline,roosa,sinine ; made ; trait y=wet s=salty,sour,sweet,thick,thin,wide ; feel s=cold,slow,soft,warm ; isa y=jook,toit s=ese",
  "porgand": "has s=juur,koor,leht,nahk,seeme,tüvi,õis ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour y=oranž s=kollane,lilla,must,punane,roheline,valge u=hall,pruun,roosa,sinine ; made ; trait s=dry,long,round,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=köögivili,toit s=ese,taim",
  "sibul": "has s=juur,koor,leht,nahk,seeme,tüvi,õis ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,lilla,pruun,punane,roheline,roosa,valge u=hall,must,oranž,sinine ; made ; trait s=dry,long,round,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=köögivili,toit s=ese,taim",
  "šokolaad": "has s=koor ; can s=swim ; does y=buy,sell s=burn ; use y=eat s=drink,wear ; where s=bed,city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=must,pruun,valge u=hall,kollane,lilla,oranž,punane,roheline,roosa,sinine ; made ; trait s=dry,long,round,salty,sour,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese,jook",
  "tomat": "has s=juur,koor,leht,nahk,oks,seeme,tüvi,õis ; can s=swim ; does y=buy,sell s=burn,grow,wash ; use y=eat s=wear ; where s=city,country,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=kollane,lilla,oranž,pruun,punane,roheline,roosa,valge u=hall,must,sinine ; made ; trait s=dry,long,round,sour,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese,köögivili,puuvili,taim",
  "vesi": "has ; can s=move ; does y=buy,sell ; use y=drink ; where y=water s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,sea,shop,sky,street ; colour s=sinine u=hall,kollane,pruun,roheline,valge ; made ; trait y=wet s=dangerous,salty,thick,thin,wide ; feel s=cold,fast,hard,slow,soft,warm ; isa y=jook s=ese,toit",
  "vorst": "has s=koor,nahk ; can s=swim ; does y=buy,sell s=burn,wash ; use y=eat s=wear ; where s=city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street ; colour s=must,pruun,punane,roosa,valge u=hall,kollane,lilla,oranž,roheline,sinine ; made ; trait s=dangerous,dry,long,round,salty,sour,sweet,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=toit s=ese",
  "arvuti": "has s=aken,ekraan,jalg,kaas,klaviatuur,nupp ; can ; does y=buy,sell,work s=burn,ring,shine ; use y=write s=read,wear ; where s=bed,city,country,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=klaas,metall,plast u=kuld,kumm,raud ; trait s=dry,thin u=thick,wide ; feel y=hard s=warm u=slow ; isa y=ese",
  "laud": "has s=jalg,leht,ratas ; can ; does y=buy,sell s=burn,wash ; use s=sit,wear,write ; where s=city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kivi,klaas,metall,plast,puit,raud u=kuld ; trait s=dry,round,wide u=thick,thin ; feel y=hard s=cold u=slow ; isa y=ese,mööbel",
  "pliiats": "has s=kaas,nupp ; can ; does y=buy,sell s=burn ; use y=wear,write ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kumm,metall,paber,plast,puit u=kivi,raud ; trait y=long s=dangerous,dry,round,sharp,thin ; feel y=hard u=slow ; isa y=ese",
  "raamat": "has y=kaas,leht s=selg ; can ; does y=buy,sell s=burn ; use y=read,wear s=write ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=paber s=kangas,metall,plast,puit u=puuvill ; trait s=dry,thick,thin,wide ; feel s=hard,soft u=slow ; isa y=ese",
  "telefon": "has y=nupp s=ekraan,kaas,klaviatuur u=aken ; can ; does y=buy,ring,sell,work s=burn,shine ; use s=read,wear,write ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=klaas,metall,plast u=kuld,kumm,puit,raud ; trait s=dry,thick,thin ; feel y=hard u=slow ; isa y=ese",
  "tool": "has s=jalg,ratas,selg ; can ; does y=buy,sell s=burn,wash ; use y=sit s=ride,wear ; where s=city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,metall,plast,puit u=kivi,klaas,kuld,puuvill,raud,vill ; trait s=dry u=round,thick,thin,wide ; feel s=cold,hard,soft u=slow ; isa y=ese,mööbel",
  "voodi": "has s=jalg,kaas,pea,ratas ; can ; does y=buy,sell s=burn u=wash ; use s=sit,wear ; where s=city,country,forest,garden,home,outdoors,school,sea,shop ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,metall,puit,puuvill,vill u=kivi,kuld,kumm,plast,raud ; trait s=dry,round,wide u=thick,thin ; feel s=hard,soft,warm u=cold,slow ; isa y=ese,mööbel",
  "aken": "has s=kaas,leht,nupp,uks ; can ; does s=burn,buy,sell,wash ; use s=write ; where s=city,country,forest,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kivi,klaas,kumm,metall,paber,plast,puit,raud ; trait s=dangerous,dry,long,round,sharp,thick,thin,wide ; feel s=cold,hard,slow ; isa s=ese",
  "kott": "has s=kaas,nupp,ratas,suu ; can s=swim ; does y=buy,sell s=burn,wash ; use y=wear s=read,sit,write ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,kuld,kumm,metall,paber,plast,puit,puuvill,vill ; trait s=dry,long,round,thick,thin,wide ; feel s=cold,hard,slow,soft,warm ; isa y=ese",
  "lamp": "has s=jalg,kaas,nupp,ratas ; can s=swim ; does y=buy,sell,shine s=burn,wash,work ; use s=wear,write ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,kivi,klaas,kuld,kumm,metall,paber,plast,puit,puuvill,raud ; trait s=dangerous,dry,long,round,sharp,thick,thin,wide ; feel s=hard,slow,soft,warm ; isa y=ese",
  "maja": "has y=uks s=aken ; can ; does s=burn,buy,sell,wash ; use ; where s=city,country,forest,garden,home,outdoors,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,kivi,klaas,metall,paber,plast,puit,raud ; trait s=dangerous,dry,long,round,sharp,thick,thin,wide ; feel s=cold,hard,slow,warm ; isa y=hoone s=ese",
  "pilet": "has ; can s=swim ; does y=buy s=burn,sell,wash ; use s=read,wear,write ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=metall,paber,plast ; trait s=dry,long,round,thin,wide ; feel s=hard,slow,soft ; isa s=ese",
  "prillid": "has ; can s=swim ; does y=buy,sell s=burn,wash ; use y=wear s=write ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=klaas,kuld,kumm,metall,paber,plast,puit,raud ; trait s=dry,long,round,thick,thin,wide ; feel s=hard,slow,soft ; isa y=ese",
  "uks": "has s=aken,leht,nupp,ratas,silm,uks ; can s=swim ; does s=burn,buy,sell,wash,work ; use s=write ; where s=city,country,forest,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kivi,klaas,kuld,kumm,metall,paber,plast,puit,raud ; trait s=dangerous,dry,long,round,thick,thin,wide ; feel s=cold,hard,slow ; isa y=ese",
  "võti": "has s=nupp ; can s=swim ; does s=burn,buy,sell,wash ; use s=wear,write ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,sea,shop,sky,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=metall s=kuld,kumm,plast,raud ; trait s=dry,long,round,sharp,thin,wide ; feel y=hard s=cold,slow ; isa y=ese",
  "jope": "has s=kaas,karv,nahk,nupp,selg,sulg ; can s=swim ; does y=buy,sell s=burn,shine,wash ; use y=wear ; where s=bed,city,country,forest,garden,home,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,kumm,plast,puuvill,vill u=kuld,metall,paber,raud ; trait s=dry,round,sharp,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=ese,riideese",
  "särk": "has s=nahk,nupp,selg ; can s=swim ; does y=buy,sell,wash s=burn ; use y=wear ; where s=bed,city,country,forest,garden,home,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=kangas s=plast,puuvill,vill u=kumm,paber ; trait s=dry,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=ese,riideese",
  "puu": "has y=juur,koor,tüvi s=leht,oks,seeme,õis ; can s=swim ; does y=burn,grow s=buy,sell ; use s=eat,sit,write ; where s=city,country,forest,garden,home,outdoors,school,sea,shop,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=puit ; trait s=dangerous,dry,long,round,sharp,thick,thin,wet,wide ; feel s=hard,slow,soft ; isa y=taim",
  "lill": "has y=õis s=juur,leht,oks,seeme,tüvi ; can s=climb,swim ; does y=buy,sell s=burn,grow ; use s=eat,wear ; where s=bed,city,country,forest,fridge,garden,home,kitchen,outdoors,school,shop,street,water ; colour s=kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge u=hall ; made ; trait s=dangerous,dry,long,round,sharp,thick,thin,wet,wide ; feel s=hard,slow,soft ; isa s=taim",
  "päike": "has ; can s=move ; does y=shine s=burn ; use ; where y=sky s=outdoors ; colour s=kollane,lilla,oranž,punane,roheline,roosa,sinine,valge u=hall,pruun ; made ; trait y=round s=dangerous,thick,wide u=dry ; feel y=warm s=fast,slow u=soft ; isa",
  "järv": "has ; can ; does ; use s=drink,ride ; where y=outdoors,water s=city,country,forest ; colour s=hall,kollane,must,pruun,punane,roheline,roosa,sinine,valge u=lilla,oranž ; made ; trait y=wet s=dangerous,long,round,salty,wide ; feel s=cold,hard,slow,warm ; isa",
  "mägi": "has s=jalg,juur,kaas,koor,selg ; can ; does s=grow ; use s=ride,sit ; where y=outdoors s=city,country,forest,sea ; colour s=hall,must,pruun,punane,roheline,valge u=kollane,lilla,oranž,roosa,sinine ; made y=kivi ; trait s=dangerous,dry,round,sharp,thick,wet,wide ; feel y=hard s=cold,slow,warm ; isa",
  "jõgi": "has s=oks,suu ; can s=move ; does ; use s=drink,ride ; where y=water s=city,country,forest,outdoors ; colour s=hall,pruun,roheline,sinine,valge u=kollane,lilla,must,oranž,punane,roosa ; made ; trait y=long,wet s=dangerous,dry,wide ; feel s=cold,fast,hard,slow,warm ; isa",
  "mets": "has s=juur,koor,leht,oks,seeme,tüvi,õis ; can ; does y=burn s=grow ; use ; where y=forest,outdoors s=city,country ; colour s=kollane,oranž,pruun,punane,roheline,valge u=hall,lilla,must,roosa,sinine ; made s=puit ; trait s=dangerous,dry,thick,wet,wide ; feel s=cold,slow,soft,warm ; isa",
  "king": "has s=karv,nahk,nina,ratas ; can s=swim ; does y=buy,sell s=burn,shine,wash ; use y=wear ; where s=city,country,forest,garden,home,kitchen,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,kumm,metall,paber,plast,puit,puuvill,vill u=kivi,klaas,kuld,raud ; trait s=dry,round,sharp,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=ese,riideese",
  "müts": "has s=karv,kõrv,nahk,nokk,nupp,sulg,õis ; can s=swim ; does y=buy,sell s=burn,wash ; use y=wear ; where s=bed,city,country,forest,garden,home,kitchen,outdoors,school,sea,shop,street,water ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,paber,plast,puuvill,vill u=kivi,klaas,kuld,kumm,metall,puit,raud ; trait s=dry,round,sharp,thick,thin,wet,wide ; feel s=cold,hard,slow,soft,warm ; isa y=ese,riideese",
  "auto": "has y=aken,ratas,rool,uks s=ekraan,hammas,nupp,tiib u=kaas ; can y=move ; does y=buy,sell,work s=burn,shine,wash u=ring ; use y=ride,sit ; where s=city,country,forest,garden,home,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=metall s=kangas,klaas,kumm,plast,puit,raud u=puuvill,vill ; trait y=dangerous s=round u=dry,thick,thin,wet,wide ; feel y=fast s=hard,soft u=cold,warm ; isa y=ese,sõiduk",
  "buss": "has y=aken,ratas,rool,uks s=ekraan,hammas,nupp u=kaas ; can y=move ; does y=work s=burn,buy,sell,shine,wash u=ring ; use y=ride s=sit ; where s=city,country,forest,outdoors,school,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,klaas,kumm,metall,plast,puit,raud u=puuvill,vill ; trait s=dangerous,long u=dry,thick,thin,wet,wide ; feel y=fast s=hard,soft u=cold,warm ; isa y=ese,sõiduk",
  "jalgratas": "has y=ratas,rool s=ekraan,hammas,jalg,nupp u=kaas ; can s=move ; does y=buy,sell s=burn,ring,shine,wash,work ; use y=ride,sit s=wear ; where s=city,country,forest,garden,home,outdoors,school,shop,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,klaas,kumm,metall,plast,puit,raud ; trait s=dangerous,long,round u=dry,thick,thin,wet ; feel s=fast,hard,soft u=cold,warm ; isa y=ese,sõiduk",
  "laev": "has y=uks s=aken,ekraan,hammas,nina,nupp,ratas,rool,uim u=kaas ; can y=move,swim ; does y=work s=burn,buy,ring,sell,shine,wash ; use y=ride s=sit ; where y=water s=city,outdoors,sea ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,klaas,kumm,metall,plast,puit,raud u=puuvill,vill ; trait s=dangerous,dry,long,wet,wide u=thick,thin ; feel s=fast,hard,slow,soft u=cold,warm ; isa y=ese,sõiduk",
  "lennuk": "has y=aken,ratas,tiib,uks s=ekraan,hammas,nina,nupp,rool,saba,uim u=kaas ; can y=fly,move s=swim ; does y=work s=burn,buy,sell,shine,wash u=ring ; use y=ride s=sit ; where s=city,country,outdoors,sky ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made s=kangas,klaas,kumm,metall,plast,puit,raud u=puuvill,vill ; trait s=dangerous,long,round u=dry,thick,thin,wet,wide ; feel y=fast s=hard,soft u=cold,warm ; isa y=ese,sõiduk",
  "rong": "has y=aken,ratas,uks s=ekraan,hammas,nupp u=kaas ; can y=move ; does y=work s=burn,ring,shine,wash u=buy,sell ; use y=ride,sit ; where s=city,country,forest,outdoors,street ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=metall s=kangas,klaas,kumm,plast,puit,raud u=puuvill,vill ; trait s=dangerous,long u=dry,thick,thin,wet,wide ; feel y=fast s=hard,soft u=cold,warm ; isa y=ese,sõiduk",
  "tramm": "has y=ratas,uks s=ekraan,hammas,nupp u=aken,kaas ; can y=move ; does y=work s=burn,ring,shine,wash u=buy,sell ; use y=ride s=sit ; where y=city,street s=country,forest,outdoors ; colour s=hall,kollane,lilla,must,oranž,pruun,punane,roheline,roosa,sinine,valge ; made y=metall s=kangas,klaas,kumm,plast,puit,raud u=puuvill,vill ; trait s=dangerous,long u=dry,thick,thin,wet,wide ; feel s=fast,hard,soft u=cold,warm ; isa y=ese,sõiduk",
};
