/*
  NOTHING A READER SEES MAY SOUND LIKE IT WAS GENERATED.

  Not a style preference. Every screen in this app is one person explaining
  Estonian to another, and somebody using it is usually also sitting in a class
  or reading a textbook. A learner skims marketing. They do not skim a teacher,
  so the moment a panel starts sounding like a brochure it stops being read the
  way the thing beside it is read.

  This sweeps for the mechanical half of that: the dash used as a clause break,
  which is the loudest single tell there is, and every phrase and sentence
  shape in `lib/copy/voice.ts`. The dash rule came first and was the only one
  with a sweep behind it. The vocabulary rule existed in three places that did
  not agree, and the one covering hand-written copy covered six files out of
  four hundred, so a phrase Anu was forbidden from using was fine in the panel
  next to her. There is one table now and all three readers of it are here, in
  `lib/tutor/humanize.ts` and in `lib/tutor/prompt.ts`.

  It walks the whole of `app/`, `lib/` and `components/` rather than a list of
  screens somebody remembered to keep up to date, because a rule that only
  holds where it was last checked is a rule that decays. `ALLOWED` below is
  the exceptions, and every one of them is a place where the character or the
  phrase is data rather than copy: something matched against, something
  stripped out, something parsed. Adding to it means arguing that a reader
  still cannot see it. It is not a place to park copy that has not been fixed
  yet, and the stale-exception test is what keeps that true.

  WHAT THIS CANNOT SEE is whether a sentence is warm, and whether it is short
  enough. Those are the other half of the rule and they are a review standard
  written out with worked examples in `docs/18-voice.md`, because no regex
  tells kind from cold. What is here is the half a machine can hold.
*/
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { EM_DASH as EM, EMOJI, EN_DASH as EN, TELLS, findTells } from "./voice";

/**
 * Files allowed to break one of these rules, which rule, and why.
 *
 * Per rule rather than per file, because these exemptions are not the same
 * exemption: the table has to name the characters it strips, and the standard
 * has to name the phrases it bans and show the copy it exists to prevent.
 * Neither has any business carrying a dash it did not mean, and
 * `docs/18-voice.md` is swept for one like anything else.
 *
 * `only` narrows it further, to the tells a file is excused for by name. That
 * exists because the third entry is not a file about the voice at all: it
 * parses somebody else's JSON, and one key of it is spelled with a word this
 * table bans. Excusing that file from the whole list would have handed it
 * every brochure word as well, for one key it does not own.
 */
const ALLOWED = new Map<string, { rules: Rule[]; only?: string[]; why: string }>([
  [
    "lib/copy/voice.ts",
    {
      rules: ["dash", "tell"],
      why: "Is the table. It has to name every character and phrase it bans, and deleting them here deletes the rule.",
    },
  ],
  [
    "docs/18-voice.md",
    {
      rules: ["tell"],
      why: "Is the standard. It names every banned phrase and quotes the generated copy it exists to prevent.",
    },
  ],
  [
    "lib/collections/emoji.ts",
    {
      rules: ["emoji"],
      why:
        "Is the table of which word has a picture, generated by scripts/build-emoji.ts from " +
        "Unicode's own data and the dictionary's glosses. The emoji here are data rather than " +
        "copy, in the sense this rule means: nobody reads this file, and the ban exists because " +
        "an emoji in a sentence reads as marketing. Excused for the emoji rule only, so a " +
        "brochure word or a stray dash in it still fails.",
    },
  ],
  [
    "prisma/data/harvested.ts",
    {
      rules: ["dash"],
      why: "Is generated, and its dashes are all inside Estonian a lexicographer recorded: a street number, a range of years, a dash opening a line of speech. Rewriting one would be this app editing Ekilex's sentences (ADR-005). Its one authored column, the gloss, is written in lib/collections/syllabus/ and swept there.",
    },
  ],
  [
    "lib/ekilex/client.ts",
    {
      rules: ["tell"],
      only: ["paradigm"],
      why: "Types Ekilex's own response, and their key for a set of forms is the word this table bans. Renaming a key we do not own would be renaming their data rather than ours.",
    },
  ],
]);

/**
 * Whether a file is excused from a rule outright.
 *
 * A file excused from named tells only is not excused from the rule, which is
 * what keeps the emoji sweep (the visual form of the same rule) reaching it.
 */
type Rule = "dash" | "tell" | "emoji";

function excused(file: string, rule: Rule): boolean {
  const entry = ALLOWED.get(file);
  if (!entry?.rules.includes(rule)) return false;
  return rule !== "tell" || entry.only === undefined;
}

/** Whether a file is excused from one tell, by that tell's name. */
function excusedTell(file: string, name: string): boolean {
  const entry = ALLOWED.get(file);
  if (!entry?.rules.includes("tell")) return false;
  return entry.only === undefined || entry.only.includes(name);
}

/**
 * Strip a trailing `//` comment without cutting inside a string.
 *
 * A naive `indexOf("//")` eats the rest of any line holding a URL, which would
 * quietly hide real copy from this check rather than fail on it.
 */
function stripTrailingComment(line: string): string {
  let quote: string | null = null;
  for (let i = 0; i < line.length; i += 1) {
    const c = line[i]!;
    if (quote) {
      if (c === "\\") i += 1;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") {
      quote = c;
      continue;
    }
    if (c === "/" && line[i + 1] === "/") return line.slice(0, i);
  }
  return line;
}

/**
 * Lines a reader could see: not `//`, not a block comment, not `{/* *\/}`.
 *
 * Comments are for whoever maintains this and may punctuate however they
 * like. The rule is about the product, not the source.
 */
function readerFacingLines(file: string): { line: number; text: string }[] {
  const out: { line: number; text: string }[] = [];
  let inBlock = false;
  readFileSync(file, "utf8")
    .split("\n")
    .forEach((raw, i) => {
      const trimmed = raw.trim();
      if (inBlock) {
        if (trimmed.includes("*/")) inBlock = false;
        return;
      }
      if (trimmed.startsWith("/*") || trimmed.startsWith("{/*")) {
        if (!trimmed.includes("*/")) inBlock = true;
        return;
      }
      if (trimmed.startsWith("//") || trimmed.startsWith("*")) return;
      out.push({ line: i + 1, text: stripTrailingComment(raw) });
    });
  return out;
}

function sourceFiles(dir: string, extensions = /\.(ts|tsx)$/): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === ".next") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...sourceFiles(full, extensions));
    // Test files are exempt on purpose: no test renders to anybody, so a dash
    // in one is source. Excluding them is also what lets this file, which has
    // to name the character, stay out of the exception list. `.itest.ts` is
    // the database-backed half of the same suite and is exempt for the same
    // reason, not because it was easier than fixing one.
    else if (extensions.test(entry) && !/\.i?test\.tsx?$/.test(entry)) out.push(full);
  }
  return out;
}

/*
  `flatMap(sourceFiles)` would hand the array index in as the second argument,
  which is how a default parameter gets silently overridden with a number.

  AND `prisma/` IS IN IT, BECAUSE THE SEED IS COPY. This was three directories
  of source, and the hand-written seed data is a fourth: `prisma/data/other.ts`
  carries the note printed under `Tere hommikust!` on the dictionary entry, and
  `verbs.ts` and `advanced.ts` carry the government line printed under
  `Government · rektsioon`. Nine of those reached a learner's screen with an em
  dash in them, six on the A1 greetings, which is the first unit anybody opens.
  `lib/collections/syllabus/` was already swept for exactly this reason and
  happens to live under `lib`; where the same kind of authored English sits
  decided whether the rule reached it.
*/
const FILES = ["app", "components", "lib", "prisma"].flatMap((dir) => sourceFiles(dir));

/**
 * The prose of a markdown file.
 *
 * A fenced block and an inline code span are data, exactly as a string literal
 * is in the source tree: `docs/04-data-model.md` quotes the Prisma schema and
 * `docs/10-testing-quality.md` quotes the grep the secret scan runs, and
 * rewriting the punctuation inside either would be rewriting the thing being
 * quoted. It is also how a document names a banned phrase without using one,
 * which is what keeps the exemption list down to the one file that has to
 * *show* the copy rather than merely name it.
 */
function markdownProse(file: string): { line: number; text: string }[] {
  const out: { line: number; text: string }[] = [];
  let fenced = false;
  readFileSync(file, "utf8")
    .split("\n")
    .forEach((raw, i) => {
      if (/^\s*(```|~~~)/.test(raw)) {
        fenced = !fenced;
        return;
      }
      if (fenced) return;
      out.push({ line: i + 1, text: raw.replace(/`[^`]*`/g, " ") });
    });
  return out;
}

/**
 * Every page written for a reader rather than for a compiler.
 *
 * `docs/` was left out of this when the rule was first written, on the
 * argument that those pages are read by contributors rather than by learners.
 * That was true and it was not a reason: they are still somebody explaining
 * something to somebody, they are the first thing a new contributor reads, and
 * a project whose own documentation is written in the voice it forbids on
 * screen is teaching the next person which of its rules are real. There were
 * 388 dashes behind that argument, and three of them were the `NO_VALUE` fault
 * from the source tree wearing a different hat: an empty cell in a table of
 * forms, in the four-states table and in the degradation table, each written as
 * a bare dash that a mechanical sweep would have turned into a comma.
 */
const MARKDOWN = ["CLAUDE.md", "README.md", ...sourceFiles("docs", /\.md$/)];

function offenders(character: string): string[] {
  return FILES.filter((f) => !excused(f, "dash")).flatMap((f) =>
    readerFacingLines(f)
      .filter((l) => l.text.includes(character))
      .map((l) => `${f}:${l.line}: ${l.text.trim()}`),
  );
}

describe("copy reads as a person wrote it", () => {
  it("finds the source tree it is supposed to be checking", () => {
    expect(FILES.length).toBeGreaterThan(100);
    expect(FILES).toContain("components/Sidebar.tsx");
    expect(FILES).toContain("app/(chromeless)/welcome/page.tsx");
  });

  it("has no em dash a reader could see", () => {
    expect(offenders(EM)).toEqual([]);
  });

  it("has no en dash a reader could see", () => {
    expect(offenders(EN)).toEqual([]);
  });

  /*
    The README is the other page a stranger reads before the app, and `docs/`
    is what the next person to work here reads first. A project whose own
    documentation is written in the voice it forbids on screen has told that
    person which of its rules are real.
  */
  it("finds the documentation it is supposed to be checking", () => {
    expect(MARKDOWN).toContain("README.md");
    expect(MARKDOWN).toContain("CLAUDE.md");
    expect(MARKDOWN).toContain("docs/03-architecture.md");
    expect(MARKDOWN.length).toBeGreaterThan(15);
  });

  it("has no dash a reader could see in the README or the docs", () => {
    const bad = MARKDOWN.filter((f) => !excused(f, "dash")).flatMap((f) =>
      markdownProse(f)
        .filter((l) => l.text.includes(EM) || l.text.includes(EN))
        .map((l) => `${f}:${l.line}: ${l.text.trim().slice(0, 100)}`),
    );
    expect(bad).toEqual([]);
  });

  /*
    Keeps the exception list honest. An entry naming a file that no longer
    contains a dash is an entry that has become a parking space, and the next
    person to need one will add theirs beside it.
  */
  it("has no stale exception", () => {
    const stale = [...ALLOWED.entries()].filter(([file, entry]) => {
      const source = readFileSync(file, "utf8");
      const found = findTells(source).map((t) => t.name);
      return entry.rules.some((r) => {
        if (r === "dash") return !(source.includes(EM) || source.includes(EN));
        // An emoji exemption is stale the moment the file stops holding one,
        // which is what stops it becoming a parking space for the next
        // component that wants to put a picture in a sentence.
        if (r === "emoji") return !EMOJI.test(source);
        return entry.only ? !entry.only.some((n) => found.includes(n)) : found.length === 0;
      });
    });
    expect(stale.map(([f]) => f)).toEqual([]);
  });
});

/*
  HOW MUCH OF IT THERE IS, WHICH IS THE OTHER WAY COPY STOPS BEING READ.

  Everything above this point is about how a sentence sounds. Nothing in it can
  see the fault that actually made this app feel like work: there were simply
  too many good sentences. Thirty-nine dead ends each explained the whole
  feature to somebody who could not use it yet, and the dictation screen spent
  forty-one words on where Ekilex sentences come from, and why a sentence you
  cannot hold in your head tests memory rather than listening, to a learner
  whose deck was empty and who wanted the button. Every one of those sentences
  passes every rule above.

  So there is a ceiling, and it is deliberately generous rather than tight: a
  dead end may say one line, and a page may introduce itself in one line. The
  measured worst in the tree when this was written was 88 characters on both,
  so these are not caps somebody has to fight, they are caps that catch the
  paragraph coming back. What they cannot do is make a short sentence a good
  one, which is `docs/18-voice.md`'s job as before.

  Deliberately NOT capped: prose in the body of a screen, a grammar
  explanation, the policy pages. A page whose subject is an explanation is
  allowed to explain. What is capped is the furniture around the thing a
  reader came for.
*/

/** A dead end gets one line. */
const EMPTY_BODY_MAX = 100;
/** A page introduces itself in one line. */
const LEAD_MAX = 95;

/**
 * The value of a JSX prop, as the strings a reader could end up seeing.
 *
 * `body="..."` is one string; `body={a ? "..." : "..."}` is two, and both
 * reach a reader, so both are measured. A template literal is measured with
 * its holes standing in at two characters, which is what a count or a level
 * renders as: the point is to catch a paragraph, not to argue about whether
 * a card total is one digit or three.
 */
function propStrings(source: string, prop: string): string[] {
  const out: string[] = [];
  const re = new RegExp(`\\b${prop}=`, "g");
  let m: RegExpExecArray | null;
  while ((m = re.exec(source))) {
    let i = m.index + m[0].length;
    if (source[i] === '"') {
      const end = source.indexOf('"', i + 1);
      if (end !== -1) out.push(source.slice(i + 1, end));
      continue;
    }
    if (source[i] !== "{") continue;
    // Walk the braced expression, skipping over anything inside a string so a
    // brace in a style object or a `${}` hole cannot end it early.
    let depth = 0;
    const start = i;
    let quote: string | null = null;
    for (; i < source.length; i += 1) {
      const c = source[i]!;
      if (quote) {
        if (c === "\\") i += 1;
        else if (c === quote) quote = null;
        continue;
      }
      if (c === '"' || c === "'" || c === "`") quote = c;
      else if (c === "{") depth += 1;
      else if (c === "}") {
        depth -= 1;
        if (depth === 0) break;
      }
    }
    const expr = source.slice(start + 1, i);
    // A JSX child of its own is markup rather than copy, and this is not a
    // parser. Anything holding a tag is left to a person to judge.
    if (/<[A-Za-z]/.test(expr)) continue;
    for (const lit of joinConcatenations(expr).match(/"[^"\\]*"|`[^`\\]*`/g) ?? []) {
      out.push(lit.slice(1, -1).replace(/\$\{[^}]*\}/g, "NN"));
    }
  }
  return out;
}

/**
 * `"a" + "b"` collapsed into `"ab"`, so a sentence built out of fragments is
 * measured as the sentence a reader sees.
 *
 * This is how the mock exam hub's lead came to be 278 characters under a
 * 95-character ceiling: four string literals, each comfortably short, joined
 * with `+`, and the sweep pushed each of them separately. A `?` between two
 * literals is genuinely two readings and stays two.
 */
export function joinConcatenations(expr: string): string {
  let joined = expr;
  for (let pass = 0; pass < 40; pass += 1) {
    const next = joined.replace(/"([^"\\]*)"\s*\+\s*"([^"\\]*)"/, (_, a: string, b: string) => `"${a}${b}"`);
    if (next === joined) return joined;
    joined = next;
  }
  return joined;
}

/** Every `<Empty ... />` block in a file, markup and all. */
function emptyBlocks(source: string): string[] {
  const out: string[] = [];
  for (const m of source.matchAll(/<Empty\b/g)) {
    const rest = source.slice(m.index);
    const selfClose = rest.indexOf("/>");
    const paired = rest.indexOf("</Empty>");
    const end = selfClose !== -1 && (paired === -1 || selfClose < paired) ? selfClose + 2 : paired + 8;
    if (end > 1) out.push(rest.slice(0, end));
  }
  return out;
}

describe("there is not too much of it", () => {
  /*
    The same argument the sweep above makes about itself. A budget that has
    stopped finding the components it measures is a budget that passes
    everything, and it would do that silently on the day somebody renames a
    prop.
  */
  /*
    And it measures a sentence rather than the pieces it was typed in. The
    exam hub's lead was four literals joined with `+`, so every fragment
    cleared the ceiling and the rendered lead was three times it.
  */
  it("measures a lead built out of joined fragments as one sentence", () => {
    const source = 'lead={\n  "One two three. " +\n  "Four five six."\n}';
    expect(propStrings(source, "lead")).toEqual(["One two three. Four five six."]);
    // A conditional is two readings and stays two.
    expect(propStrings('lead={x ? "Yes." : "No."}', "lead")).toEqual(["Yes.", "No."]);
  });

  it("finds the dead ends and the page leads it is supposed to be measuring", () => {
    const empties = FILES.flatMap((f) => emptyBlocks(readFileSync(f, "utf8")));
    const leads = FILES.flatMap((f) => propStrings(readFileSync(f, "utf8"), "lead"));
    expect(empties.length).toBeGreaterThan(30);
    expect(leads.length).toBeGreaterThan(20);
  });

  it("gives a dead end one line, not a paragraph", () => {
    const over = FILES.flatMap((f) =>
      emptyBlocks(readFileSync(f, "utf8"))
        .flatMap((block) => propStrings(block, "body"))
        .filter((body) => body.length > EMPTY_BODY_MAX)
        .map((body) => `${f}: ${body.length} chars: ${body.slice(0, 70)}`),
    );
    expect(over).toEqual([]);
  });

  it("lets a page introduce itself in one line", () => {
    const over = FILES.flatMap((f) =>
      propStrings(readFileSync(f, "utf8"), "lead")
        .filter((lead) => lead.length > LEAD_MAX)
        .map((lead) => `${f}: ${lead.length} chars: ${lead.slice(0, 70)}`),
    );
    expect(over).toEqual([]);
  });
});

/*
  The other half of the rule, and the half that bit twice while it was being
  applied.

  Some code has to *read* a dash: a pasted word list separated by one, a
  dictated Ekilex sentence with one standing on its own, a stored translation
  whose placeholder used to be one. A sweep that cannot tell those from copy
  rewrites them, and the damage is silent: a word list stops splitting, a
  stray dash becomes a word the learner has to type, every old placeholder
  starts looking like a translation somebody chose. Both were rewritten once
  before this test existed.

  So they are written with escapes, which keeps them out of the sweep's way
  and out of the exception list, and this asserts they still read all three
  characters rather than that a particular regex is spelled a particular way.
*/
describe("the code that reads a dash still reads every one of them", () => {
  it("splits a pasted word list on any dash somebody typed", async () => {
    const source = readFileSync("app/(app)/settings/ImportPanel.tsx", "utf8");
    const pattern = source.match(/const DASH_SEPARATED = (\/.+\/);/)?.[1];
    expect(pattern, "DASH_SEPARATED is gone or renamed").toBeTruthy();
    const separator = new RegExp(pattern!.slice(1, -1));
    for (const dash of [EM, EN, "-"]) {
      expect(`tuba ${dash} room`.split(separator)).toEqual(["tuba", "room"]);
    }
    expect(separator.test("tuba, room")).toBe(false);
  });

  it("cuts a stored government string at any dash the dictionary carries", async () => {
    const { parseGovernment } = await import("@/lib/estonian/government");
    for (const dash of [EM, EN, "-"]) {
      const parsed = parseGovernment(`Partitive ${dash} aitan sind (I help you)`);
      expect(parsed?.caseKey, `a ${dash} separator stopped parsing`).toBe("PARTITIVE");
      expect(parsed?.example).toBe("aitan sind");
      expect(parsed?.gloss).toBe("I help you");
    }
  });

  it("strips a dash off a word before checking the learner used the form", async () => {
    const { checkForm } = await import("@/lib/estonian/writing");
    // Without the dash in the punctuation class the token stays "toas-see",
    // the whole-word match fails, and a correct sentence is marked wrong.
    const task = { targetForm: "toas" } as Parameters<typeof checkForm>[1];
    for (const dash of [EM, EN]) {
      expect(checkForm(`Ma olen toas${dash}see on hea`, task, []).used).toBe(true);
    }
  });

  it("strips a dash standing on its own out of a dictated sentence", async () => {
    const { dictationWords } = await import("@/lib/estonian/dictation");
    // A dash between two words is punctuation, not something to type back.
    for (const dash of [EM, EN]) {
      expect(dictationWords(`Tere ${dash} kuidas läheb`)).toEqual(["Tere", "kuidas", "läheb"]);
    }
  });
});

describe("nothing a reader sees is written in brochure", () => {
  /*
    Same argument as the dash, and now the same sweep. This used to run over
    six hand-listed public files, which is how a rule quietly narrows to the
    screens somebody happened to be looking at: the landing page was covered
    and the 73-unit course page, the exam briefing and every empty state were
    not. The table is `lib/copy/voice.ts` and Anu is asked for the same list,
    so what she may not say is what a panel may not say.
  */
  it("says the plain thing, on every screen", () => {
    const bad = FILES.flatMap((f) =>
      readerFacingLines(f).flatMap((l) =>
        findTells(l.text)
          .filter((t) => !excusedTell(f, t.name))
          .map((t) => `${f}:${l.line}: [${t.name}] ${l.text.trim().slice(0, 100)}`),
      ),
    );
    expect(bad).toEqual([]);
  });

  it("says the plain thing in the README and the docs too", () => {
    const bad = MARKDOWN.flatMap((f) =>
      markdownProse(f).flatMap((l) =>
        findTells(l.text)
          .filter((t) => !excusedTell(f, t.name))
          .map((t) => `${f}:${l.line}: [${t.name}] ${l.text.trim().slice(0, 100)}`),
      ),
    );
    expect(bad).toEqual([]);
  });

  /*
    An emoji at the head of a bullet is the visual form of the same tell, and
    it would be going around an icon system this app already has: data that
    drives UI carries a lucide icon name and `components/icons.tsx` is the only
    place one becomes a component. The pattern is deliberately narrow, for the
    reason written beside it in `voice.ts`: the arrow in "Estonian to English",
    the return key in a keyboard hint and the tick on the week strip are
    typographic glyphs doing a job, and a sweep that took those out would be
    waived by the first person it inconvenienced.
  */
  it("uses its own icons rather than emoji", () => {
    const inSource = FILES.filter((f) => !excused(f, "emoji") && !excused(f, "tell")).flatMap((f) =>
      readerFacingLines(f)
        .filter((l) => EMOJI.test(l.text))
        .map((l) => `${f}:${l.line}: ${l.text.trim().slice(0, 100)}`),
    );
    const inDocs = MARKDOWN.filter((f) => !excused(f, "emoji") && !excused(f, "tell")).flatMap((f) =>
      markdownProse(f)
        .filter((l) => EMOJI.test(l.text))
        .map((l) => `${f}:${l.line}: ${l.text.trim().slice(0, 100)}`),
    );
    expect([...inSource, ...inDocs]).toEqual([]);
  });
});

/*
  The table, checked against itself.

  A ban list nobody has watched fail is a ban list of unknown state, and the
  expensive failure here is not a missing tell, it is a tell that fires on
  honest copy: a check everybody waives is a check nobody reads. Both
  directions are asserted, and the second list is the sentences that actually
  tripped an earlier draft of this table while it was being written.
*/
describe("the voice table catches what it claims to and nothing else", () => {
  it("has an instead for every tell, so a failure says what to write", () => {
    for (const tell of TELLS) {
      expect(tell.instead.length, `${tell.name} has no replacement to suggest`).toBeGreaterThan(10);
      expect(tell.find.flags, `${tell.name} is case sensitive`).toContain("i");
    }
  });

  it("catches the phrases it exists for", () => {
    const generated = [
      "It's important to note that Estonian has fourteen cases.",
      "At the end of the day, practice is what matters.",
      "Great question! The partitive is used here.",
      "In conclusion, keep reviewing every day.",
      "Moreover, the genitive stem carries the whole set of forms.",
      "This is not just a rule, but a pattern you will see everywhere.",
      "Estonian is more than just a language.",
      "Let's delve into the partitive.",
      "Leverage our seamless, cutting-edge learning platform.",
      "Embark on your Estonian journey today.",
      "Unlock the power of spaced repetition.",
      "Whether you're a beginner or an advanced speaker, we've got you covered.",
      "Amazing work! That was fantastic.",
      "As an AI, I cannot be certain about that form.",
      "Learn the genitive and the rest of the paradigm follows.",
    ];
    for (const line of generated) {
      expect(findTells(line).map((t) => t.name), `nothing caught: ${line}`).not.toEqual([]);
    }
  });

  it("leaves honest copy alone", () => {
    const written = [
      "The recordings unlock once you have read the questions.",
      "Level 4, 120 XP to the next level.",
      "Whether you are stating, supposing, instructing or passing on something you did not witness.",
      "Navigate the health system and discuss public health policy.",
      "Not just answered right once.",
      "The perfect tense is taisminevik, and it is built on the tud-participle.",
      "Six days in a row. Your longest run so far.",
      "We could not reach Ekilex, so this word has no forms yet.",
      "Fill in what you know. The genitive alone unlocks all eleven regular cases.",
    ];
    for (const line of written) {
      expect(findTells(line).map((t) => t.name), `false positive: ${line}`).toEqual([]);
    }
  });
});

/*
  A SCREEN MAY NOT PROMISE A FEATURE THE APP WITHDREW.

  XP went with the badges and the daily quest meters, and the sweep that
  guards that removal reads *code*: it fails on a file reaching for
  `xpForRating` or `AchievementToasts`, and there are none left. Copy is the
  half it cannot see, and three sentences went on naming it for as long as the
  removal has existed. Two of them were the worst places available for it.

  The first is step one of first run, on the line under the only question that
  screen asks by name, so the first thing this app ever told a stranger about
  their own data named something that does not exist. The second is the
  sentence on the class join form saying what a teacher will see, which is the
  one screen whose entire job is to be accurate about that: it promised a
  figure nothing shares and left out `lastSeen`, which is shared. The third
  says the same thing again in Settings.

  A word rather than a symbol, because `XP` is ordinary English in a comment
  explaining why it went and this reads only what a person sees.
*/
describe("nothing on screen names a feature that was taken out", () => {
  const WITHDRAWN = /\bXP\b/;

  it("no reader-facing line mentions XP", () => {
    const found = FILES.flatMap((file) =>
      readerFacingLines(file)
        .filter(({ text }) => WITHDRAWN.test(text))
        .map(({ line }) => `${file}:${line}`),
    );
    expect(found).toEqual([]);
  });
});
