import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * ESLint, on the flat config the CLI actually uses.
 *
 * `next lint` is deprecated in Next 15 and gone in 16; worse, with no config on
 * disk it drops into an interactive setup prompt, so `npm run lint` hung in CI
 * and in any non-interactive shell. `eslint .` reads this file and exits with a
 * status, which is the only behaviour a lint script is useful for.
 *
 * `eslint-config-next` ships native flat configs from 16, so its two entry
 * points are spread in directly. They used to come through `FlatCompat`,
 * which is the shape Next's own codemod produced while the package was still
 * eslintrc-only; on 16 that path throws "Converting circular structure to
 * JSON" before a single file is linted, because the legacy validator tries to
 * serialise a flat config whose plugins reference themselves.
 */
const config = [
  {
    ignores: [
      ".next/**",
      // The hosted-mode build scripts/test-signin.mjs makes for itself, which
      // is the same build output under a different name (see `distDir` in
      // next.config.ts). Without this, linting the repository lints a Next
      // build: 2,440 errors in generated chunks nobody wrote.
      ".next-signin/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by Prisma, and not ours to style.
      "prisma/generated/**",
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    rules: {
      /*
       * Project rules, each one earning its place rather than inherited wholesale.
       */

      // CLAUDE.md: "No `any` without a comment justifying it." The rule cannot
      // read comments, so it warns rather than errors — it is a prompt to
      // justify, not a block.
      "@typescript-eslint/no-explicit-any": "warn",

      // Unused code is usually a leftover from a refactor. `_`-prefixed names
      // are the escape hatch for a deliberately ignored argument.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      // Estonian text is full of apostrophes and quotes; React's own rule about
      // escaping them catches real rendering bugs, so it stays on.
      "react/no-unescaped-entities": "error",
    },
  },

  {
    // The browser test scripts are Node programs, not app code: they use
    // top-level await, console output and Playwright's own globals.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { console: "readonly", process: "readonly", Buffer: "readonly", URL: "readonly" },
    },
  },

  {
    // The service worker runs in a worker scope, where `self`, `caches` and
    // `Response` are the globals and there is no DOM.
    files: ["public/sw.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        self: "readonly",
        caches: "readonly",
        fetch: "readonly",
        Response: "readonly",
        URL: "readonly",
      },
    },
  },
];

export default config;
