import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * ESLint, on the flat config the CLI actually uses.
 *
 * `next lint` is deprecated in Next 15 and gone in 16; worse, with no config on
 * disk it drops into an interactive setup prompt, so `npm run lint` hung in CI
 * and in any non-interactive shell. `eslint .` reads this file and exits with a
 * status, which is the only behaviour a lint script is useful for.
 *
 * `eslint-config-next` ships native flat configs from 16, so its two entry
 * points are spread in directly. They used to come through `FlatCompat`,
 * which is the shape Next's own codemod produced while the package was still
 * eslintrc-only; on 16 that path throws "Converting circular structure to
 * JSON" before a single file is linted, because the legacy validator tries to
 * serialise a flat config whose plugins reference themselves.
 *
 * Safe on Next 15, which is what this repo is on: the package asks for
 * `eslint >= 9` and says nothing at all about the framework's version. And
 * `@eslint/eslintrc` is uninstalled with the wrapper, the wrapper having been
 * its only reason to be here.
 */
const config = [
  {
    ignores: [
      ".next/**",
      // The hosted-mode build scripts/test-signin.mjs makes for itself, which
      // is the same build output under a different name (see `distDir` in
      // next.config.ts). Without this, linting the repository lints a Next
      // build: 2,440 errors in generated chunks nobody wrote.
      ".next-signin/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by Prisma, and not ours to style.
      "prisma/generated/**",
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    rules: {
      /*
       * Project rules, each one earning its place rather than inherited wholesale.
       */

      // CLAUDE.md: "No `any` without a comment justifying it." The rule cannot
      // read comments, so it warns rather than errors — it is a prompt to
      // justify, not a block.
      "@typescript-eslint/no-explicit-any": "warn",

      // Unused code is usually a leftover from a refactor. `_`-prefixed names
      // are the escape hatch for a deliberately ignored argument.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      // Estonian text is full of apostrophes and quotes; React's own rule about
      // escaping them catches real rendering bugs, so it stays on.
      "react/no-unescaped-entities": "error",

      /*
       * THE REACT COMPILER'S RULES, WHICH ARRIVED TURNED UP RATHER THAN BEING
       * TURNED UP HERE.
       *
       * `eslint-config-next` 16 brings `eslint-plugin-react-hooks` 7 with it and
       * enables sixteen `react-hooks/*` rules as errors, eleven of which did not
       * exist in 15. Eleven hold in this tree already and stay errors, so none of
       * them can regress quietly. Five do not: 116 findings over about forty
       * files, listed here with their counts, because a warning nobody has
       * counted is a warning nobody reads.
       *
       *   purity              49  (46 are `Date.now()` read during render)
       *   set-state-in-effect 34
       *   refs                25
       *   static-components    7
       *   immutability         1
       *
       * These are a backlog rather than a bar being lowered, and the difference
       * is worth being exact about, because `.github/workflows/ci.yml` says of
       * its own audit gate: do not lower a number. That rule is about a gate this
       * code used to pass and would stop passing. Nothing here used to pass. The
       * rules are a new opinion arriving with a new major, and much of what they
       * object to is deliberate: `lib/layout/navMarker.ts` writes a ref during
       * render on purpose and CLAUDE.md argues it at length, and a page deciding
       * what is due now reads the clock.
       *
       * So they warn, which is the shape `no-explicit-any` two rules up already
       * takes and for the reason written there: a prompt to justify rather than a
       * block. Each goes back to "error" as it empties, and the table is what
       * says how far that has got. What may not happen is this block growing a
       * rule that was never measured, or a count here drifting from what
       * `npm run lint` prints.
       */
      "react-hooks/purity": "warn",
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/static-components": "warn",
      "react-hooks/immutability": "warn",
    },
  },

  {
    // The browser test scripts are Node programs, not app code: they use
    // top-level await, console output and Playwright's own globals.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { console: "readonly", process: "readonly", Buffer: "readonly", URL: "readonly" },
    },
  },

  {
    // The service worker runs in a worker scope, where `self`, `caches` and
    // `Response` are the globals and there is no DOM.
    files: ["public/sw.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        self: "readonly",
        caches: "readonly",
        fetch: "readonly",
        Response: "readonly",
        URL: "readonly",
      },
    },
  },
];

export default config;
