import { fixupConfigRules } from "@eslint/compat";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * ESLint, on the flat config the CLI actually uses.
 *
 * `next lint` is deprecated in Next 15 and gone in 16; worse, with no config on
 * disk it drops into an interactive setup prompt, so `npm run lint` hung in CI
 * and in any non-interactive shell. `eslint .` reads this file and exits with a
 * status, which is the only behaviour a lint script is useful for.
 *
 * `eslint-config-next` ships native flat configs from 16, so its two entry
 * points are spread in directly. They used to come through `FlatCompat`,
 * which is the shape Next's own codemod produced while the package was still
 * eslintrc-only; on 16 that path throws "Converting circular structure to
 * JSON" before a single file is linted, because the legacy validator tries to
 * serialise a flat config whose plugins reference themselves.
 *
 * Safe on Next 15, which is what this repo is on: the package asks for
 * `eslint >= 9` and says nothing at all about the framework's version. And
 * `@eslint/eslintrc` is uninstalled with the wrapper, the wrapper having been
 * its only reason to be here.
 *
 * Both presets go through `fixupConfigRules` because ESLint 10 removed the
 * `context.getFilename()` family that ESLint 9 had only deprecated, and three
 * of the plugins `eslint-config-next` 16.3 pins still call it: `eslint-plugin-react`
 * 7.37, `eslint-plugin-jsx-a11y` 6.10 and `eslint-plugin-import` 2.32, none of
 * which has a release declaring ESLint 10. Without the wrap `eslint .` dies
 * loading `react/display-name` on the first file, before one line is linted,
 * and `prebuild` takes the build down with it. `@eslint/compat` is ESLint's own
 * shim for exactly this: it hands each rule a context carrying the old methods
 * and changes nothing about what the rules report. Measured on this tree: the
 * same 123 warnings and 0 errors, rule for rule, as before the bump. The wrap
 * can come off when `eslint-config-next` ships plugins that support 10.
 */
const config = [
  {
    ignores: [
      ".next/**",
      // The hosted-mode build scripts/test-signin.mjs makes for itself, which
      // is the same build output under a different name (see `distDir` in
      // next.config.ts). Without this, linting the repository lints a Next
      // build: 2,440 errors in generated chunks nobody wrote.
      ".next-signin/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by Prisma, and not ours to style.
      "prisma/generated/**",
    ],
  },

  ...fixupConfigRules(nextCoreWebVitals),
  ...fixupConfigRules(nextTypescript),

  {
    rules: {
      /*
       * Project rules, each one earning its place rather than inherited wholesale.
       */

      // CLAUDE.md: "No `any` without a comment justifying it." The rule cannot
      // read comments, so it warns rather than errors — it is a prompt to
      // justify, not a block.
      "@typescript-eslint/no-explicit-any": "warn",

      // Unused code is usually a leftover from a refactor. `_`-prefixed names
      // are the escape hatch for a deliberately ignored argument.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],

      // Estonian text is full of apostrophes and quotes; React's own rule about
      // escaping them catches real rendering bugs, so it stays on.
      "react/no-unescaped-entities": "error",

      /*
       * THE REACT COMPILER'S RULES, AND WHY THREE OF THEM ARE OFF.
       *
       * `eslint-config-next` 16 brings `eslint-plugin-react-hooks` 7, which
       * enables sixteen `react-hooks/*` rules as errors. Thirteen hold in this
       * tree and stay errors, including `static-components` and `immutability`,
       * whose findings were real and were fixed rather than tolerated: eight
       * `<Icon />`s chosen during render now go through `NamedIcon`, and three
       * callbacks that read a variable declared after them no longer do.
       *
       * Three are off, and they are off rather than warning, because a warning
       * nobody acts on is 106 lines of noise in every lint run, which is how a
       * real warning beside them goes unread. Each exists to keep a component
       * compilable by the React Compiler, which this app does not run
       * (`next.config.ts` sets no `reactCompiler`), and what each objects to
       * here is deliberate:
       *
       *   purity              `Date.now()` read during render: a page deciding
       *                       what is due now reads the clock, and a round
       *                       stamps when a card was shown.
       *   refs                a ref read or written during render, which is
       *                       what `lib/layout/navMarker.ts` does on purpose
       *                       and what CLAUDE.md argues at length.
       *   set-state-in-effect state reset in an effect when a question
       *                       changes, the shape every round's reset takes.
       *
       * If the compiler is ever switched on, these come back on first, and the
       * findings are the list of what it cannot optimise. Until then, lint runs
       * with `--max-warnings 0`, so anything that does warn is a failure rather
       * than a line in a list.
       */
      "react-hooks/purity": "off",
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },

  {
    // The browser test scripts are Node programs, not app code: they use
    // top-level await, console output and Playwright's own globals.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { console: "readonly", process: "readonly", Buffer: "readonly", URL: "readonly" },
    },
  },

  {
    // The service worker runs in a worker scope, where `self`, `caches` and
    // `Response` are the globals and there is no DOM.
    files: ["public/sw.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        self: "readonly",
        caches: "readonly",
        fetch: "readonly",
        Response: "readonly",
        URL: "readonly",
      },
    },
  },
];

export default config;
