/**
 * A NATIVE SPEAKER'S SENTENCE FOR A SCENE. Generated by
 * `npm run scenes:import`. Do not edit by hand: re-run the importer.
 *
 * WHY THIS FILE IS A REQUEST AND NOT A DICTIONARY. `lib/collections/scenes.ts`
 * sets sixty situations and this is where one Estonian sentence per situation
 * goes. Every character in it was typed by a person into a spreadsheet, which
 * is the same standard the suggestion queue meets and exactly what ADR-005
 * requires: a model may not write a sentence a learner is invited to copy, and
 * no model can reach this file.
 *
 * WHAT THE IMPORTER DOES BEFORE A SENTENCE MAY SHIP. Every Estonian word in it
 * goes through `matchEstonianForm`, at the confidence a photographed page has
 * to clear (ADR-021), so a typo cannot reach a learner. That is the same gate
 * the scanner and the news headlines pass: an outside source proposes and the
 * dictionary decides, and this is the fourth door onto the one rule.
 *
 * EMPTY IS A CORRECT STATE. The mode is complete without a single row here:
 * `lib/progress/describe.ts` falls back to an attested Ekilex usage carrying
 * the form the task asked for, which is a real Estonian sentence a
 * lexicographer wrote down. What a contributed sentence adds is the thing the
 * dictionary structurally cannot have, a sentence about a *situation* rather
 * than about a word. So this starts empty and gets better, rather than the
 * feature waiting on it.
 */

export interface SceneAnswer {
  /** One sentence, as the contributor wrote it. Never edited by this app. */
  readonly et: string;
  /** How the contributor is credited, or an empty string where they declined. */
  readonly by: string;
}

/** Keyed on `Scene.id`. See `docs/20-contributed-sentences.md`. */
export const SCENE_ANSWERS: Readonly<Record<string, SceneAnswer>> = {};

export function sceneAnswerFor(sceneId: string): SceneAnswer | undefined {
  return SCENE_ANSWERS[sceneId];
}

