/**
 * A2 — from getting by to holding your end of a conversation.
 *
 * The level's real work is the past tense and the full locative system. A1 can
 * be survived with the present and two cases; A2 is where Estonian stops being
 * a phrasebook, so the grammar units (minevik, korraldused, vordlemine) sit
 * between the vocabulary ones rather than after them.
 */
import { unit } from "./types";

export const A2 = [
  unit({
    id: "minevik",
    title: "Minevik",
    subtitle: "Talking about yesterday",
    icon: "History",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Tell someone what you did yesterday, last week and last year.",
    blurb: "The simple past, built on the second infinitive with -si- after it, plus the handful of everyday verbs that do it their own way.",
    grammar: ["imperfect", "past-participle"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["iga-paev"],
    words: [
      ["juhtuma", "to happen"],
      ["alustama", "to begin (something)"],
      ["algama", "to begin (of itself)"],
      ["lõpetama", "to finish"],
      ["lõppema", "to come to an end"],
      ["ootama", "to wait"],
      ["unustama", "to forget"],
      ["mäletama", "to remember"],
      ["juhtima", "to lead, to drive"],
      ["kohtuma", "to meet"],
      ["sündima", "to be born"],
      ["surema", "to die"],
      ["kasvama", "to grow"],
      ["muutuma", "to change (of itself)"],
      ["muutma", "to change (something)"],
    ],
  }),

  unit({
    id: "loodus",
    title: "Loodus",
    subtitle: "Nature and animals",
    icon: "Trees",
    level: "A2",
    module: "Ümbrus",
    canDo: "Describe a landscape and talk about animals and the seasons.",
    blurb: "Forest, sea and weather, half of Estonian small talk, and a pile of gradation.",
    grammar: ["gradation", "inessive", "elative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ilm"],
    words: [
      ["loodus", "nature"],
      ["mets", "forest"],
      ["meri", "sea"],
      ["järv", "lake"],
      ["jõgi", "river"],
      ["mägi", "hill, mountain"],
      ["maa", "land, country"],
      ["puu", "tree"],
      ["lill", "flower"],
      ["rohi", "grass"],
      ["loom", "animal"],
      ["koer", "dog"],
      ["kass", "cat"],
      ["lind", "bird"],
      ["hobune", "horse"],
      ["kevad", "spring"],
      ["suvi", "summer"],
      ["sügis", "autumn"],
      ["talv", "winter"],
    ],
  }),

  unit({
    id: "keha-ja-tervis",
    title: "Keha ja tervis",
    subtitle: "Body and health",
    icon: "HeartPulse",
    level: "A2",
    module: "Ümbrus",
    canDo: "Describe a symptom to a doctor and understand the advice you are given.",
    blurb: "For the appointment you would rather not improvise. käsi : käe is worth the trip alone.",
    grammar: ["gradation", "adessive", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["loodus"],
    words: [
      ["keha", "body"],
      ["käsi", "hand, arm"],
      ["jalg", "leg, foot"],
      ["silm", "eye"],
      ["kõrv", "ear"],
      ["suu", "mouth"],
      ["nina", "nose"],
      ["pea", "head"],
      ["süda", "heart"],
      ["selg", "back"],
      ["tervis", "health"],
      ["haigus", "illness"],
      ["valu", "pain"],
      ["ravim", "medicine"],
      ["palavik", "fever"],
      ["haige", "ill, sick", "ADJECTIVE"],
      ["terve", "healthy, whole", "ADJECTIVE"],
      ["väsinud", "tired", "ADJECTIVE"],
      ["valutama", "to hurt, to ache"],
      ["tablett", "tablet"],
    ],
  }),

  unit({
    id: "kool-ja-keel",
    title: "Kool ja keel",
    subtitle: "School and language",
    icon: "GraduationCap",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Talk about studying, ask what a word means, and describe your language level.",
    blurb: "The words your Estonian class uses about Estonian class.",
    grammar: ["partitive", "translative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kus-ja-kuhu"],
    words: [
      ["sõna", "word"],
      ["keel", "language, tongue"],
      ["lause", "sentence"],
      ["küsimus", "question"],
      ["vastus", "answer"],
      ["tund", "lesson, hour"],
      ["õppimine", "learning"],
      ["harjutus", "exercise"],
      ["viga", "mistake"],
      ["näide", "example"],
      ["raamatukogu", "library"],
      ["ajaleht", "newspaper"],
      ["uudis", "news item"],
      ["lugu", "story"],
      ["õpetama", "to teach"],
      ["seletama", "to explain"],
      ["kordama", "to repeat"],
      ["tõlkima", "to translate"],
    ],
  }),

  unit({
    id: "reisimine",
    title: "Reisimine",
    subtitle: "Travel and time off",
    icon: "Plane",
    level: "A2",
    module: "Ümbrus",
    canDo: "Book a trip, check in, and describe a journey you have made.",
    blurb: "Going somewhere: the sisseütlev and alaleütlev earn their keep here (Tallinnasse, rongile).",
    grammar: ["illative", "allative", "ablative", "terminative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kus-ja-kuhu"],
    words: [
      ["reis", "trip, journey"],
      ["puhkus", "holiday, leave"],
      ["riik", "country, state"],
      ["piir", "border"],
      ["lennuk", "airplane"],
      ["laev", "ship"],
      ["jalgratas", "bicycle"],
      ["kaart", "map, card"],
      ["kohver", "suitcase"],
      ["sõitma", "to travel, to ride"],
      ["lendama", "to fly"],
      ["kõndima", "to walk"],
      ["jooksma", "to run"],
      ["otsima", "to look for"],
      ["leidma", "to find"],
      ["jõudma", "to arrive, to manage"],
      ["broneerima", "to book"],
    ],
  }),

  unit({
    id: "kodutood",
    title: "Kodutööd",
    subtitle: "Housework and routine",
    icon: "Broom",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Describe your routine at home and divide up chores with someone.",
    blurb: "Verbs you use every single day, and almost none of them appear in a textbook's first chapter.",
    grammar: ["present-tense", "object"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["minevik"],
    words: [
      ["koristama", "to tidy, to clean"],
      ["pesema", "to wash"],
      ["küpsetama", "to bake"],
      ["keetma", "to boil, to cook"],
      ["praadima", "to fry"],
      ["lõikama", "to cut"],
      ["parandama", "to repair, to correct"],
      ["ehitama", "to build"],
      ["kandma", "to carry, to wear"],
      ["hoidma", "to hold, to keep"],
      ["avama", "to open"],
      ["sulgema", "to close"],
      ["katma", "to cover, to lay (a table)"],
      ["riidekapp", "wardrobe"],
      ["nõu", "dish, advice"],
      ["prügi", "rubbish"],
      ["katki", "broken", "ADVERB"],
    ],
  }),

  unit({
    id: "linn-ja-teenused",
    title: "Linn ja teenused",
    subtitle: "Town and services",
    icon: "Building2",
    level: "A2",
    module: "Ümbrus",
    canDo: "Deal with a bank, a post office and an official form without switching to English.",
    blurb: "The errands that make you feel like a resident rather than a visitor.",
    grammar: ["allative", "ablative", "genitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ostmine"],
    words: [
      ["pank", "bank"],
      ["post", "post, mail"],
      ["amet", "office, profession"],
      ["arve", "bill, invoice"],
      ["konto", "account"],
      ["kaup", "goods"],
      ["klient", "client, customer"],
      ["teenus", "service"],
      ["järjekord", "queue, order"],
      ["dokument", "document"],
      ["allkiri", "signature"],
      ["avaldus", "application (a form you submit)"],
      ["luba", "permit, permission"],
      ["täitma", "to fill in, to fulfill"],
      ["saatma", "to send"],
      ["tellima", "to order"],
      ["esitama", "to submit, to hand in"],
    ],
  }),

  unit({
    id: "suhtlemine",
    title: "Suhtlemine",
    subtitle: "Phone, mail and the internet",
    icon: "MessageCircle",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Make a phone call, write a short message and arrange to meet.",
    blurb: "Where the alaleütlev and the verb government of helistama trip up every English speaker.",
    grammar: ["government", "allative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "GOVERNMENT", "CLOZE"],
    requires: ["kool-ja-keel"],
    words: [
      ["helistama", "to call, to phone"],
      ["vastama", "to answer"],
      ["kirjutama", "to write"],
      ["saabuma", "to arrive"],
      ["teatama", "to announce, to inform"],
      ["kutsuma", "to invite, to call"],
      ["kohtumine", "meeting (two people coming together)"],
      ["sõnum", "message"],
      ["kiri", "letter"],
      ["aadress", "address"],
      ["võrk", "network, net"],
      ["leht", "page, leaf"],
      ["parool", "password"],
      ["pilt", "picture"],
      ["heli", "sound"],
    ],
  }),

  unit({
    id: "vaba-aeg",
    title: "Vaba aeg",
    subtitle: "Free time and sport",
    icon: "Bike",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Say what you do for fun, suggest an activity and accept or refuse one.",
    blurb: "What you actually talk about with someone you have just met.",
    grammar: ["partitive", "infinitives"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kodutood"],
    words: [
      ["sport", "sport"],
      ["mäng", "game"],
      ["muusika", "music"],
      ["laul", "song"],
      ["tants", "dance"],
      ["film", "film"],
      ["teater", "theater"],
      ["näitus", "exhibition"],
      ["pidu", "party"],
      ["reegel", "rule"],
      ["võistlus", "competition (a contest)"],
      ["mängima", "to play"],
      ["laulma", "to sing"],
      ["tantsima", "to dance"],
      ["ujuma", "to swim"],
      ["sõitma", "to ride"],
      ["võitma", "to win"],
      ["kaotama", "to lose"],
    ],
  }),

  unit({
    id: "restoranis",
    title: "Restoranis",
    subtitle: "Eating out",
    icon: "ChefHat",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Read a menu, order a full meal and ask what a dish contains.",
    blurb: "The osastav at its most useful: you order some of a thing, not the whole thing.",
    grammar: ["partitive", "object", "conditional"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["sook-ja-jook"],
    words: [
      ["menüü", "menu"],
      ["roog", "dish, course"],
      ["eelroog", "starter"],
      ["magustoit", "dessert"],
      ["kaste", "sauce", "NOUN", 178715],
      ["salat", "salad"],
      ["köögivili", "vegetable"],
      ["puuvili", "fruit"],
      ["mari", "berry"],
      ["seen", "mushroom"],
      ["maitse", "taste, flavor"],
      ["portsjon", "portion"],
      ["arve", "bill"],
      ["tellima", "to order"],
      ["soovitama", "to recommend"],
      ["maitsma", "to taste"],
    ],
  }),

  unit({
    id: "korraldused",
    title: "Korraldused ja palved",
    subtitle: "Asking, telling and offering",
    icon: "Megaphone",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Give an instruction, make a polite request and offer to help.",
    blurb: "The imperative, and the conditional that turns an order into a request.",
    grammar: ["imperative", "conditional", "politeness"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["minevik"],
    words: [
      ["aitama", "to help"],
      ["lubama", "to allow, to promise"],
      ["keelama", "to forbid"],
      ["paluma", "to request, to beg"],
      ["soovima", "to wish"],
      ["käskima", "to order, to command"],
      ["proovima", "to try"],
      ["jätkama", "to continue"],
      ["peatuma", "to stop (of itself)"],
      ["peatama", "to stop (something)"],
      ["takistama", "to hinder"],
      ["vabandama", "to apologize"],
      ["tänama", "to thank"],
      ["tervitama", "to greet"],
      // "Kas ma tohin?" is the polite ask this unit is about.
      ["tohtima", "to be allowed to"],
    ],
  }),

  unit({
    id: "vordlemine",
    title: "Võrdlemine",
    subtitle: "Comparing things",
    icon: "Scale",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Compare two things and say which is best.",
    blurb: "Comparatives and superlatives, plus the adjectives worth comparing.",
    grammar: ["comparative", "superlative", "adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["omadussonad"],
    words: [
      ["tugev", "strong", "ADJECTIVE"],
      ["nõrk", "weak", "ADJECTIVE"],
      ["lai", "wide", "ADJECTIVE"],
      ["kitsas", "narrow", "ADJECTIVE"],
      ["sügav", "deep", "ADJECTIVE"],
      ["madal", "low, shallow", "ADJECTIVE"],
      ["kõrge", "high", "ADJECTIVE"],
      ["paks", "thick, fat", "ADJECTIVE"],
      ["õhuke", "thin", "ADJECTIVE"],
      ["puhas", "clean", "ADJECTIVE"],
      ["määrdunud", "dirty", "ADJECTIVE"],
      ["täis", "full", "ADJECTIVE"],
      ["tühi", "empty", "ADJECTIVE"],
      ["sarnane", "similar", "ADJECTIVE"],
      ["erinev", "different", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "tunded",
    title: "Tunded",
    subtitle: "Feelings",
    icon: "Heart",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Say how you feel and ask someone else how they are, and mean it.",
    blurb: "Estonian puts feelings in cases English puts in verbs: mul on hea meel.",
    grammar: ["adessive", "government"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["keha-ja-tervis"],
    words: [
      ["rõõm", "joy"],
      ["mure", "worry"],
      ["hirm", "fear"],
      ["viha", "anger"],
      ["armastus", "love"],
      ["meel", "mind, mood"],
      ["tunne", "feeling"],
      ["õnn", "luck, happiness"],
      ["rahu", "peace, calm"],
      ["rõõmus", "cheerful", "ADJECTIVE"],
      ["kurb", "sad", "ADJECTIVE"],
      ["vihane", "angry", "ADJECTIVE"],
      ["murelik", "worried", "ADJECTIVE"],
      ["rahulik", "calm", "ADJECTIVE"],
      ["üllatunud", "surprised", "ADJECTIVE"],
      ["tunduma", "to seem"],
    ],
  }),

  unit({
    id: "plaanid",
    title: "Plaanid",
    subtitle: "Plans and the future",
    icon: "CalendarCheck",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Make arrangements, talk about your plans and say what you intend to do.",
    blurb: "Estonian has no future tense. This unit is how it manages without one.",
    grammar: ["future", "infinitives", "time-expressions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["korraldused"],
    words: [
      ["plaan", "plan"],
      ["kavatsus", "intention"],
      ["eesmärk", "goal"],
      ["võimalus", "possibility, opportunity"],
      ["otsus", "decision"],
      ["kavatsema", "to intend"],
      ["planeerima", "to plan"],
      ["otsustama", "to decide"],
      ["valima", "to choose, to elect"],
      ["lootma", "to hope"],
      ["kartma", "to fear"],
      ["uskuma", "to believe"],
      ["arvama", "to think, to reckon"],
      ["nõustuma", "to agree"],
      ["nõus", "in agreement (ma olen nõus: I agree)", "ADVERB"],
      ["sobima", "to suit, to be convenient"],
      ["kestma", "to last, to go on"],
    ],
  }),
] as const;
