/**
 * A2 — from getting by to holding your end of a conversation.
 *
 * The level's real work is the past tense and the full locative system. A1 can
 * be survived with the present and two cases; A2 is where Estonian stops being
 * a phrasebook, so the grammar units (minevik, korraldused, vordlemine) sit
 * between the vocabulary ones rather than after them.
 */
import { unit } from "./types";

export const A2 = [
  unit({
    id: "minevik",
    title: "Minevik",
    subtitle: "Talking about yesterday",
    icon: "History",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Tell someone what you did yesterday, last week and last year.",
    blurb: "The simple past, built on the second infinitive with -si- after it, plus the handful of everyday verbs that do it their own way.",
    grammar: ["imperfect", "past-participle"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["iga-paev"],
    words: [
      ["juhtuma", "to happen"],
      ["alustama", "to begin (something)"],
      ["algama", "to begin (of itself)"],
      ["lõpetama", "to finish"],
      ["lõppema", "to come to an end"],
      ["ootama", "to wait"],
      ["unustama", "to forget"],
      ["mäletama", "to remember"],
      ["juhtima", "to lead, to drive"],
      ["kohtuma", "to meet"],
      ["sündima", "to be born"],
      ["surema", "to die"],
      ["kasvama", "to grow"],
      ["muutuma", "to change (of itself)"],
      ["muutma", "to change (something)"],
    ],
  }),

  unit({
    id: "loodus",
    title: "Loodus",
    subtitle: "Nature and animals",
    icon: "Trees",
    level: "A2",
    module: "Ümbrus",
    canDo: "Describe a landscape and talk about animals and the seasons.",
    blurb: "Forest, sea and weather, half of Estonian small talk, and a pile of gradation.",
    grammar: ["genitive", "gradation", "inessive", "elative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ilm"],
    words: [
      ["loodus", "nature"],
      ["mets", "forest"],
      ["meri", "sea"],
      ["järv", "lake"],
      ["jõgi", "river"],
      ["mägi", "hill, mountain"],
      ["maa", "land, country"],
      ["puu", "tree"],
      ["lill", "flower"],
      ["rohi", "grass"],
      ["loom", "animal", "NOUN", 196387],
      ["koer", "dog"],
      ["kass", "cat"],
      ["lind", "bird"],
      ["hobune", "horse"],
      ["kevad", "spring"],
      ["suvi", "summer"],
      ["sügis", "autumn"],
      ["talv", "winter"],
      ["taevas", "sky"],
      ["õhk", "air"],
      ["kivi", "stone"],
      ["taim", "plant"],
      ["karu", "bear"],
    ],
  }),

  unit({
    id: "keha-ja-tervis",
    title: "Keha ja tervis",
    subtitle: "Body and health",
    icon: "HeartPulse",
    level: "A2",
    module: "Ümbrus",
    canDo: "Describe a symptom to a doctor and understand the advice you are given.",
    blurb: "For the appointment you would rather not improvise. käsi : käe is worth the trip alone.",
    grammar: ["partitive", "adessive", "gradation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["loodus"],
    words: [
      ["keha", "body"],
      ["käsi", "hand, arm"],
      ["jalg", "leg, foot"],
      ["silm", "eye", "NOUN", 233583],
      ["kõrv", "ear"],
      ["suu", "mouth", "NOUN", 237825],
      ["nina", "nose"],
      ["pea", "head", "NOUN", 214506],
      ["süda", "heart"],
      ["selg", "back"],
      ["tervis", "health"],
      ["haigus", "illness"],
      ["valu", "pain", "NOUN", 253685],
      ["ravim", "medicine"],
      ["palavik", "fever"],
      ["haige", "ill, sick", "ADJECTIVE"],
      ["terve", "healthy, whole", "ADJECTIVE"],
      ["väsinud", "tired", "ADJECTIVE"],
      ["valutama", "to hurt, to ache"],
      ["tablett", "tablet"],
      ["nägu", "face"],
      ["hammas", "tooth"],
      ["kõht", "stomach, belly"],
      ["kael", "neck"],
    ],
  }),

  unit({
    id: "kool-ja-keel",
    title: "Kool ja keel",
    subtitle: "School and language",
    icon: "GraduationCap",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Talk about studying, ask what a word means, and describe your language level.",
    blurb: "The words your Estonian class uses about Estonian class.",
    grammar: ["partitive", "translative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kus-ja-kuhu"],
    words: [
      ["sõna", "word"],
      ["keel", "language, tongue"],
      ["lause", "sentence"],
      ["küsimus", "question"],
      ["vastus", "answer"],
      ["tund", "lesson, hour"],
      ["õppimine", "learning"],
      ["harjutus", "exercise"],
      ["viga", "mistake"],
      ["näide", "example"],
      ["raamatukogu", "library"],
      ["ajaleht", "newspaper"],
      ["uudis", "news item"],
      ["lugu", "story"],
      ["õpetama", "to teach"],
      ["seletama", "to explain"],
      ["kordama", "to repeat"],
      ["tõlkima", "to translate"],
      ["klass", "class"],
      ["teema", "topic", "NOUN"],
      ["paber", "paper"],
    ],
  }),

  unit({
    id: "reisimine",
    title: "Reisimine",
    subtitle: "Travel and time off",
    icon: "Plane",
    level: "A2",
    module: "Ümbrus",
    canDo: "Book a trip, check in, and describe a journey you have made.",
    blurb: "Going somewhere: the sisseütlev and alaleütlev earn their keep here (Tallinnasse, rongile).",
    grammar: ["illative", "allative", "ablative", "terminative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kus-ja-kuhu"],
    words: [
      ["reis", "trip, journey", "NOUN", 226782],
      ["puhkus", "holiday, leave"],
      ["riik", "country, state"],
      ["piir", "border"],
      ["lennuk", "airplane"],
      ["laev", "ship"],
      ["jalgratas", "bicycle"],
      ["kaart", "map, card"],
      ["kohver", "suitcase"],
      ["sõitma", "to travel, to ride"],
      ["lendama", "to fly"],
      ["kõndima", "to walk"],
      ["jooksma", "to run"],
      ["otsima", "to look for"],
      ["leidma", "to find"],
      ["jõudma", "to arrive, to manage"],
      ["broneerima", "to book"],
      ["põhi", "north"],
      ["lõuna", "south"],
      ["ida", "east"],
      ["lääs", "west"],
      ["saar", "island"],
      ["välismaa", "abroad, foreign country"],
      ["kaugus", "distance"],
    ],
  }),

  unit({
    id: "kodutood",
    title: "Kodutööd",
    subtitle: "Housework and routine",
    icon: "Broom",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Describe your routine at home and divide up chores with someone.",
    blurb: "Verbs you use every single day, and almost none of them appear in a textbook's first chapter.",
    grammar: ["present-tense", "imperative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["minevik"],
    words: [
      ["koristama", "to tidy, to clean"],
      ["pesema", "to wash"],
      ["küpsetama", "to bake"],
      ["keetma", "to boil, to cook"],
      ["praadima", "to fry"],
      ["lõikama", "to cut"],
      ["parandama", "to repair, to correct"],
      ["ehitama", "to build"],
      ["kandma", "to carry, to wear"],
      ["hoidma", "to hold, to keep"],
      ["avama", "to open"],
      ["sulgema", "to close"],
      ["katma", "to cover, to lay (a table)"],
      ["riidekapp", "wardrobe"],
      ["nõu", "dish, advice", "NOUN", 209724],
      ["prügi", "rubbish"],
      ["katki", "broken", "ADVERB"],
    ],
  }),

  unit({
    id: "linn-ja-teenused",
    title: "Linn ja teenused",
    subtitle: "Town and services",
    icon: "Building2",
    level: "A2",
    module: "Ümbrus",
    canDo: "Deal with a bank, a post office and an official form without switching to English.",
    blurb: "The errands that make you feel like a resident rather than a visitor.",
    grammar: ["allative", "ablative", "genitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ostmine"],
    words: [
      ["pank", "bank", "NOUN", 213548],
      ["post", "post, mail", "NOUN", 219321],
      ["amet", "office, profession"],
      ["arve", "bill, invoice"],
      ["konto", "account"],
      ["kaup", "goods"],
      ["klient", "client, customer"],
      ["teenus", "service"],
      ["järjekord", "queue, order"],
      ["dokument", "document"],
      ["allkiri", "signature"],
      ["avaldus", "application (a form you submit)"],
      ["luba", "permit, permission", "NOUN", 196723],
      ["täitma", "to fill in, to fulfill"],
      ["saatma", "to send"],
      ["tellima", "to order", "VERB", 243828],
      ["esitama", "to submit, to hand in"],
      ["küla", "village"],
      ["hoone", "building"],
      ["taotlus", "application"],
      ["kohalik", "local", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "suhtlemine",
    title: "Suhtlemine",
    subtitle: "Phone, mail and the internet",
    icon: "MessageCircle",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Make a phone call, write a short message and arrange to meet.",
    blurb: "Where the alaleütlev and the verb government of helistama trip up every English speaker.",
    grammar: ["government", "allative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "GOVERNMENT", "CLOZE"],
    requires: ["kool-ja-keel"],
    words: [
      ["helistama", "to call, to phone"],
      ["vastama", "to answer"],
      ["kirjutama", "to write"],
      ["saabuma", "to arrive"],
      ["teatama", "to announce, to inform"],
      ["kutsuma", "to invite, to call"],
      ["kohtumine", "meeting (two people coming together)"],
      ["sõnum", "message"],
      ["kiri", "letter"],
      ["aadress", "address"],
      ["võrk", "network, net"],
      ["leht", "page, leaf"],
      ["parool", "password"],
      ["pilt", "picture"],
      ["heli", "sound"],
      ["kohtama", "to meet, to come across"],
    ],
  }),

  unit({
    id: "vaba-aeg",
    title: "Vaba aeg",
    subtitle: "Free time and sport",
    icon: "Bike",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Say what you do for fun, suggest an activity and accept or refuse one.",
    blurb: "What you actually talk about with someone you have just met.",
    grammar: ["partitive", "infinitives"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kodutood"],
    words: [
      ["sport", "sport"],
      ["mäng", "game"],
      ["muusika", "music"],
      ["laul", "song"],
      ["tants", "dance"],
      ["film", "film"],
      ["teater", "theater"],
      ["näitus", "exhibition"],
      ["pidu", "party"],
      ["reegel", "rule"],
      ["võistlus", "competition (a contest)"],
      ["mängima", "to play"],
      ["laulma", "to sing"],
      ["tantsima", "to dance"],
      ["ujuma", "to swim"],
      ["sõitma", "to ride"],
      ["võitma", "to win"],
      ["kaotama", "to lose"],
      ["koguma", "to collect, to gather"],
      ["kino", "cinema"],
      ["kontsert", "concert"],
      ["pall", "ball"],
      ["foto", "photo"],
      ["saun", "sauna"],
    ],
  }),

  unit({
    id: "restoranis",
    title: "Restoranis",
    subtitle: "Eating out",
    icon: "ChefHat",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Read a menu, order a full meal and ask what a dish contains.",
    blurb: "The osastav at its most useful: you order some of a thing, not the whole thing.",
    /*
      The numerals page is read here rather than at A1, where the numbers are
      taught as words: its whole point is that the counted noun is partitive
      singular, which is a page about an ending, and this is the first unit
      after the partitive where somebody is counting things, portions and
      prices, with a bill at the end of it.
    */
    grammar: ["partitive", "numerals", "conditional"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["sook-ja-jook"],
    words: [
      ["menüü", "menu"],
      ["roog", "dish, course", "NOUN", 228711],
      ["eelroog", "starter"],
      ["magustoit", "dessert"],
      ["kaste", "sauce", "NOUN", 178715],
      ["salat", "salad"],
      ["köögivili", "vegetable"],
      ["puuvili", "fruit"],
      ["mari", "berry", "NOUN", 200639],
      ["seen", "mushroom"],
      ["maitse", "taste, flavor"],
      ["portsjon", "portion"],
      ["arve", "bill"],
      ["tellima", "to order", "VERB", 243828],
      ["soovitama", "to recommend"],
      ["maitsma", "to taste"],
      ["kana", "chicken"],
      ["pudel", "bottle"],
      ["hommikusöök", "breakfast"],
      ["lõunasöök", "lunch"],
      ["õhtusöök", "dinner"],
    ],
  }),

  unit({
    id: "korraldused",
    title: "Korraldused ja palved",
    subtitle: "Asking, telling and offering",
    icon: "Megaphone",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Give an instruction, make a polite request and offer to help.",
    blurb: "The imperative, and the conditional that turns an order into a request.",
    grammar: ["imperative", "conditional", "politeness"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["iga-paev"],
    words: [
      ["aitama", "to help"],
      ["lubama", "to allow, to promise"],
      ["keelama", "to forbid"],
      ["paluma", "to request, to beg"],
      ["soovima", "to wish"],
      ["käskima", "to order, to command"],
      ["proovima", "to try"],
      ["jätkama", "to continue"],
      ["peatuma", "to stop (of itself)"],
      ["peatama", "to stop (something)"],
      ["takistama", "to hinder"],
      ["vabandama", "to apologize"],
      ["tänama", "to thank"],
      ["tervitama", "to greet"],
      // "Kas ma tohin?" is the polite ask this unit is about.
      ["tohtima", "to be allowed to"],
      ["suutma", "to manage to, to be able to"],
      ["laskma", "to let, to have (something done)"],
      ["üritama", "to try, to attempt"],
    ],
  }),

  unit({
    id: "vordlemine",
    title: "Võrdlemine",
    subtitle: "Comparing things",
    icon: "Scale",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Compare two things and say which is best.",
    blurb: "Comparatives and superlatives, plus the adjectives worth comparing.",
    grammar: ["comparative", "superlative", "adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["omadussonad"],
    words: [
      ["tugev", "strong", "ADJECTIVE"],
      ["nõrk", "weak", "ADJECTIVE"],
      ["lai", "wide", "ADJECTIVE"],
      ["kitsas", "narrow", "ADJECTIVE"],
      ["sügav", "deep", "ADJECTIVE"],
      ["madal", "low, shallow", "ADJECTIVE"],
      ["kõrge", "high", "ADJECTIVE"],
      ["paks", "thick, fat", "ADJECTIVE"],
      ["õhuke", "thin", "ADJECTIVE"],
      ["puhas", "clean", "ADJECTIVE"],
      ["määrdunud", "dirty", "ADJECTIVE"],
      ["täis", "full", "ADVERB", 249536],
      ["tühi", "empty", "ADJECTIVE"],
      ["sarnane", "similar", "ADJECTIVE"],
      ["erinev", "different", "ADJECTIVE"],
      ["parem", "better", "ADJECTIVE", 213895],
      ["halvem", "worse", "ADJECTIVE"],
      ["rikas", "rich", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "tunded",
    title: "Tunded",
    subtitle: "Feelings",
    icon: "Heart",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Say how you feel and ask someone else how they are, and mean it.",
    blurb: "Estonian puts feelings in cases English puts in verbs: mul on hea meel.",
    grammar: ["adessive", "government"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["keha-ja-tervis"],
    words: [
      ["rõõm", "joy"],
      ["mure", "worry", "NOUN", 204593],
      ["hirm", "fear", "NOUN", 169573],
      ["viha", "anger"],
      ["armastus", "love"],
      ["meel", "mind, mood"],
      ["tunne", "feeling"],
      ["õnn", "luck, happiness"],
      ["rahu", "peace, calm", "NOUN", 225099],
      ["rõõmus", "cheerful", "ADJECTIVE"],
      ["kurb", "sad", "ADJECTIVE"],
      ["vihane", "angry", "ADJECTIVE"],
      ["murelik", "worried", "ADJECTIVE"],
      ["rahulik", "calm", "ADJECTIVE"],
      ["üllatunud", "surprised", "ADJECTIVE"],
      ["tunduma", "to seem"],
      ["muretsema", "to worry"],
      ["tuju", "mood"],
      ["hing", "soul"],
    ],
  }),

  unit({
    id: "plaanid",
    title: "Plaanid",
    subtitle: "Plans and the future",
    icon: "CalendarCheck",
    level: "A2",
    module: "Aeg ja lugu",
    canDo: "Make arrangements, talk about your plans and say what you intend to do.",
    blurb: "Estonian has no future tense. This unit is how it manages without one.",
    grammar: ["future", "infinitives", "time-expressions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["korraldused"],
    words: [
      ["plaan", "plan"],
      ["kavatsus", "intention"],
      ["eesmärk", "goal"],
      ["võimalus", "possibility, opportunity"],
      ["otsus", "decision"],
      ["kavatsema", "to intend"],
      ["planeerima", "to plan", "VERB", 217865],
      ["otsustama", "to decide"],
      ["valima", "to choose, to elect"],
      ["lootma", "to hope"],
      ["kartma", "to fear"],
      ["uskuma", "to believe"],
      ["arvama", "to think, to reckon"],
      ["nõustuma", "to agree"],
      ["nõus", "in agreement (ma olen nõus: I agree)", "ADVERB"],
      ["sobima", "to suit, to be convenient"],
      ["kestma", "to last, to go on"],
      ["plaanima", "to plan"],
      ["tegevus", "activity"],
      ["võit", "win, victory"],
    ],
  }),
  /*
    The degree words no unit teaches. `viisisonad` at A1 has the everyday half
    (`peaaegu`, `üsna`, `täiesti`, `veidi`, `pisut`, `vähemalt`, `kõvasti`);
    these are the ones that come once somebody has something to qualify: how
    much of it, whether it was enough, and the two that mean "more and more".
    Every one was asked of Ekilex and came back as an adverb, and the bands are
    Ekilex's own, A1 to B2. Appended to the end of the last A2 part, so no day
    id before it moves. Each is `ADVERB` for the reason the connectives are: an
    Estonian adverb does not inflect, and the label says which cards it takes.
  */
  unit({
    /*
      THE WORDS FOR SAYING WHAT SOMETHING WAS LIKE, AND WHAT YOU THOUGHT.

      Another handful off `lib/collections/frequency.ts` that no unit taught:
      `mõte`, `idee`, `maailm`, `jutt`, `kena`, `lõbus`, `imelik`. A learner
      at A2 tells somebody about their weekend, and these are the words that
      conversation is made of.
    */
    id: "kirjeldamine",
    title: "Kirjeldamine",
    subtitle: "Ideas, the world, and what something was like",
    icon: "MessageCircle",
    level: "A2",
    module: "Suhtlemine",
    canDo: "Say what you thought of something and describe it in a few words: nice, fun, strange, famous.",
    blurb: "The words a story about your weekend is made of.",
    grammar: ["adjective-agreement"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM"],
    requires: ["tunded"],
    words: [
      ["mõte", "thought, idea"],
      ["idee", "idea"],
      ["maailm", "world"],
      ["jutt", "talk, story"],
      ["tänu", "gratitude, thanks"],
      ["tähelepanu", "attention"],
      ["mingi", "some, some kind of", "PRONOUN"],
      ["kena", "nice, pretty", "ADJECTIVE"],
      ["armas", "dear, sweet", "ADJECTIVE"],
      ["lõbus", "fun", "ADJECTIVE"],
      ["imelik", "strange", "ADJECTIVE"],
      ["eriline", "special", "ADJECTIVE"],
      ["normaalne", "normal", "ADJECTIVE"],
      ["vaene", "poor", "ADJECTIVE"],
      ["kuulus", "famous", "ADJECTIVE"],
      ["pime", "dark (without light), blind", "ADJECTIVE"],
      ["ohutu", "safe", "ADJECTIVE"],
      ["tänulik", "grateful", "ADJECTIVE"],
      ["ettevaatlik", "careful", "ADJECTIVE"],
      ["uhke", "proud, splendid", "ADJECTIVE"],
      ["värske", "fresh"],
      ["vaikne", "quiet", "ADJECTIVE"],
      ["pehme", "soft", "ADJECTIVE"],
      ["magus", "sweet"],
    ],
  }),

  unit({
    id: "kuivord",
    title: "Kui väga",
    subtitle: "How much you mean it",
    icon: "Gauge",
    level: "A2",
    module: "Igapäevane suhtlus",
    canDo: "Say how much you mean something: partly, fully, enough, not at all, more and more.",
    blurb: "Small words that change how strongly a sentence says what it says.",
    grammar: ["word-order"],
    cardTypes: ["RECOGNITION", "PRODUCTION"],
    requires: ["maaramine"],
    words: [
      ["vähe", "not much, little", "ADVERB", 258910],
      ["vähem", "less", "ADVERB", 258929],
      ["piisavalt", "enough, sufficiently", "ADVERB"],
      ["osaliselt", "partly", "ADVERB"],
      ["täielikult", "fully, entirely", "ADVERB"],
      ["äärmiselt", "extremely", "ADVERB"],
      ["lausa", "downright, even", "ADVERB"],
      ["sugugi", "(not) at all", "ADVERB"],
      ["hoopis", "instead, altogether", "ADVERB"],
      ["ligi", "nearly (with a number)", "ADVERB"],
      ["üha", "more and more", "ADVERB"],
      ["aina", "all the time", "ADVERB"],
    ],
  }),
] as const;
