/**
 * B1 — from conversation to argument.
 *
 * This is where Estonian stops being learnable by pattern and starts needing
 * rules: the total-versus-partial object, verb government, the conditional, and
 * the participles that every compound tense is built from. The vocabulary units
 * exist to give those rules something to bite on, which is why each one names
 * the grammar it carries rather than being a themed word list with a test after.
 */
import { unit } from "./types";

export const B1 = [
  unit({
    id: "objekt",
    title: "Sihitis",
    subtitle: "The whole thing, or some of it",
    icon: "Target",
    level: "B1",
    module: "Grammatika süveneb",
    canDo: "Choose between the osastav and the omastav object and say why.",
    blurb: "The single hardest thing in Estonian grammar, and the one that marks out a B1 speaker.",
    grammar: ["object", "partitive", "genitive", "aspect"],
    // Verbs, so the form worth drilling is a person and not a case. It asked
    // for `CASE_FORM`, which needs a genitive stem: twelve words, no genitive
    // between them, and not one card built. The object rule itself is taught
    // on the grammar pages this unit links to and met in the gap-fill cards,
    // where the verb stands in a sentence somebody recorded.
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["plaanid"],
    words: [
      ["ehitama", "to build"],
      ["kirjutama", "to write"],
      ["lugema", "to read"],
      ["ostma", "to buy"],
      ["sööma", "to eat"],
      ["jooma", "to drink"],
      ["lõpetama", "to finish"],
      ["alustama", "to start"],
      ["saatma", "to send"],
      ["tegema", "to make"],
      ["parandama", "to repair"],
      ["müüma", "to sell"],
    ],
  }),

  unit({
    id: "rektsioon",
    title: "Rektsioon",
    subtitle: "Verbs that demand a case",
    icon: "Crosshair",
    level: "B1",
    module: "Grammatika süveneb",
    canDo: "Use the case each common verb requires, instead of the one English suggests.",
    blurb:
      "The unit English speakers get wrong for years: aitan sind, helistan sulle, mulle meeldib. " +
      "Each card asks which case the verb takes.",
    grammar: ["government", "allative", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "GOVERNMENT", "CLOZE"],
    requires: ["objekt"],
    words: [
      ["meeldima", "to please, to be liked by"],
      ["mõtlema", "to think"],
      ["armastama", "to love"],
      ["vihkama", "to hate"],
      ["vajama", "to need"],
      ["uskuma", "to believe"],
      ["tänama", "to thank"],
      ["küsima", "to ask"],
      ["vastama", "to answer"],
      ["sõltuma", "to depend"],
      ["osalema", "to participate"],
      ["tegelema", "to deal with, to be occupied with"],
      ["huvituma", "to be interested"],
      ["loobuma", "to give up, to renounce"],
    ],
  }),

  unit({
    id: "tingiv",
    title: "Tingiv kõneviis",
    subtitle: "Would, could, should",
    icon: "GitBranch",
    level: "B1",
    module: "Grammatika süveneb",
    canDo: "Talk about what would happen, make polite requests and give advice.",
    blurb: "One suffix, -ksi-, and suddenly you can be tactful, hypothetical and polite.",
    grammar: ["conditional", "politeness"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["objekt"],
    words: [
      ["soovitama", "to recommend"],
      ["eelistama", "to prefer"],
      ["kaaluma", "to weigh, to consider"],
      ["pakkuma", "to offer"],
      ["nõudma", "to demand"],
      ["lubama", "to permit, to promise"],
      ["oletama", "to suppose"],
      ["ette kujutama", "to imagine", "VERB"],
      ["tingimus", "condition"],
      ["juhus", "chance, occasion"],
      ["olukord", "situation"],
      ["valik", "choice"],
    ],
  }),

  unit({
    id: "kesksonad",
    title: "Kesksõnad",
    subtitle: "Participles and compound tenses",
    icon: "Layers",
    level: "B1",
    module: "Grammatika süveneb",
    canDo: "Use the perfect and pluperfect, and describe things with participles.",
    blurb: "-nud and -tud do half the work in written Estonian. This is where they start.",
    grammar: ["participles", "perfect", "pluperfect"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["tingiv"],
    words: [
      ["saabuma", "to arrive"],
      ["lahkuma", "to leave, to depart"],
      ["valmima", "to ripen, to be completed"],
      ["katkema", "to break off"],
      ["säilima", "to be preserved"],
      ["tekkima", "to arise, to appear"],
      ["kaduma", "to disappear"],
      ["ilmuma", "to appear, to be published"],
      ["arenema", "to develop"],
      ["paranema", "to improve, to recover"],
      ["halvenema", "to worsen"],
      ["jätkuma", "to continue, to suffice"],
    ],
  }),

  unit({
    id: "too-ja-raha",
    title: "Töö ja raha",
    subtitle: "Work, money and decisions",
    icon: "Briefcase",
    level: "B1",
    module: "Töö ja ühiskond",
    canDo: "Describe your job, discuss pay and conditions, and take part in a meeting.",
    blurb: "Meetings, wages and contracts. B1 vocabulary you meet the week you start a job.",
    grammar: ["genitive", "translative", "object"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["rektsioon"],
    words: [
      ["palk", "wage, salary"],
      ["koosolek", "meeting (a group with an agenda)"],
      ["leping", "contract"],
      ["toode", "product"],
      ["ettevõte", "company, enterprise"],
      ["ülesanne", "task"],
      ["kogemus", "experience"],
      ["oskus", "skill"],
      ["vastutus", "responsibility"],
      ["projekt", "project"],
      ["tähtaeg", "deadline"],
      ["aruanne", "report"],
      ["kasutama", "to use"],
      ["korraldama", "to organize"],
      ["juhtima", "to manage, to lead"],
      ["vastutama", "to be responsible"],
      ["saavutama", "to achieve"],
    ],
  }),

  unit({
    id: "eluase",
    title: "Eluase",
    subtitle: "Housing and moving",
    icon: "KeyRound",
    level: "B1",
    module: "Töö ja ühiskond",
    canDo: "Rent a flat, describe a problem with it and deal with a landlord.",
    blurb: "One of the two conversations every newcomer has to have in Estonian.",
    grammar: ["inessive", "elative", "genitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["too-ja-raha"],
    words: [
      ["üür", "rent"],
      ["üürnik", "tenant"],
      ["omanik", "owner"],
      ["kolimine", "moving house"],
      ["remont", "renovation"],
      ["mööbel", "furniture"],
      ["küte", "heating"],
      ["elekter", "electricity"],
      ["naaber", "neighbor"],
      ["kord", "order, time (occasion)"],
      ["ruum", "space, room"],
      ["kolima", "to move house"],
      ["üürima", "to rent"],
      ["sisustama", "to furnish"],
      ["lekkima", "to leak"],
    ],
  }),

  unit({
    id: "meedia",
    title: "Meedia",
    subtitle: "News and what is in it",
    icon: "Newspaper",
    level: "B1",
    module: "Meedia ja tehnoloogia",
    canDo: "Follow a news bulletin and summarize a story you have read.",
    blurb: "News Estonian is its own register, and it is the fastest way into B2 reading.",
    grammar: ["impersonal", "participles"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kesksonad"],
    words: [
      ["ajakirjanik", "journalist"],
      ["ajakiri", "magazine"],
      ["saade", "broadcast, program"],
      ["intervjuu", "interview"],
      ["allikas", "source"],
      ["pealkiri", "headline"],
      ["artikkel", "article"],
      ["reklaam", "advertisement"],
      ["sündmus", "event"],
      ["teade", "announcement"],
      ["kuulutama", "to proclaim, to advertise"],
      ["avaldama", "to publish, to express"],
      ["kajastama", "to cover, to reflect"],
      ["kommenteerima", "to comment"],
      ["kinnitama", "to confirm"],
    ],
  }),

  unit({
    id: "tehnoloogia",
    title: "Tehnoloogia",
    subtitle: "Computers and the internet",
    icon: "Cpu",
    level: "B1",
    module: "Meedia ja tehnoloogia",
    canDo: "Deal with a device, an account and a technical problem in Estonian.",
    blurb: "Estonia runs on e-services, so this vocabulary is not optional here.",
    grammar: ["object", "impersonal"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["meedia"],
    words: [
      ["seade", "device"],
      ["ekraan", "screen"],
      ["klaviatuur", "keyboard"],
      ["fail", "file"],
      ["kaust", "folder"],
      ["andmed", "data"],
      ["tarkvara", "software"],
      ["rakendus", "application (a piece of software)"],
      ["turvalisus", "security (of a person), safety"],
      ["ühendus", "connection (a link or a service)"],
      ["salvestama", "to save, to record"],
      ["kustutama", "to delete"],
      ["laadima", "to load, to charge"],
      ["uuendama", "to update"],
      ["seadistama", "to configure"],
    ],
  }),

  unit({
    id: "keskkond",
    title: "Keskkond",
    subtitle: "Environment and sustainability",
    icon: "Leaf",
    level: "B1",
    module: "Töö ja ühiskond",
    canDo: "Discuss environmental problems and what should be done about them.",
    blurb: "A topic every B1 exam asks about, and one Estonians genuinely argue over.",
    grammar: ["impersonal", "conditional"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["loodus", "kesksonad"],
    words: [
      ["keskkond", "environment"],
      ["saaste", "pollution"],
      ["jäätmed", "waste"],
      ["taaskasutus", "recycling"],
      ["energia", "energy"],
      ["kliima", "climate", "NOUN"],
      ["liik", "species, kind"],
      ["kaitse", "protection"],
      ["ressurss", "resource"],
      ["tarbimine", "consumption"],
      ["säästma", "to save, to conserve"],
      ["kaitsma", "to protect"],
      ["reostama", "to pollute"],
      ["vähendama", "to reduce"],
      ["sorteerima", "to sort"],
    ],
  }),

  unit({
    id: "haridus",
    title: "Haridus",
    subtitle: "Education and qualifications",
    icon: "School",
    level: "B1",
    module: "Töö ja ühiskond",
    canDo: "Describe your education, apply for a course and discuss the school system.",
    blurb: "What you say when someone asks what you studied, in the register they expect.",
    grammar: ["translative", "elative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kool-ja-keel"],
    words: [
      ["haridus", "education"],
      ["eriala", "field of study"],
      ["kraad", "degree"],
      ["õppekava", "curriculum"],
      ["loeng", "lecture"],
      ["seminar", "seminar"],
      ["eksam", "exam"],
      ["hinne", "grade, mark"],
      ["tunnistus", "certificate"],
      ["stipendium", "scholarship"],
      ["teadmine", "knowledge"],
      ["lõpetaja", "graduate"],
      ["sooritama", "to perform, to sit (an exam)"],
      ["omandama", "to acquire"],
      ["kandideerima", "to apply, to stand for"],
    ],
  }),

  unit({
    id: "inimsuhted",
    title: "Inimsuhted",
    subtitle: "Relationships",
    icon: "HeartHandshake",
    level: "B1",
    module: "Inimsuhted",
    canDo: "Talk about friendships, disagreements and how people get on.",
    blurb: "The vocabulary of getting along, falling out and making up.",
    grammar: ["government", "comitative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "GOVERNMENT", "CLOZE"],
    requires: ["tunded"],
    words: [
      ["suhe", "relationship"],
      ["sõprus", "friendship"],
      ["usaldus", "trust"],
      ["tüli", "quarrel"],
      ["lepitus", "reconciliation"],
      ["abielu", "marriage"],
      ["kohtumine", "meeting (two people coming together)"],
      ["tuttav", "acquaintance"],
      ["usaldama", "to trust"],
      ["tülitsema", "to quarrel"],
      ["leppima", "to make up, to put up with"],
      ["toetama", "to support"],
      ["hoolima", "to care"],
      ["mõistma", "to understand"],
      ["solvama", "to offend"],
    ],
  }),

  unit({
    id: "iseloom",
    title: "Iseloom",
    subtitle: "Character and personality",
    icon: "Smile",
    level: "B1",
    module: "Inimsuhted",
    canDo: "Describe someone's character in more than two adjectives.",
    blurb: "Where an intermediate learner stops saying 'nice' about everybody.",
    grammar: ["adjective-agreement", "derivation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["inimsuhted"],
    words: [
      ["iseloom", "character (a person's)"],
      ["aus", "honest", "ADJECTIVE"],
      ["sõbralik", "friendly", "ADJECTIVE"],
      ["tagasihoidlik", "modest", "ADJECTIVE"],
      ["enesekindel", "self-confident", "ADJECTIVE"],
      ["kannatlik", "patient", "ADJECTIVE"],
      ["hoolas", "diligent", "ADJECTIVE"],
      ["laisk", "lazy", "ADJECTIVE"],
      ["julge", "brave", "ADJECTIVE"],
      ["arglik", "timid", "ADJECTIVE"],
      ["helde", "generous", "ADJECTIVE"],
      ["ihne", "stingy", "ADJECTIVE"],
      ["range", "strict", "ADJECTIVE"],
      ["leebe", "gentle, mild", "ADJECTIVE"],
      ["andekas", "talented", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "arvamus",
    title: "Arvamus",
    subtitle: "Opinions and disagreement",
    icon: "MessagesSquare",
    level: "B1",
    module: "Inimsuhted",
    canDo: "State an opinion, agree, disagree politely and give a reason.",
    blurb: "The connectives that turn a list of sentences into an argument.",
    grammar: ["conditional", "subordination"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["iseloom"],
    words: [
      ["arvamus", "opinion"],
      ["seisukoht", "standpoint"],
      ["põhjus", "reason, cause"],
      ["tagajärg", "consequence"],
      ["näiteks", "for example", "ADVERB"],
      ["vastuolu", "contradiction"],
      ["kahtlus", "doubt"],
      ["kinnitus", "confirmation"],
      ["väitma", "to claim"],
      ["nõustuma", "to agree"],
      ["vaidlema", "to argue"],
      ["kahtlema", "to doubt"],
      ["põhjendama", "to justify (give reasons for)"],
      ["tõestama", "to prove (by reasoning), to demonstrate"],
      ["möönma", "to concede"],
    ],
  }),

  unit({
    id: "probleemid",
    title: "Probleemid",
    subtitle: "Things going wrong",
    icon: "TriangleAlert",
    level: "B1",
    module: "Töö ja ühiskond",
    canDo: "Report a problem, complain effectively and ask for it to be fixed.",
    blurb: "Complaining well is a B1 skill, and it needs its own vocabulary.",
    grammar: ["impersonal", "conditional"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["eluase"],
    words: [
      ["probleem", "problem"],
      ["viga", "fault, mistake"],
      ["kaebus", "complaint"],
      ["lahendus", "solution"],
      ["abi", "help"],
      ["õnnetus", "accident"],
      ["oht", "danger"],
      ["risk", "risk"],
      ["kahju", "damage, pity"],
      ["hüvitis", "compensation"],
      ["kaebama", "to complain"],
      ["lahendama", "to solve"],
      ["põhjustama", "to cause"],
      ["vältima", "to avoid"],
      ["hoiatama", "to warn"],
      // What you actually want at a service desk: it back, or the money back.
      ["tagastama", "to give back, to return"],
      ["puuduma", "to be missing, to be absent"],
    ],
  }),

  unit({
    id: "liitverbid",
    title: "Ühendverbid",
    subtitle: "Verbs with a particle",
    icon: "Combine",
    level: "B1",
    module: "Grammatika süveneb",
    canDo: "Understand how ära, üles and läbi change a verb's meaning completely.",
    blurb: "ära sööma is not sööma. Estonian's phrasal verbs, and they are everywhere.",
    grammar: ["particle-verbs", "aspect", "object"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["objekt"],
    words: [
      ["ära tulema", "to come away, to leave", "VERB"],
      ["üles tõusma", "to get up", "VERB"],
      ["läbi lugema", "to read through", "VERB"],
      ["kokku leppima", "to agree on", "VERB"],
      ["välja nägema", "to look, to appear", "VERB"],
      ["maha jätma", "to abandon", "VERB"],
      ["üle vaatama", "to review, to inspect", "VERB"],
      ["ette valmistama", "to prepare", "VERB"],
      ["sisse astuma", "to enter, to enroll", "VERB"],
      ["edasi andma", "to pass on", "VERB"],
    ],
  }),
] as const;
