/**
 * B2 — from argument to register.
 *
 * A B2 speaker is not one who knows more words than a B1 speaker; they are one
 * who can change how they sound. So four of these units are voice and mood —
 * the impersonal, the quotative, the des-form, and the word formation that lets
 * you turn a verb into a noun and back — and the topic units are the ones an
 * Estonian newspaper actually covers.
 */
import { unit } from "./types";

export const B2 = [
  unit({
    id: "umbisikuline",
    title: "Umbisikuline tegumood",
    subtitle: "When nobody is named",
    icon: "UserX",
    level: "B2",
    module: "Hääl ja kõneviis",
    canDo: "Read and write the impersonal Estonian of notices, news and official writing.",
    blurb: "It isn't the passive. It's how Estonian says people did something without ever saying who.",
    grammar: ["impersonal", "participles"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["liitverbid"],
    words: [
      ["teostama", "to carry out"],
      ["rakendama", "to apply, to implement"],
      ["kehtestama", "to establish, to impose"],
      ["määrama", "to determine, to appoint"],
      ["kinnitama", "to confirm, to approve"],
      ["tühistama", "to cancel, to annul"],
      ["algatama", "to initiate"],
      ["menetlema", "to process (a case)"],
      ["korraldus", "order, arrangement"],
      ["otsustamine", "decision-making"],
      ["läbiviimine", "carrying out"],
      ["kohaldama", "to apply (a rule)"],
    ],
  }),

  unit({
    id: "kaudne",
    title: "Kaudne kõneviis",
    subtitle: "Passing on what you heard",
    icon: "Quote",
    level: "B2",
    module: "Hääl ja kõneviis",
    canDo: "Pass on hearsay with the mood Estonian keeps for it, and notice when it's used on you.",
    blurb: "Where English says apparently, Estonian just changes the verb ending to -vat. You'll hear it in every bit of gossip and half the news.",
    grammar: ["quotative", "reported-speech"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CONJUGATION", "CLOZE"],
    requires: ["umbisikuline"],
    words: [
      ["väitma", "to claim"],
      ["kuulduma", "to be rumored"],
      ["teatama", "to report, to notify"],
      ["mainima", "to mention"],
      ["viitama", "to refer"],
      ["osutama", "to point out, to render"],
      ["rõhutama", "to emphasize"],
      ["kuuldus", "rumor"],
      ["tunnistaja", "witness"],
      ["väide", "claim, assertion"],
      ["tõendus", "evidence"],
      ["oletus", "assumption"],
    ],
  }),

  unit({
    id: "des-vorm",
    title: "Des-vorm",
    subtitle: "Two things at once",
    icon: "Shuffle",
    level: "B2",
    module: "Hääl ja kõneviis",
    canDo: "Join two actions into one sentence, the way written Estonian likes to.",
    blurb: "Kõndides, mõeldes, lugedes: while walking, while thinking, while reading. One ending that stops your writing sounding like a list.",
    grammar: ["converb", "subordination"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["kaudne"],
    words: [
      ["liikuma", "to move"],
      ["püüdma", "to try, to catch"],
      ["jälgima", "to observe, to follow"],
      ["kaaluma", "to consider, to weigh"],
      ["arvestama", "to take into account"],
      ["arutama", "to discuss"],
      ["analüüsima", "to analyze"],
      ["võrdlema", "to compare"],
      ["eristama", "to distinguish"],
      ["ühendama", "to connect, to unite"],
      ["eraldama", "to separate"],
      ["täpsustama", "to specify"],
    ],
  }),

  unit({
    id: "sonamoodustus",
    title: "Sõnamoodustus",
    subtitle: "Building words from words",
    icon: "Blocks",
    level: "B2",
    module: "Hääl ja kõneviis",
    canDo: "Spot the suffix on a word you've never seen and work out what it probably means.",
    blurb: "-us, -lik, -tu, -ne. Learn four suffixes and thousands of words you've never seen start to make sense.",
    grammar: ["derivation", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["des-vorm"],
    words: [
      ["areng", "development (growth or progress)"],
      ["kasv", "growth"],
      ["muutus", "change"],
      ["mõju", "influence"],
      ["tähendus", "meaning"],
      ["võimekus", "capability"],
      ["kättesaadavus", "availability"],
      ["jätkusuutlik", "sustainable", "ADJECTIVE"],
      ["kasutu", "useless", "ADJECTIVE"],
      ["võimatu", "impossible", "ADJECTIVE"],
      ["usaldusväärne", "reliable", "ADJECTIVE"],
      ["põhjalik", "thorough", "ADJECTIVE"],
      ["ulatuslik", "extensive", "ADJECTIVE"],
      ["järjekindel", "consistent", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "uhiskond",
    title: "Ühiskond",
    subtitle: "Society and public life",
    icon: "Landmark",
    level: "B2",
    module: "Avalik elu",
    canDo: "Follow a public debate and take a side in it.",
    blurb: "Words you'll hear on every news bulletin: government, law, economy, rights.",
    grammar: ["impersonal", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["arvamus"],
    words: [
      ["ühiskond", "society"],
      ["valitsus", "government"],
      ["seadus", "law", "NOUN", 231517],
      ["õigus", "right, law", "NOUN", 260736],
      ["kohustus", "obligation"],
      ["kodanik", "citizen"],
      ["rahvas", "people, nation"],
      ["vabadus", "freedom"],
      ["võrdsus", "equality"],
      ["heaolu", "welfare, wellbeing"],
      ["kogukond", "community"],
      ["põlvkond", "generation"],
      ["rahvastik", "population"],
      ["ränne", "migration"],
      ["lõimumine", "integration"],
      ["rahvusvaheline", "international", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "poliitika",
    title: "Poliitika",
    subtitle: "Politics and power",
    icon: "Vote",
    level: "B2",
    module: "Avalik elu",
    canDo: "Understand election coverage and explain how a decision gets made.",
    blurb: "Estonian political words are mostly Latin-based and regular, so they come quickly.",
    grammar: ["nominalisation", "impersonal"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["uhiskond"],
    words: [
      ["erakond", "political party"],
      ["valimised", "elections"],
      ["hääletus", "vote, ballot", "NOUN", 170918],
      ["riigikogu", "parliament"],
      ["minister", "minister"],
      ["koalitsioon", "coalition"],
      ["opositsioon", "opposition"],
      ["poliitik", "politician"],
      ["võim", "power"],
      ["reform", "reform"],
      ["eelnõu", "draft bill"],
      ["kampaania", "campaign"],
      ["hääletama", "to vote"],
      ["esindama", "to represent"],
      ["kritiseerima", "to criticize"],
    ],
  }),

  unit({
    id: "majandus",
    title: "Majandus",
    subtitle: "Economy and business",
    icon: "TrendingUp",
    level: "B2",
    module: "Avalik elu",
    canDo: "Read a business page and explain an economic trend.",
    blurb: "Numbers going up and down, and the verbs Estonian uses to say so.",
    grammar: ["comparative", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["too-ja-raha"],
    words: [
      ["majandus", "economy"],
      ["turg", "market"],
      ["nõudlus", "demand"],
      ["pakkumine", "supply, offer"],
      ["hinnatõus", "price rise"],
      ["inflatsioon", "inflation"],
      ["investeering", "investment"],
      ["kasum", "profit"],
      ["kahjum", "loss"],
      ["maks", "tax", "NOUN", 200115],
      ["eelarve", "budget"],
      ["kriis", "crisis"],
      ["tööpuudus", "unemployment"],
      ["konkurents", "competition (rivalry)"],
      ["kasvama", "to grow"],
      ["langema", "to fall"],
    ],
  }),

  unit({
    id: "oigus",
    title: "Õigus",
    subtitle: "Law and justice",
    icon: "Gavel",
    level: "B2",
    module: "Avalik elu",
    canDo: "Understand a legal notice and describe a dispute and how it ended.",
    blurb: "The language of contracts and courts, where the impersonal never goes away.",
    grammar: ["impersonal", "quotative"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["poliitika"],
    words: [
      ["kohus", "court", "NOUN", 283694],
      ["kohtunik", "judge"],
      ["advokaat", "lawyer"],
      ["süüdistus", "accusation"],
      ["karistus", "punishment"],
      ["kuritegu", "crime"],
      ["tõend", "piece of evidence"],
      ["otsus", "judgment, decision"],
      ["hagi", "lawsuit"],
      ["kahtlustatav", "suspect"],
      ["süütu", "innocent", "ADJECTIVE"],
      ["seaduslik", "lawful", "ADJECTIVE"],
      ["karistama", "to punish"],
      ["kaebama", "to appeal, to complain"],
      ["tõendama", "to prove (by producing evidence)"],
      ["isik", "person"],
    ],
  }),

  unit({
    id: "teadus",
    title: "Teadus",
    subtitle: "Science and method",
    icon: "FlaskConical",
    level: "B2",
    module: "Mõte ja kultuur",
    canDo: "Follow a popular science article and describe how a study was done.",
    blurb: "The words for how research is done, which you'll carry straight into academic writing at C1.",
    grammar: ["impersonal", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["sonamoodustus"],
    words: [
      ["teadus", "science"],
      ["uuring", "study, survey"],
      ["katse", "experiment, attempt", "NOUN", 179036],
      ["meetod", "method"],
      ["tulemus", "result"],
      ["järeldus", "conclusion"],
      ["hüpotees", "hypothesis"],
      ["mudel", "model"],
      ["andmestik", "dataset"],
      ["täpsus", "accuracy"],
      ["uurima", "to investigate"],
      ["mõõtma", "to measure"],
      ["järeldama", "to conclude"],
      ["veenduma", "to make sure"],
      ["avastama", "to discover"],
    ],
  }),

  unit({
    id: "ajalugu",
    title: "Ajalugu",
    subtitle: "History",
    icon: "Landmark",
    level: "B2",
    module: "Mõte ja kultuur",
    canDo: "Tell the story of past events and explain why they mattered.",
    blurb: "Long stretches of storytelling in the past tense, and most of what the country talks about.",
    grammar: ["imperfect", "pluperfect", "participles"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["kesksonad"],
    words: [
      ["ajalugu", "history"],
      ["sajand", "century"],
      ["ajastu", "era"],
      ["sõda", "war"],
      ["rahu", "peace", "NOUN", 225099],
      ["iseseisvus", "independence"],
      ["okupatsioon", "occupation"],
      ["revolutsioon", "revolution"],
      ["pärand", "heritage"],
      ["mälestus", "memory, remembrance"],
      ["allikas", "source"],
      ["vabanema", "to become free"],
      ["vallutama", "to conquer"],
      ["taastama", "to restore"],
      ["säilitama", "to preserve"],
    ],
  }),

  unit({
    id: "kunst",
    title: "Kunst ja kultuur",
    subtitle: "The arts",
    icon: "Drama",
    level: "B2",
    module: "Mõte ja kultuur",
    canDo: "Review a film, a book or an exhibition and back up your verdict.",
    blurb: "Words for opinions, and something worth having an opinion about.",
    grammar: ["comparative", "subordination"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["ajalugu"],
    words: [
      ["kunst", "art", "NOUN", 187802],
      ["kirjandus", "literature"],
      ["luule", "poetry"],
      ["romaan", "novel"],
      ["näidend", "play"],
      ["lavastus", "production, staging"],
      ["autor", "author"],
      ["teos", "work (of art)"],
      ["stiil", "style"],
      ["sisu", "content"],
      ["vorm", "form", "NOUN", 257760],
      ["kriitika", "criticism"],
      ["tõlgendus", "interpretation"],
      ["looma", "to create"],
      ["kujutama", "to depict"],
      ["kultuur", "culture"],
      ["kunstnik", "artist"],
    ],
  }),

  unit({
    id: "psuhholoogia",
    title: "Psühholoogia",
    subtitle: "Mind and behavior",
    icon: "Brain",
    level: "B2",
    module: "Mõte ja kultuur",
    canDo: "Talk about motivation, habits and behavior in abstract terms.",
    blurb: "Abstract nouns you can actually use, and a workout for -mine and -us.",
    grammar: ["nominalisation", "derivation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["sonamoodustus"],
    words: [
      ["käitumine", "behavior"],
      ["harjumus", "habit"],
      ["motivatsioon", "motivation"],
      ["teadvus", "consciousness"],
      ["mälu", "memory"],
      ["taju", "perception"],
      ["hoiak", "attitude"],
      ["isiksus", "personality"],
      ["stress", "stress"],
      ["enesehinnang", "self-esteem"],
      ["mõjutama", "to influence"],
      ["reageerima", "to react"],
      ["kohanema", "to adapt (oneself), to settle in"],
      ["keskenduma", "to concentrate"],
      ["tajuma", "to perceive"],
    ],
  }),

  unit({
    id: "tervishoid",
    title: "Tervishoid",
    subtitle: "The health system",
    icon: "Stethoscope",
    level: "B2",
    module: "Avalik elu",
    canDo: "Find your way around the health system and discuss public health policy.",
    blurb: "Beyond 'my throat hurts': the system that decides who treats it.",
    grammar: ["impersonal", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["keha-ja-tervis", "uhiskond"],
    words: [
      ["tervishoid", "health care"],
      ["ravi", "treatment"],
      ["diagnoos", "diagnosis"],
      ["vaktsiin", "vaccine"],
      ["nakkus", "infection"],
      ["epideemia", "epidemic"],
      ["kindlustus", "insurance"],
      ["saatekiri", "referral"],
      ["ennetus", "prevention"],
      ["taastusravi", "rehabilitation"],
      ["ravima", "to treat, to cure"],
      ["ennetama", "to prevent"],
      ["nakatuma", "to become infected"],
      ["diagnoosima", "to diagnose"],
      ["patsient", "patient"],
    ],
  }),

  unit({
    id: "toomaailm",
    title: "Töömaailm",
    subtitle: "Working life",
    icon: "Users",
    level: "B2",
    module: "Avalik elu",
    canDo: "Handle a job interview, a negotiation and a difficult conversation at work.",
    blurb: "The words that make you sound like a colleague rather than a textbook.",
    grammar: ["conditional", "politeness", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["too-ja-raha"],
    words: [
      ["kandidaat", "candidate"],
      ["värbamine", "recruitment"],
      ["ametikoht", "position, post"],
      ["juhend", "instruction, guide"],
      ["tagasiside", "feedback"],
      ["läbirääkimised", "negotiations"],
      ["kompromiss", "compromise"],
      ["konflikt", "conflict"],
      ["meeskond", "team"],
      ["edutamine", "promotion"],
      ["koondamine", "redundancy"],
      ["läbi rääkima", "to negotiate", "VERB"],
      ["delegeerima", "to delegate"],
      ["motiveerima", "to motivate"],
    ],
  }),

  unit({
    id: "statistika",
    title: "Arvud ja suundumused",
    subtitle: "Charts and figures",
    icon: "ChartLine",
    level: "B2",
    module: "Mõte ja kultuur",
    canDo: "Describe a chart, a trend and a proportion accurately.",
    blurb: "Exams ask for this all the time, and so does every presentation at work.",
    grammar: ["comparative", "partitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CASE_FORM", "CLOZE"],
    requires: ["majandus"],
    words: [
      ["osakaal", "proportion, share"],
      ["protsent", "per cent"],
      ["keskmine", "average", "ADJECTIVE"],
      ["kasvutempo", "growth rate"],
      ["langus", "decline"],
      ["tõus", "rise"],
      ["suundumus", "trend"],
      ["näitaja", "indicator"],
      ["võrdlus", "comparison"],
      ["valim", "sample"],
      ["ligikaudu", "approximately", "ADVERB"],
      ["oluliselt", "significantly", "ADVERB"],
      ["ületama", "to exceed"],
      ["moodustama", "to constitute"],
    ],
  }),

  unit({
    id: "argumenteerimine",
    title: "Argumenteerimine",
    subtitle: "Building a case",
    icon: "ScrollText",
    level: "B2",
    module: "Mõte ja kultuur",
    canDo: "Structure a written argument, with concession and counter-argument.",
    blurb: "The linking words and hedges that hold a B2 essay together.",
    grammar: ["subordination", "concession", "hedging"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["arvamus", "sonamoodustus"],
    words: [
      ["seisukoht", "position, standpoint"],
      ["vastuväide", "counter-argument"],
      ["eeldus", "premise, assumption"],
      ["järeldus", "conclusion"],
      ["tõendusmaterjal", "body of evidence"],
      ["üldistus", "generalization"],
      ["erand", "exception"],
      ["kokkuvõte", "summary"],
      ["seetõttu", "therefore", "ADVERB"],
      ["seevastu", "by contrast, whereas", "ADVERB"],
      ["ometi", "nevertheless", "ADVERB"],
      // A literary "but", commoner in an essay than in speech, which is why it is
      // taught here rather than beside aga: Ekilex bands it B2.
      ["ent", "but, however", "ADVERB"],
      ["eeldama", "to presuppose"],
      ["üldistama", "to generalize"],
      ["ümber lükkama", "to refute", "VERB"],
    ],
  }),
] as const;
