/**
 * C1 — from register to control.
 *
 * At C1 the learner already understands everything in a newspaper. What is
 * missing is production: the ability to nominalise, to subordinate three clauses
 * without losing the thread, to hedge a claim precisely, and to hear the
 * difference between two near-synonyms. So the grammar units here are about
 * compression — turning clauses into phrases — and the topic units are the ones
 * that demand abstraction rather than vocabulary.
 */
import { unit } from "./types";

export const C1 = [
  unit({
    id: "nominalisatsioon",
    title: "Nominalisatsioon",
    subtitle: "Turning clauses into phrases",
    icon: "Minimize2",
    level: "C1",
    module: "Tihendamine",
    canDo: "Compress a clause into a noun phrase the way formal Estonian expects.",
    blurb: "The single biggest difference between B2 prose and C1 prose is density.",
    grammar: ["nominalisation", "derivation", "genitive"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["argumenteerimine"],
    words: [
      ["rakendamine", "application, implementation"],
      ["kujunemine", "formation, development"],
      ["hindamine", "assessment"],
      ["kättesaamine", "receipt, obtaining"],
      ["täitmine", "fulfillment, execution"],
      ["kehtivus", "validity"],
      ["ulatus", "extent, scope"],
      ["määr", "rate, degree"],
      ["sõltuvus", "dependence"],
      ["paratamatus", "inevitability"],
      ["võimalikkus", "possibility"],
      ["seaduspärasus", "regularity, pattern"],
      ["väljendus", "expression (the act of expressing)"],
      ["toimimine", "functioning"],
      ["loomine", "creation"],
      ["säilitamine", "preservation"],
      ["kujundamine", "shaping"],
      ["teostus", "execution"],
    ],
  }),

  unit({
    id: "lauseloome",
    title: "Lauseloome",
    subtitle: "Long sentences that still work",
    icon: "Network",
    level: "C1",
    module: "Tihendamine",
    canDo: "Build a three-clause sentence that stays readable, and punctuate it correctly.",
    blurb: "Estonian subordination, relative clauses and the comma rules nobody teaches you.",
    grammar: ["subordination", "relative-clause", "punctuation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["nominalisatsioon"],
    words: [
      ["seos", "connection (between things)"],
      ["suhe", "relation"],
      ["raamistik", "framework"],
      ["kontekst", "context"],
      ["aspekt", "aspect"],
      ["mõõde", "dimension"],
      ["tasand", "level, plane"],
      ["lähtekoht", "starting point"],
      ["lähtuma", "to proceed from"],
      ["tulenema", "to result from"],
      ["seonduma", "to be connected"],
      ["hõlmama", "to encompass"],
      ["piirduma", "to be limited to"],
      ["kajastuma", "to be reflected"],
      ["kõrvallause", "subordinate clause"],
      ["pealause", "main clause"],
      ["sidesõna", "conjunction"],
      ["koma", "comma", "NOUN"],
      ["täiend", "attribute, modifier"],
    ],
  }),

  unit({
    id: "akadeemiline",
    title: "Akadeemiline eesti keel",
    subtitle: "Arguing a point",
    icon: "ScrollText",
    level: "C1",
    module: "Teadmine",
    canDo: "Write an academic paragraph with a claim, support and a qualification.",
    blurb: "Verbs and nouns for writing an essay or holding a position: tuginema, käsitlema, veenev.",
    grammar: ["hedging", "government", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "GOVERNMENT", "CLOZE"],
    requires: ["lauseloome"],
    words: [
      ["tuginema", "to be based on"],
      ["käsitlema", "to treat, to deal with"],
      ["kirjeldama", "to describe"],
      ["hindama", "to assess, to value"],
      ["põhjendus", "justification"],
      ["erinevus", "difference"],
      ["sarnasus", "similarity"],
      ["tõenäoline", "probable", "ADJECTIVE"],
      ["veenev", "convincing", "ADJECTIVE"],
      ["vastuoluline", "contradictory", "ADJECTIVE"],
      ["ammendav", "exhaustive", "ADJECTIVE"],
      ["asjakohane", "relevant", "ADJECTIVE"],
      ["kaheldav", "questionable", "ADJECTIVE"],
      ["ilmne", "evident", "ADJECTIVE"],
      ["arutlus", "reasoning, discussion"],
      ["analüüs", "analysis"],
      ["argument", "argument"],
      ["loogika", "logic"],
      ["struktuur", "structure"],
      ["tõestus", "proof"],
    ],
  }),

  unit({
    id: "teadustoo",
    title: "Teadustöö",
    subtitle: "Research writing",
    icon: "Microscope",
    level: "C1",
    module: "Teadmine",
    canDo: "Read a research abstract and describe a study's design and limits.",
    blurb: "The conventions of Estonian academic prose, which are stricter than the English ones.",
    grammar: ["impersonal", "hedging", "nominalisation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["akadeemiline"],
    words: [
      ["uurimus", "research study"],
      ["metoodika", "methodology"],
      ["valim", "sample"],
      ["muutuja", "variable"],
      ["korrelatsioon", "correlation"],
      ["piirang", "limitation"],
      ["usaldusväärsus", "reliability"],
      ["kehtivus", "validity"],
      ["kordus", "replication"],
      ["viitamine", "referencing"],
      ["püstitama", "to formulate, to set up"],
      ["testima", "to test"],
      ["kontrollima", "to verify, to check"],
      ["tõlgendama", "to interpret"],
      ["uurija", "researcher"],
      ["teadlane", "scientist"],
      ["eksperiment", "experiment"],
      ["publikatsioon", "publication"],
      ["andmebaas", "database"],
      ["statistika", "statistics"],
    ],
  }),

  unit({
    id: "filosoofia",
    title: "Filosoofia",
    subtitle: "Ideas in the abstract",
    icon: "Lightbulb",
    level: "C1",
    module: "Teadmine",
    canDo: "Discuss an abstract idea without reaching for a concrete example every sentence.",
    blurb: "Vocabulary that only exists at this level, and the register that carries it.",
    grammar: ["nominalisation", "subordination"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["akadeemiline"],
    words: [
      ["mõiste", "concept"],
      ["olemus", "essence"],
      ["tõde", "truth"],
      ["teadmine", "knowledge"],
      ["veendumus", "conviction"],
      ["põhimõte", "principle"],
      ["väärtus", "value"],
      ["tähendusrikas", "meaningful", "ADJECTIVE"],
      ["abstraktne", "abstract", "ADJECTIVE"],
      ["subjektiivne", "subjective", "ADJECTIVE"],
      ["objektiivne", "objective", "ADJECTIVE"],
      ["määratlema", "to define"],
      ["eeldama", "to presuppose"],
      ["järeldama", "to infer"],
      ["teooria", "theory"],
      ["mõtlemine", "thinking"],
      ["arusaam", "understanding, notion"],
      ["seisukohavõtt", "taking a position"],
      ["paradoks", "paradox"],
      ["üldkehtiv", "universally valid", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "eetika",
    title: "Eetika",
    subtitle: "Right, wrong and responsibility",
    icon: "Scale",
    level: "C1",
    module: "Teadmine",
    canDo: "Argue an ethical position and steelman the one you disagree with.",
    blurb: "The topic every C1 exam essay is secretly about.",
    grammar: ["conditional", "concession", "hedging"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["filosoofia"],
    words: [
      ["eetika", "ethics"],
      ["moraal", "morality"],
      ["kohusetunne", "sense of duty"],
      ["õiglus", "justice"],
      ["ausus", "honesty"],
      ["vastutustunne", "sense of responsibility"],
      ["dilemma", "dilemma", "NOUN"],
      ["kompromiss", "compromise"],
      ["õiglane", "just, fair", "ADJECTIVE"],
      ["lubamatu", "impermissible", "ADJECTIVE"],
      ["erapooletu", "impartial", "ADJECTIVE"],
      ["õigustama", "to justify (defend as right)"],
      ["hukka mõistma", "to condemn", "VERB"],
      ["kaalutlema", "to deliberate"],
      ["väärkasutus", "misuse"],
      ["kohustuslikkus", "obligatoriness"],
      ["hüve", "benefit, good"],
      ["kahjulik", "harmful", "ADJECTIVE"],
      ["lugupidamine", "respect"],
    ],
  }),

  unit({
    id: "retoorika",
    title: "Retoorika",
    subtitle: "Persuading people",
    icon: "Megaphone",
    level: "C1",
    module: "Väljendus",
    canDo: "Give a persuasive talk and recognize the devices used on you.",
    blurb: "Speech Estonian, which is not written Estonian read aloud.",
    grammar: ["word-order", "emphasis", "rhetorical-questions"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["akadeemiline"],
    words: [
      ["veenmine", "persuasion"],
      ["kõne", "speech"],
      ["ettekanne", "presentation"],
      ["publik", "audience"],
      ["rõhuasetus", "emphasis"],
      ["kujund", "figure of speech"],
      ["võrdpilt", "metaphor, simile"],
      ["liialdus", "exaggeration"],
      ["veenma", "to persuade"],
      ["mõjuma", "to have an effect"],
      ["esile tõstma", "to highlight", "VERB"],
      ["õõnestama", "to undermine"],
      ["ümber veenma", "to talk round", "VERB"],
      ["veenvus", "persuasiveness"],
      ["väitlus", "debate"],
      ["esinemine", "performance, appearance"],
      ["sõnavõtt", "speech, statement"],
      ["kuulaja", "listener"],
      ["mulje", "impression"],
    ],
  }),

  unit({
    id: "register",
    title: "Register",
    subtitle: "Formal, neutral, familiar",
    icon: "SlidersHorizontal",
    level: "C1",
    module: "Väljendus",
    canDo: "Say the same thing three ways and pick the right one for the room.",
    blurb: "The C1 skill that has nothing to do with knowing more words.",
    grammar: ["register", "politeness", "word-order"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["retoorika"],
    words: [
      ["kõnekeel", "colloquial speech"],
      ["kirjakeel", "standard written language"],
      ["släng", "slang"],
      ["ametlik", "official", "ADJECTIVE"],
      ["mitteametlik", "informal", "ADJECTIVE"],
      ["viisakas", "polite", "ADJECTIVE"],
      ["familiaarne", "familiar", "ADJECTIVE"],
      ["kohmakas", "clumsy", "ADJECTIVE"],
      ["ladus", "fluent, smooth", "ADJECTIVE"],
      ["täpne", "precise", "ADJECTIVE"],
      ["ähmane", "vague", "ADJECTIVE"],
      ["sõnastama", "to word, to phrase"],
      ["ümber sõnastama", "to rephrase", "VERB"],
      ["stiilivärving", "stylistic coloring"],
      ["väljendusviis", "mode of expression"],
      ["suhtlusolukord", "communicative situation"],
      ["neutraalne", "neutral", "ADJECTIVE"],
      ["pidulik", "formal, ceremonious", "ADJECTIVE"],
      ["argine", "everyday (humdrum)", "ADJECTIVE"],
    ],
  }),

  unit({
    id: "idioomid",
    title: "Kõnekäänud",
    subtitle: "Idiom and fixed expression",
    icon: "Sparkles",
    level: "C1",
    module: "Väljendus",
    canDo: "Use and understand common idioms without translating them word by word.",
    blurb: "Where a fluent speaker stops sounding like a very good textbook.",
    grammar: ["idiom", "register"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["register"],
    words: [
      ["kõnekäänd", "saying, idiom"],
      ["vanasõna", "proverb"],
      ["väljend", "expression (a phrase)"],
      ["ütlus", "saying"],
      ["nali", "joke"],
      ["tähendusvarjund", "shade of meaning"],
      ["piltlik", "figurative", "ADJECTIVE"],
      ["otsene", "direct, literal", "ADJECTIVE"],
      ["kaudne", "indirect", "ADJECTIVE"],
      ["tabav", "apt, well-aimed", "ADJECTIVE"],
      ["vihjama", "to hint"],
      ["viitama", "to allude"],
      ["püsiühend", "fixed expression"],
      ["ülekantud", "transferred, figurative", "ADJECTIVE"],
      ["tähenduslik", "meaningful", "ADJECTIVE"],
      ["rahvatarkus", "folk wisdom"],
      ["kujundlikkus", "figurativeness"],
      ["mõistukõne", "parable, allegory"],
    ],
  }),

  unit({
    id: "diskursus",
    title: "Sidusus",
    subtitle: "Holding a text together",
    icon: "Link",
    level: "C1",
    module: "Tihendamine",
    canDo: "Signpost a long text so a reader never loses the thread.",
    blurb: "Discourse markers: the difference between a text and a pile of sentences.",
    grammar: ["cohesion", "subordination", "word-order"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["lauseloome"],
    words: [
      ["sidusus", "cohesion"],
      ["ülesehitus", "structure"],
      ["lõik", "paragraph"],
      ["sissejuhatus", "introduction"],
      ["järeldus", "conclusion"],
      ["üleminek", "transition"],
      ["esiteks", "firstly", "ADVERB"],
      ["teisalt", "on the other hand", "ADVERB"],
      ["lisaks", "in addition", "ADVERB"],
      ["järelikult", "consequently", "ADVERB"],
      ["kokkuvõttes", "in summary", "ADVERB"],
      ["täpsemalt", "more precisely", "ADVERB"],
      ["tekst", "text"],
      ["viide", "reference"],
      ["alapealkiri", "subheading"],
      ["mõttekäik", "train of thought"],
      ["selgus", "clarity"],
      ["järgnevus", "sequence"],
    ],
  }),

  unit({
    id: "innovatsioon",
    title: "Innovatsioon",
    subtitle: "Technology and change",
    icon: "Rocket",
    level: "C1",
    module: "Maailm",
    canDo: "Discuss technological change and its social consequences.",
    blurb: "Estonia's favorite subject, in the register it is actually discussed in.",
    grammar: ["nominalisation", "hedging"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["tehnoloogia", "akadeemiline"],
    words: [
      ["uuendus", "innovation"],
      ["läbimurre", "breakthrough"],
      ["tehisintellekt", "artificial intelligence"],
      ["automatiseerimine", "automation"],
      ["digitaliseerimine", "digitalisation"],
      ["taristu", "infrastructure"],
      ["küberturvalisus", "cyber security"],
      ["privaatsus", "privacy"],
      ["väärikus", "dignity"],
      ["rakendus", "application"],
      ["juurutama", "to introduce, to roll out"],
      ["kohandama", "to adapt (something)"],
      ["asendama", "to replace"],
      ["arendus", "development (of land or a building)"],
      ["prototüüp", "prototype"],
      ["mastaap", "scale"],
      ["kasutajakogemus", "user experience"],
      ["algoritm", "algorithm"],
      ["andmekaitse", "data protection"],
    ],
  }),

  unit({
    id: "rahvusvaheline",
    title: "Rahvusvahelised suhted",
    subtitle: "The world outside",
    icon: "Globe",
    level: "C1",
    module: "Maailm",
    canDo: "Follow international coverage and describe a diplomatic position.",
    blurb: "A register with its own euphemisms, and Estonia has strong views in it.",
    grammar: ["quotative", "hedging", "impersonal"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["poliitika"],
    words: [
      ["välispoliitika", "foreign policy"],
      ["diplomaatia", "diplomacy"],
      ["liit", "alliance, union"],
      ["leping", "treaty"],
      ["sanktsioon", "sanction"],
      ["julgeolek", "security (of a country)"],
      ["konflikt", "conflict"],
      ["läbirääkimine", "negotiation"],
      ["suveräänsus", "sovereignty"],
      ["kokkulepe", "agreement"],
      ["vahendama", "to mediate"],
      ["sekkuma", "to intervene"],
      ["toetuma", "to rely on"],
      ["saatkond", "embassy"],
      ["resolutsioon", "resolution"],
      ["ühisavaldus", "joint statement"],
      ["liikmesriik", "member state"],
      ["koostöö", "cooperation"],
      ["survestama", "to pressure"],
    ],
  }),

  unit({
    id: "kirjandus",
    title: "Kirjandus",
    subtitle: "Reading literature",
    icon: "BookOpen",
    level: "C1",
    module: "Väljendus",
    canDo: "Read an Estonian novel and talk about how it is written, not just what happens.",
    blurb: "Literary Estonian uses forms the spoken language dropped. This is where you meet them.",
    grammar: ["participles", "converb", "word-order"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["kunst", "register"],
    words: [
      ["jutustaja", "narrator"],
      ["tegelane", "character (in a story)"],
      ["süžee", "plot"],
      ["ülesehitus", "structure"],
      ["motiiv", "motif"],
      ["sümbol", "symbol"],
      ["meeleolu", "mood, atmosphere"],
      ["kujundlik", "imagery-rich", "ADJECTIVE"],
      ["mõjuv", "powerful, effective", "ADJECTIVE"],
      ["peen", "subtle, fine", "ADJECTIVE"],
      ["jutustama", "to narrate"],
      ["vihjama", "to allude"],
      ["proosa", "prose"],
      ["värss", "verse"],
      ["peategelane", "protagonist"],
      ["kirjanik", "writer"],
      ["pöördepunkt", "turning point"],
    ],
  }),

  unit({
    id: "nuansid",
    title: "Nüansid",
    subtitle: "Near-synonyms and precision",
    icon: "Focus",
    level: "C1",
    module: "Väljendus",
    canDo: "Choose between two words that a dictionary glosses identically.",
    blurb: "The last thing a learner acquires, and the first thing a native speaker notices.",
    grammar: ["register", "collocation"],
    cardTypes: ["RECOGNITION", "PRODUCTION", "CLOZE"],
    requires: ["idioomid"],
    words: [
      ["erinevus", "difference"],
      ["varjund", "nuance, shade"],
      ["täpsustus", "clarification"],
      ["üldistus", "generalization"],
      ["selgitus", "explanation"],
      ["tähelepanek", "observation"],
      ["märkus", "remark"],
      ["hoiatus", "warning"],
      ["taotlema", "to strive for, to apply for"],
      ["püüdlema", "to aspire"],
      ["saavutama", "to attain"],
      ["omandama", "to acquire"],
      ["valdama", "to master, to command"],
      ["rõhutus", "lack of stress", "NOUN", 459033],
      ["alltekst", "subtext"],
      ["selgitama", "to clarify"],
      ["omapärane", "distinctive", "ADJECTIVE"],
      ["napp", "scant, terse", "ADJECTIVE"],
    ],
  }),
] as const;
