/**
 * The words the course no longer teaches and the dictionary keeps.
 *
 * The ten C2 units were cut in the thirteenth pass (docs/13-mvp-status.md
 * §19) with the note that their vocabulary stays in the dictionary, since
 * removing real, Ekilex-sourced words because their unit was cut would be
 * deleting correct data over an unrelated decision. The harvest reads the
 * syllabus, so the moment it was re-run those 170 words would have left the
 * seed with it. This is the list that keeps them: the same shape as a unit's
 * word list, lemma and authored English gloss, and the same rule that Ekilex
 * decides whether each one exists.
 *
 * Read by scripts/harvest-ekilex.ts alongside the units. Not a unit, so no
 * screen lists it and no card is built from it unless a learner looks one of
 * these up, which is the same standing every other dictionary word has.
 */
import type { WordSpec } from "./types";

export const RETIRED_WORDS: readonly WordSpec[] = [
  ["aktsent", "accent", "NOUN"],
  ["alliteratsioon", "alliteration", "NOUN"],
  ["annus", "dose", "NOUN"],
  ["arhailine", "archaic", "ADJECTIVE"],
  ["arusaamatus", "misunderstanding", "NOUN"],
  ["arusaamine", "understanding", "NOUN"],
  ["arvamuslugu", "opinion piece", "NOUN"],
  ["avalikkus", "the public sphere", "NOUN"],
  ["defineerima", "to define", "VERB"],
  ["ekvivalent", "equivalent (of equal value)", "NOUN", 163239],
  ["elegantne", "elegant", "ADJECTIVE"],
  ["emakeel", "native language", "NOUN"],
  ["enesekindlus", "self-assurance", "NOUN"],
  ["erialane", "specialist", "ADJECTIVE"],
  ["eristuma", "to stand out, to differ", "VERB"],
  ["eristus", "distinction", "NOUN"],
  ["essee", "essay", "NOUN"],
  ["etteheide", "reproach", "NOUN"],
  ["hageja", "plaintiff", "NOUN"],
  ["hagiavaldus", "statement of claim", "NOUN"],
  ["harjuma", "to get used to", "VERB"],
  ["harjumuspärane", "habitual", "ADJECTIVE"],
  ["huumor", "humor", "NOUN"],
  ["häbistav", "shaming", "ADJECTIVE"],
  ["hääldus", "pronunciation", "NOUN"],
  ["igapäevane", "everyday (happening daily)", "ADJECTIVE"],
  ["iroonia", "irony", "NOUN"],
  ["irvitama", "to sneer", "VERB"],
  ["juhtkiri", "editorial", "NOUN"],
  ["jõustuma", "to come into force", "VERB"],
  ["jõustumine", "entry into force", "NOUN"],
  ["kaalukas", "weighty", "ADJECTIVE"],
  ["kahemõtteline", "ambiguous", "ADJECTIVE"],
  ["kalambuur", "pun", "NOUN"],
  ["kantseliitlik", "bureaucratic", "ADJECTIVE"],
  ["kattuvus", "overlap", "NOUN"],
  ["keelekasutaja", "language user", "NOUN"],
  ["keelekasutus", "language use", "NOUN"],
  ["keelekeskkond", "language environment", "NOUN"],
  ["keelenorm", "language norm", "NOUN"],
  ["keeleoskus", "language skill", "NOUN"],
  ["keelevahetus", "language switching", "NOUN"],
  ["kirjaviis", "orthography, spelling", "NOUN"],
  ["kitsendus", "restriction", "NOUN"],
  ["klassifikatsioon", "classification", "NOUN"],
  ["kogenud", "experienced", "ADJECTIVE"],
  ["kohustama", "to oblige", "VERB"],
  ["kohustuslik", "obligatory", "ADJECTIVE"],
  ["kolumnist", "columnist", "NOUN"],
  ["kommentaar", "commentary", "NOUN"],
  ["konkreetne", "concrete", "ADJECTIVE"],
  ["koomiline", "comic", "ADJECTIVE"],
  ["kostja", "defendant", "NOUN"],
  ["kõla", "sound, resonance", "NOUN"],
  ["kõnekeelne", "colloquial", "ADJECTIVE"],
  ["kõnepruuk", "way of speaking, parlance", "NOUN"],
  ["kõrvalekalle", "deviation", "NOUN"],
  ["kõrvaltoime", "side effect", "NOUN"],
  ["käsitlus", "treatment, approach", "NOUN"],
  ["laiendus", "extension", "NOUN"],
  ["lakooniline", "laconic", "ADJECTIVE"],
  ["lauseehitus", "sentence construction", "NOUN"],
  ["leidlik", "inventive", "ADJECTIVE"],
  ["levinud", "widespread", "ADJECTIVE"],
  ["ligikaudne", "approximate", "ADJECTIVE"],
  ["ligilähedaselt", "approximately", "ADVERB"],
  ["lihtsustama", "to simplify", "VERB"],
  ["loomulik", "natural", "ADJECTIVE"],
  ["lugejaskond", "readership", "NOUN"],
  ["luuletus", "poem", "NOUN"],
  ["läbinägelik", "perceptive", "ADJECTIVE"],
  ["lähtekeel", "source language", "NOUN"],
  ["menetlus", "proceedings", "NOUN"],
  ["mitmetähenduslik", "polysemous", "ADJECTIVE"],
  ["mitmetähenduslikkus", "polysemy", "NOUN"],
  ["moonutama", "to distort", "VERB"],
  ["mugandus", "adaptation", "NOUN"],
  ["murdesõna", "dialect word", "NOUN"],
  ["murrak", "local dialect", "NOUN"],
  ["murre", "dialect", "NOUN", 204633],
  ["mõistatus", "riddle", "NOUN"],
  ["mõnitus", "taunt", "NOUN"],
  ["määratlemine", "definition, delimitation", "NOUN"],
  ["määratlus", "definition", "NOUN"],
  ["määrus", "regulation", "NOUN"],
  ["naljatama", "to joke", "VERB"],
  ["norm", "norm", "NOUN", 208960],
  ["nutikas", "clever", "ADJECTIVE", 209401],
  ["näidustus", "indication", "NOUN"],
  ["nüansirikas", "nuanced", "ADJECTIVE"],
  ["ohtrasõnaline", "verbose", "ADJECTIVE"],
  ["olenev", "depending", "ADJECTIVE"],
  ["omaks võtma", "to adopt, to embrace", "VERB"],
  ["ootamatu", "unexpected", "ADJECTIVE"],
  ["originaal", "original", "NOUN", 211672],
  ["oskussõna", "technical term", "NOUN"],
  ["paragrahv", "section, paragraph", "NOUN"],
  ["paroodia", "parody", "NOUN"],
  ["piiritlema", "to delimit", "VERB"],
  ["piiritletud", "delimited", "ADJECTIVE"],
  ["piirkondlik", "regional", "ADJECTIVE"],
  ["pilge", "mockery", "NOUN"],
  ["pingutus", "effort", "NOUN"],
  ["poleemika", "polemic", "NOUN"],
  ["provokatiivne", "provocative", "ADJECTIVE"],
  ["provokatsioon", "provocation", "NOUN"],
  ["põlvkondlik", "generational", "ADJECTIVE"],
  ["riim", "rhyme", "NOUN", 227681],
  ["rõhk", "stress, accent", "NOUN"],
  ["rütm", "rhythm", "NOUN"],
  ["rütmika", "rhythmics", "NOUN"],
  ["sagedus", "frequency", "NOUN"],
  ["sarkasm", "sarcasm", "NOUN"],
  ["selgesti", "clearly", "ADVERB"],
  ["selgesõnaline", "explicit", "ADJECTIVE"],
  ["siduv", "binding", "ADJECTIVE"],
  ["sihtkeel", "target language", "NOUN"],
  ["spetsiifiline", "specific", "ADJECTIVE"],
  ["standardkeel", "standard language", "NOUN"],
  ["stiilitaju", "sense of style", "NOUN"],
  ["sujuv", "smooth", "ADJECTIVE"],
  ["sõnamäng", "wordplay, pun", "NOUN"],
  ["sõnastus", "wording", "NOUN"],
  ["sõnasõnaline", "literal", "ADJECTIVE"],
  ["sõnavalik", "word choice", "NOUN"],
  ["säte", "provision", "NOUN"],
  ["sätestama", "to stipulate", "VERB"],
  ["sümptom", "symptom", "NOUN"],
  ["süvenema", "to become absorbed", "VERB"],
  ["tabama", "to capture, to hit", "VERB"],
  ["tabavus", "aptness", "NOUN"],
  ["taluvus", "tolerance", "NOUN"],
  ["terav", "sharp", "ADJECTIVE"],
  ["teravmeelne", "witty", "ADJECTIVE"],
  ["teravmeelsus", "wit", "NOUN"],
  ["teravus", "sharpness, poignancy", "NOUN"],
  ["termin", "term", "NOUN"],
  ["terminoloogia", "terminology", "NOUN"],
  ["tihedus", "density", "NOUN"],
  ["toimetamine", "editing", "NOUN"],
  ["tunnus", "feature, characteristic", "NOUN"],
  ["tõlge", "translation", "NOUN"],
  ["tõlkeviga", "translation error", "NOUN"],
  ["tõlkija", "translator", "NOUN"],
  ["tühine", "void, negligible", "ADJECTIVE"],
  ["vabalt", "freely", "ADVERB"],
  ["vabatõlge", "free translation", "NOUN"],
  ["vaimukas", "witty", "ADJECTIVE"],
  ["valdamine", "command, mastery", "NOUN"],
  ["vallatu", "playful, mischievous", "ADJECTIVE"],
  ["vaste", "equivalent (in another language)", "NOUN"],
  ["vastunäidustus", "contraindication", "NOUN"],
  ["vihje", "hint", "NOUN"],
  ["vilumus", "proficiency, skill", "NOUN"],
  ["voolav", "flowing", "ADJECTIVE"],
  ["väljenduslaad", "manner of expression", "NOUN"],
  ["väljendusrikkus", "expressiveness", "NOUN"],
  ["õigusakt", "legal act", "NOUN"],
  ["õiguskord", "legal order", "NOUN"],
  ["ähmasus", "vagueness", "NOUN"],
  ["üheselt", "unambiguously", "ADVERB"],
  ["üldarusaadav", "generally comprehensible", "ADJECTIVE"],
  ["üldkeel", "general language", "NOUN"],
  ["üldsus", "the public", "NOUN"],
  ["ülevus", "loftiness", "NOUN"],
];
