/**
 * EVERY RUSSIAN OR UKRAINIAN LINE THE APP HOLDS, IN ONE FILE PER LANGUAGE, FOR
 * SOMEBODY FLUENT TO READ.
 *
 *   npx tsx scripts/export-translations.ts
 *
 * writes `docs/translations/ru.md` and `docs/translations/uk.md`. Each line is
 * printed beside the English it translates, grouped by the area of the app it
 * belongs to, with a box to tick, so a reviewer can work through a language
 * in one pass and say which lines they changed. Regenerate it after any
 * translation lands; the file is a reading of the tables, never edited by
 * hand, and a fix goes into the area file under `lib/copy/i18n/` it names.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { AREAS } from "@/lib/copy/i18n";
import { ENTRY_COPY } from "@/lib/copy/entryLocales";
import { COUNTED_CORE, MACHINE_NOTICE, MACHINE_NOTICE_EN, MACHINE_SHORT } from "@/lib/copy/locale";

type L = "ru" | "uk";
const NAMES: Record<L, string> = { ru: "Russian", uk: "Ukrainian" };

/** A line set off so Markdown cannot read it as anything but text. */
function quote(text: string): string {
  return text.replace(/\r?\n/g, " ").replace(/([\\`*_<>[\]#|])/g, "\\$1");
}

function areaFile(name: string): string {
  return name === "core" ? `lib/copy/i18n/${"{ru,uk}"}.ts` : `lib/copy/i18n/areas/${name}.ts`;
}

function strings(value: unknown, path: string, out: [string, string][]): void {
  if (typeof value === "string") out.push([path, value]);
  else if (Array.isArray(value)) value.forEach((v, i) => strings(v, `${path}[${i}]`, out));
  else if (value && typeof value === "object") {
    for (const [k, v] of Object.entries(value)) strings(v, path ? `${path}.${k}` : k, out);
  }
}

function build(locale: L): { text: string; lines: number } {
  const parts: string[] = [];
  let n = 0;
  const item = (english: string, translated: string, note?: string) => {
    n += 1;
    parts.push(`- [ ] **${n}.** ${quote(english)}${note ? ` _(${note})_` : ""}  \n  → ${quote(translated)}`);
  };

  parts.push(`# Kodukeel in ${NAMES[locale]}: every line to verify`, "");
  parts.push(
    "Generated by `npx tsx scripts/export-translations.ts` from the translation tables. Do not edit this file;",
    "fix a line in the file named under its heading and regenerate. Each entry is the English the app shows,",
    "then the translation. Tick a box when a line is right as it stands, and note the number of any line you change.",
    "",
    "Things that look odd and are deliberate:",
    "",
    "- `{name}` in braces is a value the app fills in (a number, a word, a date). It must stay, spelled exactly.",
    "- `{e1}`, `{e2}` stand for an Estonian word the app puts back unchanged; the table may not hold Estonian letters.",
    "- _(context: …)_ marks an English word that means two things on two screens and has a translation for each.",
    "- Estonian words (case names like seesütlev, forms like tuba) are never translated.",
    "",
  );

  parts.push("## The notice that the translation is unreviewed", "", "_lib/copy/locale.ts_", "");
  item(MACHINE_NOTICE_EN, MACHINE_NOTICE[locale]);
  item(MACHINE_NOTICE_EN, MACHINE_SHORT[locale], "short version");
  parts.push("");

  const entry = ENTRY_COPY[locale];
  const english: [string, string][] = [];
  strings(entry, "", english);
  parts.push("## The entry page for new visitors", "", "_lib/copy/entryLocales.ts (no English key: the line is shown beside its field name)_", "");
  for (const [path, value] of english) {
    if (path === "href" || path === "name" || path === "lang") continue;
    item(path, value, "field");
  }
  parts.push("");

  parts.push("## Counted words shared by every screen: one, few (2 to 4), many (5 and up)", "", "_lib/copy/locale.ts_", "");
  for (const [noun, forms] of Object.entries(COUNTED_CORE)) item(`${noun} / ${forms.en.join(", ")}`, forms[locale].join(", "), "1, 2, 5");
  parts.push("");

  for (const [name, area] of AREAS) {
    const rows = Object.entries(area[locale]);
    const counted = Object.entries(area.counted ?? {});
    if (rows.length === 0 && counted.length === 0) continue;
    parts.push(`## ${name} (${rows.length} lines)`, "", `_${areaFile(name)}_`, "");
    for (const [key, value] of rows) {
      const at = key.lastIndexOf("@");
      const hasContext = at > 0 && !key.slice(at + 1).includes(" ");
      if (hasContext) item(key.slice(0, at), value, `context: ${key.slice(at + 1)}`);
      else item(key, value);
    }
    if (counted.length > 0) {
      parts.push("", `### Counted words in ${name}: one, few (2 to 4), many (5 and up)`, "");
      for (const [noun, forms] of counted) item(`${noun} / ${forms.en.join(", ")}`, forms[locale].join(", "), "1, 2, 5");
    }
    parts.push("");
  }
  return { text: parts.join("\n") + "\n", lines: n };
}

mkdirSync("docs/translations", { recursive: true });
for (const locale of ["ru", "uk"] as const) {
  const { text, lines } = build(locale);
  writeFileSync(`docs/translations/${locale}.md`, text);
  console.log(`docs/translations/${locale}.md: ${lines} lines`);
}
