/**
 * WHAT EVERY SENTENCE THE DICTIONARY SHIPS MEANS, WORKED OUT ONCE AND WRITTEN
 * DOWN.
 *
 * A learner met `jah` under `Sina jah.` and asked what that was doing there.
 * The screens were given the English after that, and on a deployment with no
 * model key they still had nothing to show: Ekilex records no translation
 * against a usage on a reader key, so of the 12,172 sentences in
 * `prisma/data/expanded.json` and the 5,221 in `prisma/data/harvested.ts`,
 * **not one** carried an English line. A runtime ask fills that in one
 * sentence at a time for whoever has a key; the default deployment has none,
 * and a rule that only holds where somebody is paying for it is not the rule
 * this app said it had.
 *
 * So the English is built like the gloss is built: once, here, into a file
 * that ships in the repository and is read by the seed. Every deployment then
 * has it, keyless or not, on every screen, with no call and no wait.
 *
 * IT IS A FILE KEYED ON THE SENTENCE, NOT A COLUMN ON THE ENTRY, and that is
 * the whole shape of it. An English line is a fact about the sentence rather
 * than about the word it happens to be filed under: `lib/dict/borrow.ts` lends
 * one word's usages to another and they mean the same thing under both, so a
 * translation stored per entry would be stored twice and paid for twice.
 * Keeping it out of `harvested.ts` matters more: that file is generated by
 * `npm run harvest` from Ekilex and rewritten whole on every run, so an
 * English column in it would be deleted by the next harvest, silently, in the
 * one file nobody re-reads. Here the harvest can run as often as it likes.
 *
 * ADR-005 IS UNTOUCHED AND THIS IS THE DIRECTION IT ALLOWS. The model
 * translates *into* English and is never asked to produce Estonian: the
 * sentence came from a lexicographer and is not ours to rewrite, so the worst
 * a bad model can do here is gloss one clumsily. The question and the reading
 * of the answer are `lib/tutor/translate.ts`'s own, imported rather than
 * retyped, so a line built here and one a learner asks for at runtime are the
 * same translation of the same kind.
 *
 * A REFUSAL IS NEVER WRITTEN DOWN AS AN ANSWER, which is the lesson the seed
 * and the Ekilex harvest each learned expensively: a miss stored as a hit is a
 * wrong line nobody looks at again. An empty answer, the word UNKNOWN, an
 * essay, the Estonian handed straight back, or an answer still carrying
 * Estonian's own letters is dropped and reported, and the sentence is simply
 * left without an English line, which is exactly the state every sentence was
 * in before this existed.
 *
 * Resumable and cached: every answer is kept under `.translate-cache/`, so a
 * run that stops halfway costs nothing to finish and a re-run costs nothing at
 * all. Reports by default and writes with `--write`, like every other audit
 * here.
 *
 *   npm run translate:examples -- --limit 20     # a measured sample first
 *   npm run translate:examples -- --write
 */
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { HARVESTED } from "../prisma/data/harvested";
import { readSentenceTranslation, sentenceInstruction } from "../lib/tutor/translate";
import { estonianNotCopied } from "../lib/dict/copiedWords";
import { openWithFallback, resolveProviders } from "../lib/tutor/provider";
import { readExpanded } from "./lib/expandedFile";
import { isRefusedSentence } from "../lib/dict/refused";

/**
 * The expansion's own shape for a sentence, which is not the database's.
 *
 * `Lexeme.examples` is a JSON string column and `parseExamples` reads one;
 * `expanded.json` holds the same list already parsed, because it is a file
 * rather than a row. Reading it as a string found nothing and reported the
 * course's 5,221 sentences as the whole dictionary, which is a third of it.
 */
interface ExpandedRow { examples?: { et: string; en: string | null }[] | null }

const CACHE = ".translate-cache";
const OUT = "prisma/data/example-english.json";
/** The two characters `lib/copy/voice.ts` bans in anything a person reads. */
const DASH = /[\u2013\u2014]/;

/**
 * Whether an answer is worth writing down, over and above what the runtime
 * reading already refuses.
 *
 * Two things, and both are about this file being read by a learner rather than
 * by a machine. An answer carrying õ, ä, ö, ü, š or ž in a word its sentence did
 * not hold is Estonian that came back in English's place (a name or a quoted
 * word copied through is not, which is `estonianNotCopied`), and a line of Estonian under a heading
 * promising English is worse than no line at all. And a dash used as a clause
 * break is the loudest single tell that a sentence was generated, which is the
 * one thing `lib/copy/voice.ts` says no screen here may do; a dash the
 * lexicographer's own sentence has (a street number, a range of years) is the
 * sentence rather than the model, so it is only the invented one that is
 * refused. Measured over the first 5,615 answers: one em dash and two en
 * dashes the source did not have, which is three sentences out of 16,175 left
 * without a line and the voice rule true of every line that is there.
 */
function acceptable(en: string, et: string): boolean {
  if (estonianNotCopied(en, et)) return false;
  if (DASH.test(en) && !DASH.test(et)) return false;
  // And a quote mark it lost on the way. A model translating a sentence that
  // quotes somebody sometimes drops the opening one and keeps the closing one,
  // so `"Kurat!" vandus mees.` came back as `Damn!" the man swore.`, which is
  // a stray character sitting on a learner's screen. Only where the sentence
  // itself is balanced: seven of the nine odd counts in the file are odd in
  // the Estonian too, and those are faithful.
  return quotes(en) % 2 === 0 || quotes(et) % 2 === 1;
}

/** How many quote marks a line carries, in either language's quoting style. */
function quotes(text: string): number {
  return (text.match(/["\u201c\u201d\u201e]/g) ?? []).length;
}

const args = process.argv.slice(2);
const write = args.includes("--write");
const limitAt = args.indexOf("--limit");
const limit = limitAt >= 0 ? Number(args[limitAt + 1]) : Infinity;
/**
 * How many questions are in the air at once.
 *
 * Sixteen thousand sentences one after another is three hours, which is three
 * hours in which a key can rate-limit, a laptop can sleep and the whole run
 * can be lost; the cache makes a second run free, but the first one still has
 * to finish. Eight is chosen against the provider rather than against the
 * machine: it is well inside a free Gemini key's own per-minute allowance, and
 * the chain walks past a link having a bad minute on its own.
 */
const CONCURRENCY = Number(args[args.indexOf("--concurrency") + 1]) || 8;

/**
 * Every distinct sentence the seed will write, in the order a reader meets them.
 *
 * AND NOT ONE A PERSON HAS REFUSED, which is the door this run is. The
 * refusals in `lib/dict/refused.ts` reach the column, the seed, the harvest
 * and every audit, and this script reads `HARVESTED` and the expansion
 * straight off disk rather than through `scripts/lib/dictionary.ts`, so it
 * was outside all of that: a run would have paid a model for a line no screen
 * may draw and written it back into `prisma/data/example-english.json`, which
 * is the one file the refusal had just been taken out of. The unit suite
 * catches the result and only after the call is bought and the file rewritten,
 * which is the wrong end to find it from.
 */
function shippedSentences(): string[] {
  const seen = new Set<string>();
  // The course first: these are the sentences a lesson and the learn ladder
  // put in front of somebody in their first fortnight.
  for (const word of HARVESTED) {
    for (const et of word.usages) if (!isRefusedSentence(et)) seen.add(et);
  }
  for (const row of readExpanded<ExpandedRow>()) {
    for (const example of row.examples ?? []) {
      if (example.et && !isRefusedSentence(example.et)) seen.add(example.et);
    }
  }
  return [...seen];
}

const cacheName = (sentence: string) =>
  `${createHash("sha1").update(sentence).digest("hex")}.json`;

async function cached(sentence: string): Promise<string | null | undefined> {
  try {
    const raw = await readFile(join(CACHE, cacheName(sentence)), "utf8");
    return JSON.parse(raw).en ?? null;
  } catch {
    return undefined;
  }
}

async function remember(sentence: string, en: string | null): Promise<void> {
  await writeFile(join(CACHE, cacheName(sentence)), JSON.stringify({ et: sentence, en }), "utf8");
}

async function askModel(sentence: string): Promise<string | null> {
  const chain = resolveProviders({ purpose: "grader" });
  if (chain.length === 0) throw new Error("No provider configured. Set GEMINI_API_KEY or GROQ_API_KEY.");

  const open = await openWithFallback(
    chain,
    "You translate Estonian into English. You never write Estonian.",
    [{ role: "user", content: sentenceInstruction(sentence) }],
  );
  let text = "";
  for await (const chunk of open.chunks) {
    text += chunk;
    if (text.length > 400) break;
  }
  const en = readSentenceTranslation(text, sentence);
  return en && acceptable(en, sentence) ? en : null;
}

async function main() {
  await mkdir(CACHE, { recursive: true });

  const existing: Record<string, string> = await readFile(OUT, "utf8")
    .then((raw) => JSON.parse(raw))
    .catch(() => ({}));

  const sentences = shippedSentences();
  const wanted = sentences.filter((et) => !existing[et]);
  console.log(
    `${sentences.length} sentences ship in the dictionary, ` +
    `${sentences.length - wanted.length} already have English, ${wanted.length} to ask about.`,
  );

  const out: Record<string, string> = { ...existing };
  let asked = 0;
  let fromCache = 0;
  let refused = 0;
  let stopped = false;
  const started = Date.now();

  /*
    A queue rather than a loop, so the cache is read and the model asked with
    `CONCURRENCY` in the air. `next` is the shared cursor: every worker takes
    the sentence at it and moves it on, which is what keeps `--limit` a limit
    on questions asked rather than on questions asked per worker.
  */
  let next = 0;
  const worker = async () => {
    while (!stopped) {
      const et = wanted[next++];
      if (et === undefined) return;

      const held = await cached(et);
      if (held !== undefined) {
        // Asked against `acceptable` here too, not only when the answer was
        // fresh: the cache is every answer a provider has ever given, and a
        // rule added after a run has to reach the lines that run wrote.
        fromCache += 1;
        if (held && acceptable(held, et)) out[et] = held;
        else refused += 1;
        continue;
      }

      if (asked >= limit) return;
      asked += 1;

      let en: string | null = null;
      try {
        en = await askModel(et);
      } catch (error) {
        // One worker hitting a wall stops the run rather than the other seven
        // carrying on into the same wall: a rejected key and a spent balance
        // are both answers about the whole chain, not about this sentence.
        console.error(`\n${et}\n  ${(error as Error).message}`);
        stopped = true;
        return;
      }
      await remember(et, en);
      if (en) out[et] = en;
      else refused += 1;

      if (asked % 100 === 0) {
        const perSecond = asked / ((Date.now() - started) / 1000);
        const left = Math.min(wanted.length, limit) - asked;
        process.stdout.write(
          `\r  ${asked} asked, ${refused} refused, ${perSecond.toFixed(1)}/s, ` +
          `about ${Math.round(left / perSecond / 60)} min left   `,
        );
      }
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  const covered = sentences.filter((et) => out[et]).length;
  console.log(
    `\n${asked} asked, ${fromCache} read from the cache, ${refused} refused. ` +
    `${covered} of ${sentences.length} sentences now carry English ` +
    `(${Math.round((covered / sentences.length) * 100)}%).`,
  );

  const sample = Object.entries(out).slice(0, 5);
  for (const [et, en] of sample) console.log(`  ${et}\n    ${en}`);

  if (!write) {
    console.log(`\nNothing written. Re-run with --write to update ${OUT}.`);
    return;
  }
  // One key per line, like the built dictionary, because the diff is the only
  // way anybody reviews a file this size and a generator that reformats on the
  // way past hides every real change inside a rewrite of everything.
  const keys = Object.keys(out).sort();
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])}`).join(",\n");
  await writeFile(OUT, `{\n${body}\n}\n`, "utf8");
  console.log(`\nWrote ${keys.length} translations to ${OUT}.`);
}

void main();
