/**
 * THE WRITTEN SENTENCES, A1 AND A2, BY UNIT IN TEACHING ORDER.
 *
 * Read `lib/dict/authored.ts` before adding a row: what a row may be, what the
 * machine checks, and what only a person can. `npm run check:authored` prints
 * every row that breaks a rule, with the reason.
 *
 * Each row is [the word it is filed under, the Estonian, the English]. Every
 * word of the Estonian is one the course has taught by the evening the word
 * arrives, so a sentence here may only use what comes before it in this file
 * or on the same evening.
 */
import type { AuthoredRow } from "@/lib/dict/authored";

export const AUTHORED_ROWS: readonly AuthoredRow[] = [
  // vastused
  ["jah", "Jah, muidugi!", "Yes, of course!"],
  ["muidugi", "Muidugi, aitäh!", "Of course, thank you!"],
  ["aitäh", "Jah, aitäh!", "Yes, thank you!"],
  ["ei", "Ei, aitäh.", "No, thank you."],
  // asesonad
  ["mina", "Mina? Jah, mina.", "Me? Yes, me."],
  ["sina", "Sina? Ei, tema.", "You? No, him."],
  ["tema", "Tema? Jah, tema.", "Her? Yes, her."],
  ["meie", "Meie? Ei, teie.", "Us? No, you."],
  ["nemad", "Nemad? Ei, meie.", "Them? No, us."],
  // esimesed-verbid
  ["olema", "See olen mina.", "That is me."],
  ["see", "See on tema.", "This is her."],
  ["too", "Too on tema, see olen mina.", "That one over there is him, and this is me."],
  ["elama", "Mina elan, sina elad.", "I live, you live."],
  ["õppima", "Mina õpin, tema ei õpi.", "I study, he does not."],
  ["rääkima", "Ma tahan rääkida.", "I want to talk."],
  ["töötama", "Ma töötan, tema õpib.", "I work, she studies."],
  ["tahtma", "Ma tahan õppida.", "I want to learn."],
  ["minema", "Ma tahan minna.", "I want to go."],
  ["tulema", "Tema tuleb, mina lähen.", "She is coming, I am going."],
  // vaikesed-sonad
  ["ja", "Ma töötan ja õpin.", "I work and study."],
  ["aga", "Ta õpib, aga ei tööta.", "She studies but does not work."],
  ["ka", "Ka mina õpin.", "I am studying too."],
  ["väga", "Ma tahan väga minna.", "I really want to go."],
  ["hästi", "Te räägite hästi.", "You speak well."],
  ["siin", "Ma elan siin.", "I live here."],
  ["siin", "Tema elab ka siin.", "She lives here too."],
  ["nüüd", "Nüüd ma lähen.", "Now I am going."],
  ["täna", "Täna ma töötan.", "Today I am working."],
  ["veel", "Ta on veel siin.", "She is still here."],
  ["ainult", "Ta tahab ainult õppida.", "He only wants to study."],
  // kusisonad
  ["kes", "Kes sa oled?", "Who are you?"],
  ["mis", "Mis see on?", "What is this?"],
  ["kus", "Kus sa töötad?", "Where do you work?"],
  ["kuhu", "Kuhu te lähete?", "Where are you going?"],
  ["kust", "Kust sa tuled?", "Where are you coming from?"],
  ["millal", "Millal sa tuled?", "When are you coming?"],
  ["miks", "Miks sa eesti keelt õpid?", "Why are you learning Estonian?"],
  ["kuidas", "Kuidas sul läheb?", "How are you?"],
  ["kas", "Kas sa räägid eesti keelt?", "Do you speak Estonian?"],
  ["milline", "Milline see on?", "What is it like?"],
  ["kumb", "Kumb on sinu?", "Which of the two is yours?"],
  ["palju", "Ta räägib palju.", "She talks a lot."],
  ["kui", "Ta räägib, kui ta tahab.", "He talks when he wants to."],
  // inimesed
  ["inimene", "Ta on hea inimene.", "She is a good person."],
  ["naine", "See on minu naine.", "This is my wife."],
  ["mees", "Too mees elab siin.", "That man lives here."],
  ["laps", "Laps tahab minna.", "The child wants to go."],
  ["sõber", "Ta on minu sõber.", "He is my friend."],
  ["ema", "Minu ema elab siin.", "My mother lives here."],
  ["isa", "Isa töötab täna.", "Dad is working today."],
  ["pere", "Meie pere elab siin.", "Our family lives here."],
  ["vend", "Mu vend õpib ka.", "My brother is studying too."],
  ["õde", "Minu õde räägib väga hästi.", "My sister speaks very well."],
  ["tütar", "Meie tütar õpib.", "Our daughter is studying."],
  ["poeg", "Nende poeg töötab.", "Their son works."],
  ["vanaema", "Vanaema tuleb täna.", "Grandma is coming today."],
  ["vanaisa", "Vanaisa elab ka siin.", "Grandpa lives here too."],
  ["nimi", "Mis tema nimi on?", "What is her name?"],
  ["õpetaja", "Ta on õpetaja.", "She is a teacher."],
  ["õpilane", "Mina olen õpilane.", "I am a pupil."],
  ["arst", "Tema isa on arst.", "His father is a doctor."],
  // tutvumine
  ["eesnimi", "Mis su eesnimi on?", "What is your first name?"],
  ["perekonnanimi", "Mis on teie perekonnanimi?", "What is your surname?"],
  ["aadress", "Mis on sinu aadress?", "What is your address?"],
  ["elukoht", "Mis on teie elukoht?", "What is your place of residence?"],
  ["sünnikoht", "Mis on teie sünnikoht?", "What is your place of birth?"],
  ["sünniaeg", "Mis on teie sünniaeg?", "What is your date of birth?"],
  ["tutvuma", "Ma tahan temaga tutvuda.", "I want to get to know him."],
  ["tutvustama", "Ta tutvustab mind.", "She is introducing me."],
  ["tuttav", "Ta on minu tuttav.", "He is an acquaintance of mine."],
  ["kolleeg", "See on minu kolleeg.", "This is my colleague."],
  ["sõbranna", "Minu sõbranna elab siin.", "My (female) friend lives here."],
  ["hobi", "Mis on sinu hobi?", "What is your hobby?"],
  ["huvi", "Mul on huvi eesti keelt õppida.", "I am interested in learning Estonian."],
  ["meeldiv", "Teie õde on väga meeldiv.", "Your sister is very pleasant."],
  ["abielus", "Kas te olete abielus?", "Are you married?"],
  ["vallaline", "Ma olen vallaline.", "I am single."],
  // arvud
  ["number", "Mis on sinu number?", "What is your number?"],
  ["üks", "Mul on üks vend.", "I have one brother."],
  ["kaks", "Mul on kaks õde.", "I have two sisters."],
  ["kolm", "Meil on kolm last.", "We have three children."],
  ["neli", "Täna tuleb neli sõpra.", "Four friends are coming today."],
  ["viis", "Mul on viis sõpra.", "I have five friends."],
  ["kuus", "Siin elab kuus inimest.", "Six people live here."],
  ["seitse", "Meie peres on seitse inimest.", "There are seven people in our family."],
  ["kaheksa", "Kaheksa last õpib siin.", "Eight children study here."],
  ["üheksa", "Üheksa õpilast tuleb täna.", "Nine students are coming today."],
  ["kümme", "Kümme inimest töötab siin.", "Ten people work here."],
  ["üksteist", "Ta on üksteist.", "She is eleven."],
  ["kaksteist", "Minu poeg on kaksteist.", "My son is twelve."],
  ["kakskümmend", "Mu õde on kakskümmend.", "My sister is twenty."],
  ["kolmkümmend", "Ma olen kolmkümmend.", "I am thirty."],
  ["vanus", "Mis on teie vanus?", "What is your age?"],
  ["sada", "Siin töötab sada inimest.", "A hundred people work here."],
  ["tuhat", "Siin elab tuhat inimest.", "A thousand people live here."],
  ["esimene", "Ta on minu esimene õpetaja.", "She is my first teacher."],
  ["teine", "Mu teine vend elab siin.", "My other brother lives here."],
  ["kolmas", "Ta on meie kolmas laps.", "He is our third child."],
  ["neljas", "Täna on neljas.", "Today is the fourth."],
  ["viies", "Mina olen viies.", "I am fifth."],
  // kodu
  ["kodu", "Minu kodu on siin.", "My home is here."],
  ["maja", "Meie maja on siin.", "Our house is here."],
  ["tuba", "See on minu tuba.", "This is my room."],
  ["köök", "Kus on köök?", "Where is the kitchen?"],
  ["korter", "Me elame korteris.", "We live in a flat."],
  ["uks", "Kus on uks?", "Where is the door?"],
  ["aken", "Toas on üks aken.", "There is one window in the room."],
  ["laud", "Köögis on laud.", "There is a table in the kitchen."],
  ["tool", "Toas on kaks tooli.", "There are two chairs in the room."],
  ["voodi", "Voodi on toas.", "The bed is in the room."],
  ["raamat", "Mis raamat see on?", "What book is that?"],
  ["arvuti", "Kas see on sinu arvuti?", "Is this your computer?"],
  ["telefon", "Kus on minu telefon?", "Where is my phone?"],
  ["võti", "Kus on võti?", "Where is the key?"],
  ["klaas", "Laual on klaas.", "There is a glass on the table."],
  ["tass", "Laual on kaks tassi.", "There are two cups on the table."],
  ["pilt", "Seinal on pilt.", "There is a picture on the wall."],
  ["sein", "Toas on neli seina.", "The room has four walls."],
  ["põrand", "Raamat on põrandal.", "The book is on the floor."],
  ["korrus", "Ma elan teisel korrusel.", "I live on the second floor."],
  // pohiverbid
  ["tegema", "Mida sa teed?", "What are you doing?"],
  ["saama", "Ma ei saa tulla.", "I cannot come."],
  ["pidama", "Ma pean täna töötama.", "I have to work today."],
  ["sööma", "Laps sööb köögis.", "The child is eating in the kitchen."],
  ["jooma", "Mida sa jood?", "What are you drinking?"],
  ["tooma", "Palun too mulle tass.", "Please bring me a cup."],
  ["viima", "Isa viib lapse koju.", "Dad is taking the child home."],
  ["andma", "Anna mulle raamat, palun.", "Give me the book, please."],
  ["võtma", "Võta üks tass.", "Take a cup."],
  ["panema", "Pane tass lauale.", "Put the cup on the table."],
  ["jääma", "Ma jään koju.", "I am staying home."],
  // sook-ja-jook
  ["toit", "Toit on laual.", "The food is on the table."],
  ["söök", "Söök on köögis.", "The meal is in the kitchen."],
  ["jook", "Mis jook see on?", "What drink is this?"],
  ["leib", "Ma söön leiba.", "I am eating bread."],
  ["sai", "Laps tahab saia.", "The child wants some white bread."],
  ["kohv", "Kas sa tahad kohvi?", "Do you want coffee?"],
  ["vesi", "Palun anna mulle vett.", "Please give me some water."],
  ["piim", "Laps joob piima.", "The child is drinking milk."],
  ["mahl", "Mul on klaas mahla.", "I have a glass of juice."],
  ["liha", "Ma ei söö liha.", "I do not eat meat."],
  ["kala", "Täna sööme kala.", "Today we are eating fish."],
  ["õun", "Laual on kaks õuna.", "There are two apples on the table."],
  ["kartul", "Me sööme kartulit.", "We are eating potatoes."],
  ["juust", "Ma võtan leiba ja juustu.", "I will take bread and cheese."],
  ["muna", "Isa sööb muna.", "Dad is eating an egg."],
  ["või", "Pane leivale võid.", "Put some butter on the bread."],
  ["sool", "Kus on sool?", "Where is the salt?"],
  ["suhkur", "Kas sa võtad suhkrut?", "Do you take sugar?"],
  ["supp", "Supp on väga hea.", "The soup is very good."],
  // aeg
  ["aeg", "Mul ei ole aega.", "I do not have time."],
  ["päev", "Täna on hea päev.", "Today is a good day."],
  ["öö", "Head ööd!", "Good night!"],
  ["hommik", "Täna hommikul ma töötan.", "This morning I am working."],
  ["õhtu", "Õhtul ma olen kodus.", "In the evening I am at home."],
  ["nädal", "Nädalas on seitse päeva.", "A week has seven days."],
  ["kuu", "Ma olen siin kaks kuud.", "I have been here for two months."],
  ["aasta", "Aastas on kaksteist kuud.", "A year has twelve months."],
  ["tund", "Ma töötan kaheksa tundi.", "I work eight hours."],
  ["minut", "Üks minut, palun!", "One minute, please!"],
  ["kell", "Kell on kaks.", "It is two o'clock."],
  ["esmaspäev", "Esmaspäeval ma töötan.", "On Monday I work."],
  ["teisipäev", "Teisipäeval ma õpin eesti keelt.", "On Tuesday I study Estonian."],
  ["kolmapäev", "Kolmapäeval tuleb vanaema.", "Grandma comes on Wednesday."],
  ["neljapäev", "Neljapäeval me sööme kala.", "On Thursday we eat fish."],
  ["reede", "Reedel ma ei tööta.", "On Friday I do not work."],
  ["laupäev", "Laupäeval me oleme kodus.", "On Saturday we are at home."],
  ["pühapäev", "Pühapäeval tulevad sõbrad.", "Friends come on Sunday."],
  ["pool", "Kell on pool kaks.", "It is half past one."],
  ["hetk", "Üks hetk, palun!", "One moment, please!"],
  // iga-paev
  ["teadma", "Ma tean, kus ta elab.", "I know where she lives."],
  ["tundma", "Kas sa tunned teda?", "Do you know him?"],
  ["nägema", "Ma näen sind.", "I can see you."],
  ["kuulma", "Kas sa kuuled mind?", "Can you hear me?"],
  ["ütlema", "Mida ta ütleb?", "What is he saying?"],
  ["küsima", "Ta küsib, kus sa elad.", "She is asking where you live."],
  ["vastama", "Palun vasta mulle.", "Please answer me."],
  ["lugema", "Õhtul ma loen.", "In the evening I read."],
  ["kirjutama", "Laps kirjutab hästi.", "The child writes well."],
  ["magama", "Laps magab toas.", "The child is sleeping in the room."],
  ["ärkama", "Ma ärkan kell seitse.", "I wake up at seven."],
  ["istuma", "Istu, palun!", "Sit down, please!"],
  ["seisma", "Ta seisab köögis.", "She is standing in the kitchen."],
  // omadussonad
  ["suur", "Meie maja on suur.", "Our house is big."],
  ["väike", "Minu tuba on väike.", "My room is small."],
  ["hea", "See on hea raamat.", "This is a good book."],
  ["halb", "Täna on halb päev.", "Today is a bad day."],
  ["uus", "Mul on uus telefon.", "I have a new phone."],
  ["vana", "See maja on vana.", "This house is old."],
  ["noor", "Meie õpetaja on noor.", "Our teacher is young."],
  ["pikk", "Mu vend on pikk.", "My brother is tall."],
  ["lühike", "See raamat on lühike.", "This book is short."],
  ["kiire", "Mul on kiire.", "I am in a hurry."],
  ["aeglane", "Minu arvuti on aeglane.", "My computer is slow."],
  ["kallis", "See telefon on kallis.", "This phone is expensive."],
  ["odav", "Leib on odav.", "Bread is cheap."],
  ["ilus", "Sinu tuba on ilus.", "Your room is beautiful."],
  ["tore", "See on tore!", "That is great!"],
  ["raske", "Eesti keelt on raske õppida.", "Estonian is hard to learn."],
  ["kerge", "See tool on kerge.", "This chair is light."],
  ["lihtne", "See on väga lihtne.", "This is very simple."],
  ["valmis", "Söök on valmis.", "The food is ready."],
  ["keeruline", "See on keeruline.", "It is complicated."],
  // varvid
  ["värv", "Mis värv see on?", "What colour is it?"],
  ["punane", "Minu telefon on punane.", "My phone is red."],
  ["sinine", "Uks on sinine.", "The door is blue."],
  ["roheline", "Roheline tass on minu.", "The green cup is mine."],
  ["kollane", "Köök on kollane.", "The kitchen is yellow."],
  ["must", "Ma joon musta kohvi.", "I drink black coffee."],
  ["valge", "Seinad on valged.", "The walls are white."],
  ["hall", "Täna on hall päev.", "Today is a grey day."],
  ["pruun", "Laud on pruun.", "The table is brown."],
  ["roosa", "Tütre tuba on roosa.", "The daughter's room is pink."],
  ["lilla", "Mul on lilla tass.", "I have a purple cup."],
  ["hele", "Tuba on hele.", "The room is bright."],
  ["tume", "Tume leib on hea.", "Dark bread is good."],
  // riided
  ["särk", "Mul on uus särk.", "I have a new shirt."],
  ["kleit", "See kleit on väga ilus.", "This dress is very pretty."],
  ["seelik", "Tal on punane seelik.", "She has a red skirt."],
  ["king", "Kus on minu kingad?", "Where are my shoes?"],
  ["sokk", "Kus on mu sokid?", "Where are my socks?"],
  ["müts", "Mul on must müts.", "I have a black hat."],
  ["mantel", "Minu mantel on vana.", "My coat is old."],
  ["jope", "See jope on odav.", "This jacket is cheap."],
  ["sall", "Kas see sall on sinu?", "Is this scarf yours?"],
  ["kinnas", "Kus on minu kindad?", "Where are my gloves?"],
  ["taskurätik", "Kas sul on taskurätik?", "Do you have a handkerchief?"],
  ["vöö", "See vöö on pruun.", "This belt is brown."],
  ["riie", "See riie on hea.", "This fabric is good."],
  ["suurus", "Mis suurus see on?", "What size is this?"],
  ["püksid", "Mul on uued püksid.", "I have new trousers."],
  ["kampsun", "Mul on sinine kampsun.", "I have a blue sweater."],
  ["saabas", "Mul on uued saapad.", "I have new boots."],
  // ilm
  ["ilm", "Mis ilm täna on?", "What is the weather like today?"],
  ["päike", "Ma näen päikest.", "I can see the sun."],
  ["vihm", "Täna tuleb vihma.", "It is going to rain today."],
  ["lumi", "Täna tuleb lund.", "It is going to snow today."],
  ["tuul", "Täna on suur tuul.", "There is a strong wind today."],
  ["pilv", "Täna on palju pilvi.", "There are a lot of clouds today."],
  ["torm", "Täna on torm.", "There is a storm today."],
  ["jää", "Ma tahan vett ja jääd.", "I want water and ice."],
  ["udu", "Täna hommikul on udu.", "There is fog this morning."],
  ["kraad", "Täna on kümme kraadi.", "It is ten degrees today."],
  ["külm", "Mul on külm.", "I am cold."],
  ["soe", "Täna on soe.", "It is warm today."],
  ["kuum", "Supp on kuum.", "The soup is hot."],
  ["märg", "Mu mantel on märg.", "My coat is wet."],
  ["kuiv", "Leib on kuiv.", "The bread is dry."],
  // suured-arvud
  ["kolmteist", "Ta on kolmteist.", "He is thirteen."],
  ["neliteist", "Mu tütar on neliteist.", "My daughter is fourteen."],
  ["viisteist", "Kell on viisteist.", "It is three in the afternoon."],
  ["kuusteist", "Meil on kuusteist tooli.", "We have sixteen chairs."],
  ["seitseteist", "Täna on seitseteist kraadi.", "It is seventeen degrees today."],
  ["kaheksateist", "Mu vend on kaheksateist.", "My brother is eighteen."],
  ["üheksateist", "Kell on üheksateist.", "It is seven in the evening."],
  ["nelikümmend", "Ma olen nelikümmend.", "I am forty."],
  ["viiskümmend", "Isa on viiskümmend.", "Dad is fifty."],
  ["kuuskümmend", "Tunnis on kuuskümmend minutit.", "An hour has sixty minutes."],
  ["seitsekümmend", "Vanaema on seitsekümmend.", "Grandma is seventy."],
  ["kaheksakümmend", "Vanaisa on kaheksakümmend.", "Grandpa is eighty."],
  ["üheksakümmend", "Siin elab üheksakümmend inimest.", "Ninety people live here."],
  ["kuues", "Ma elan kuuendal korrusel.", "I live on the sixth floor."],
  ["seitsmes", "Ta elab seitsmendal korrusel.", "She lives on the seventh floor."],
  ["kaheksas", "Ta elab kaheksandal korrusel.", "He lives on the eighth floor."],
  ["üheksas", "Täna on üheksas.", "Today is the ninth."],
  ["kümnes", "Ta on kümnes õpilane.", "She is the tenth student."],
  ["miljon", "Tal on miljon sõpra.", "She has a million friends."],
  // ostmine
  ["pood", "Ma lähen poodi.", "I am going to the shop."],
  ["turg", "Laupäeval me läheme turule.", "On Saturday we are going to the market."],
  ["raha", "Mul ei ole raha.", "I do not have any money."],
  ["sularaha", "Kas teil on sularaha?", "Do you have cash?"],
  ["hind", "Hind on hea.", "The price is good."],
  ["pilet", "Mul on kaks piletit.", "I have two tickets."],
  ["ostma", "Ma tahan osta leiba.", "I want to buy bread."],
  ["müüma", "Ta müüb turul kala.", "She sells fish at the market."],
  ["maksma", "Ma maksan sularahas.", "I will pay in cash."],
  ["linn", "See linn on väga ilus.", "This town is very beautiful."],
  ["tänav", "Ma elan sellel tänaval.", "I live on this street."],
  ["tee", "Kas sa tahad teed?", "Do you want tea?"],
  ["buss", "Millal buss tuleb?", "When is the bus coming?"],
  ["rong", "Rong on kiire.", "The train is fast."],
  ["auto", "Meil on uus auto.", "We have a new car."],
  ["jaam", "Kus on jaam?", "Where is the station?"],
  ["park", "Park on väga ilus.", "The park is very beautiful."],
  ["euro", "See maksab kaks eurot.", "It costs two euros."],
  // kus-ja-kuhu
  ["koht", "See on hea koht.", "This is a good place."],
  ["kesklinn", "Ma töötan kesklinnas.", "I work in the city centre."],
  ["väljak", "Väljakul on palju inimesi.", "There are a lot of people on the square."],
  ["sild", "See sild on väga vana.", "This bridge is very old."],
  ["nurk", "Laud on nurgas.", "The table is in the corner."],
  ["kool", "Laps on koolis.", "The child is at school."],
  ["töö", "Ma lähen tööle.", "I am going to work."],
  ["haigla", "Isa töötab haiglas.", "Dad works at the hospital."],
  ["kirik", "Pühapäeval me läheme kirikusse.", "On Sunday we go to church."],
  ["rand", "Täna me läheme randa.", "Today we are going to the beach."],
  ["ülikool", "Mu õde õpib ülikoolis.", "My sister studies at university."],
  ["kohvik", "Me joome kohvikus kohvi.", "We are drinking coffee in the café."],
  ["restoran", "See restoran on kallis.", "This restaurant is expensive."],
  ["hotell", "Kus on hotell?", "Where is the hotel?"],
  ["vasakul", "Pood on vasakul.", "The shop is on the left."],
  ["paremal", "Kool on paremal.", "The school is on the right."],
  ["otse", "Mine otse!", "Go straight on!"],
  ["edasi", "Ma lähen edasi.", "I am going on."],
  ["tagasi", "Ta tuleb täna tagasi.", "She is coming back today."],
  ["asuma", "Kus asub jaam?", "Where is the station?"],
  ["mujal", "Ta elab mujal.", "He lives somewhere else."],
  ["siia", "Palun tule siia.", "Please come here."],
  // transport
  ["sõitma", "Ma sõidan bussiga.", "I go by bus."],
  ["tramm", "Me sõidame trammiga.", "We go by tram."],
  ["troll", "Kas see troll läheb kesklinna?", "Does this trolleybus go to the city centre?"],
  ["takso", "Ma võtan takso.", "I will take a taxi."],
  ["peatus", "Peatus on paremal.", "The stop is on the right."],
  ["bussijaam", "Bussijaam on kesklinnas.", "The bus station is in the city centre."],
  ["lennujaam", "Ma sõidan lennujaama.", "I am driving to the airport."],
  ["sadam", "Isa töötab sadamas.", "Dad works at the port."],
  ["jalgratas", "Ma sõidan jalgrattaga.", "I ride a bike."],
  ["sõit", "Head sõitu!", "Have a good trip!"],
  ["väljuma", "Ma väljun siin.", "I am getting off here."],
  ["sisenema", "Me siseneme majja.", "We go into the house."],
  ["väljapääs", "Kus on väljapääs?", "Where is the exit?"],
  ["sõiduplaan", "Kas sul on sõiduplaan?", "Do you have the timetable?"],
  ["hilinema", "Buss hilineb.", "The bus is late."],
  ["ootama", "Ma ootan bussi.", "I am waiting for the bus."],
  ["foor", "Foor on punane.", "The traffic light is red."],
  ["kõnnitee", "Laps on kõnniteel.", "The child is on the pavement."],
  ["jalgsi", "Ma lähen jalgsi.", "I am going on foot."],
  ["ühistransport", "Ma sõidan ühistranspordiga.", "I use public transport."],
  // umbmaarased
  ["ise", "Ma teen seda ise.", "I will do it myself."],
  ["keegi", "Keegi tuleb.", "Someone is coming."],
  ["kõik", "Kõik on hästi.", "Everything is fine."],
  ["igaüks", "Igaüks teab seda.", "Everyone knows that."],
  ["mõni", "Mõni päev on raske.", "Some days are hard."],
  ["iga", "Ma ärkan iga päev kell seitse.", "I wake up at seven every day."],
  ["oma", "Ma elan oma korteris.", "I live in my own flat."],
  // millal
  ["homme", "Homme ma ei tööta.", "Tomorrow I am not working."],
  ["eile", "Eile oli külm.", "It was cold yesterday."],
  ["ülehomme", "Ülehomme tuleb vanaema.", "Grandma is coming the day after tomorrow."],
  ["üleeile", "Üleeile oli torm.", "There was a storm the day before yesterday."],
  ["praegu", "Praegu ma olen tööl.", "Right now I am at work."],
  ["kohe", "Ma tulen kohe.", "I am coming right away."],
  ["varsti", "Buss tuleb varsti.", "The bus is coming soon."],
  ["hiljem", "Räägime hiljem.", "Let's talk later."],
  ["alati", "Ta räägib alati palju.", "He always talks a lot."],
  ["tihti", "Ma söön tihti kala.", "I often eat fish."],
  ["sageli", "Vihma tuleb sageli.", "It often rains."],
  ["harva", "Ma joon harva kohvi.", "I rarely drink coffee."],
  ["mõnikord", "Mõnikord ma töötan kodus.", "Sometimes I work at home."],
  ["kunagi", "Ma ei söö kunagi liha.", "I never eat meat."],
  ["juba", "Ma olen juba kodus.", "I am already home."],
  ["jälle", "Täna tuleb jälle vihma.", "It is raining again today."],
  ["ammu", "Ma elan siin juba ammu.", "I have lived here for a long time."],
  ["vanasti", "Vanasti elas siin palju inimesi.", "In the old days many people lived here."],
  // kohasonad
  ["peal", "Raamat on laua peal.", "The book is on the table."],
  ["all", "Kingad on voodi all.", "The shoes are under the bed."],
  ["ees", "Auto on maja ees.", "The car is in front of the house."],
  ["taga", "Park on maja taga.", "The park is behind the house."],
  ["kõrval", "Kool on kiriku kõrval.", "The school is next to the church."],
  ["juures", "Ma olen arsti juures.", "I am at the doctor's."],
  ["vahel", "Laud on kahe tooli vahel.", "The table is between two chairs."],
  ["sees", "Mis selle sees on?", "What is inside it?"],
  ["keskel", "Laud on toa keskel.", "The table is in the middle of the room."],
  ["vastas", "Pood on meie maja vastas.", "The shop is opposite our house."],
  ["ümber", "Maja ümber on park.", "There is a park around the house."],
  ["üle", "Mine üle tee.", "Cross the road."],
  ["läbi", "Me läheme pargi läbi.", "We are going through the park."],
  ["koos", "Me sööme koos.", "We eat together."],
  ["ilma", "Ma joon kohvi ilma suhkruta.", "I drink coffee without sugar."],
  ["enne", "Tule enne kella kolme.", "Come before three o'clock."],
  ["pärast", "Tule pärast tööd.", "Come after work."],
  ["lähedal", "Pood on väga lähedal.", "The shop is very close."],
  ["kohal", "Pilt on laua kohal.", "The picture is above the table."],
  ["mööda", "Mine mööda tänavat.", "Go along the street."],
  ["alates", "Alates esmaspäevast töötan ma.", "From Monday I am working."],
  ["kaasas", "Kas sul on raha kaasas?", "Do you have money on you?"],
  ["vastu", "Ma olen vastu.", "I am against it."],
  // sidesonad
  ["ning", "Ma söön leiba ning juustu.", "I am eating bread and cheese."],
  ["vaid", "Ma ei joo kohvi, vaid teed.", "I do not drink coffee, but tea."],
  ["et", "Ma tean, et ta tuleb.", "I know that she is coming."],
  ["sest", "Ma jään koju, sest mul on külm.", "I am staying home because I am cold."],
  ["kuna", "Kuna täna tuleb vihma, jään ma koju.", "Since it is raining today, I am staying home."],
  ["ega", "Ma ei söö liha ega kala.", "I eat neither meat nor fish."],
  ["või", "Kas sa tahad kohvi või teed?", "Do you want coffee or tea?"],
  ["ehk", "Ehk ta tuleb homme.", "Perhaps he will come tomorrow."],
  ["kuni", "Ma ootan, kuni sa tuled.", "I will wait until you come."],
  ["nagu", "Ta räägib nagu õpetaja.", "She talks like a teacher."],
  ["sellepärast", "Mul on külm, sellepärast ma jään koju.", "I am cold, so I am staying home."],
  ["seega", "Buss hilineb, seega ma võtan takso.", "The bus is late, so I will take a taxi."],
  ["siis", "Kui sa tuled, siis me sööme koos.", "If you come, then we will eat together."],
  ["nii", "Sa räägid nii hästi!", "You speak so well!"],
  ["mitte", "Mitte täna, vaid homme.", "Not today, but tomorrow."],
  ["kuigi", "Ma lähen tööle, kuigi on külm.", "I am going to work, although it is cold."],
  // kindlus
  ["kindlasti", "Ma tulen kindlasti.", "I will definitely come."],
  ["vist", "Ta on vist kodus.", "I think he is at home."],
  ["äkki", "Äkki ta ei tule.", "Maybe she will not come."],
  ["küll", "Ta tuleb küll.", "He will come, you will see."],
  ["eks", "Sa tuled homme, eks?", "You are coming tomorrow, right?"],
  ["tõesti", "Kas see on tõesti sinu?", "Is this really yours?"],
  ["tegelikult", "Tegelikult ma ei tea.", "Actually, I do not know."],
  ["õige", "See on õige tee.", "This is the right way."],
  // maaramine
  ["ju", "Sa ju tead seda.", "You know that, don't you."],
  ["just", "Ta tuli just koju.", "She has just come home."],
  ["enam", "Ma ei tööta enam.", "I do not work any more."],
  ["isegi", "Isegi laps teab seda.", "Even a child knows that."],
  ["ikka", "Ma elan ikka siin.", "I still live here."],
  ["rohkem", "Palun anna mulle rohkem vett.", "Please give me more water."],
  ["liiga", "See on liiga kallis.", "This is too expensive."],
  ["päris", "Täna on päris külm.", "It is quite cold today."],
  ["natuke", "Ma räägin natuke eesti keelt.", "I speak a little Estonian."],
  ["üldse", "Ma ei tea üldse.", "I have no idea at all."],
  ["eriti", "Täna on eriti külm.", "It is especially cold today."],
  ["sama", "Meil on sama õpetaja.", "We have the same teacher."],
  ["uuesti", "Palun ütle uuesti.", "Please say it again."],
  ["varem", "Ma ärkan täna varem.", "I am waking up earlier today."],
  ["kaua", "Kui kaua sa siin elad?", "How long have you lived here?"],
  ["siit", "Kas buss läheb siit?", "Does the bus leave from here?"],
  ["sinna", "Ma lähen sinna homme.", "I am going there tomorrow."],
  ["üksi", "Ma elan üksi.", "I live alone."],
  ["aeglaselt", "Palun räägi aeglaselt.", "Please speak slowly."],
  // kuud
  ["jaanuar", "Jaanuaris on väga külm.", "It is very cold in January."],
  ["veebruar", "Veebruaris tuleb palju lund.", "A lot of snow falls in February."],
  ["märts", "Märtsis on veel külm.", "It is still cold in March."],
  ["aprill", "Aprillis tuleb tihti vihma.", "It often rains in April."],
  ["mai", "Mais on ilm juba soe.", "In May the weather is already warm."],
  ["juuni", "Juunis me läheme randa.", "In June we go to the beach."],
  ["juuli", "Juulis on väga soe.", "It is very warm in July."],
  ["august", "Augustis me oleme kodus.", "In August we are at home."],
  ["september", "Septembris lähevad lapsed kooli.", "In September children go to school."],
  ["oktoober", "Oktoobris on palju vihma.", "There is a lot of rain in October."],
  ["november", "Novembris on hall ilm.", "The weather is grey in November."],
  ["detsember", "Detsembris tuleb lund.", "It snows in December."],
  ["kuupäev", "Mis kuupäev täna on?", "What is the date today?"],
  ["sünnipäev", "Täna on minu sünnipäev.", "Today is my birthday."],
  ["tähtpäev", "Täna on tähtpäev.", "Today is a special day."],
  ["jaanipäev", "Jaanipäeval me oleme rannas.", "At Midsummer we are at the beach."],
  ["nädalavahetus", "Head nädalavahetust!", "Have a good weekend!"],
  ["puhkepäev", "Pühapäev on minu puhkepäev.", "Sunday is my day off."],
  // riigid
  ["Eesti", "Ma elan Eestis.", "I live in Estonia."],
  ["Soome", "Mu vend elab Soomes.", "My brother lives in Finland."],
  ["Läti", "Me sõidame homme Lätti.", "We are going to Latvia tomorrow."],
  ["Venemaa", "Ta sõidab homme Venemaale.", "She is going to Russia tomorrow."],
  ["Rootsi", "Mu õde elab Rootsis.", "My sister lives in Sweden."],
  ["Saksamaa", "Mu sõber töötab Saksamaal.", "My friend works in Germany."],
  ["Inglismaa", "Ta õpib Inglismaal.", "She studies in England."],
  ["Ameerika", "Tema isa elab Ameerikas.", "Her father lives in America."],
  ["Euroopa", "Eesti on Euroopas.", "Estonia is in Europe."],
  ["eestlane", "Ma olen eestlane.", "I am Estonian."],
  ["soomlane", "Tema naine on soomlane.", "His wife is Finnish."],
  ["lätlane", "Minu kolleeg on lätlane.", "My colleague is Latvian."],
  ["venelane", "Ta on venelane, aga elab Eestis.", "He is Russian but lives in Estonia."],
  ["rootslane", "Meie õpetaja on rootslane.", "Our teacher is Swedish."],
  ["sakslane", "Minu õpetaja on sakslane.", "My teacher is German."],
  ["inglane", "Ta on inglane.", "He is English."],
  ["ameeriklane", "Kas sa oled ameeriklane?", "Are you American?"],
  ["välismaalane", "Ma olen välismaalane.", "I am a foreigner."],
  ["kodumaa", "Eesti on minu kodumaa.", "Estonia is my homeland."],
  ["rahvus", "Mis rahvus sa oled?", "What nationality are you?"],
  ["pärit", "Kust sa pärit oled?", "Where are you from?"],
  ["vene", "Ma räägin vene keelt.", "I speak Russian."],
  ["prantsuse", "Ta õpib prantsuse keelt.", "She is learning French."],
  ["Prantsusmaa", "Ma tahan minna Prantsusmaale.", "I want to go to France."],
  // viisisonad
  ["kiiresti", "Ta räägib väga kiiresti.", "She speaks very fast."],
  ["kergesti", "Laps õpib kergesti.", "The child learns easily."],
  ["kõvasti", "Räägi palun kõvasti.", "Please speak loudly."],
  ["halvasti", "Ma magasin halvasti.", "I slept badly."],
  ["tavaliselt", "Tavaliselt ma ärkan kell seitse.", "I usually wake up at seven."],
  ["enamasti", "Enamasti ma sõidan bussiga.", "Mostly I go by bus."],
  ["pidevalt", "Ta räägib pidevalt.", "He talks all the time."],
  ["umbes", "See maksab umbes kümme eurot.", "It costs about ten euros."],
  ["peaaegu", "Söök on peaaegu valmis.", "The food is almost ready."],
  ["üsna", "Täna on üsna soe.", "It is fairly warm today."],
  ["täiesti", "See on täiesti õige.", "That is completely right."],
  ["veidi", "Oota veidi, palun.", "Wait a little, please."],
  ["pisut", "Mul on pisut külm.", "I am a little cold."],
  ["vähemalt", "Ma magan vähemalt kaheksa tundi.", "I sleep at least eight hours."],
  ["alles", "Kell on alles seitse.", "It is only seven o'clock."],
  ["taas", "Täna on taas külm.", "It is cold again today."],
  ["pigem", "Ma joon pigem teed.", "I would rather drink tea."],
  // osakesed
  ["kinni", "Pane uks kinni.", "Close the door."],
  ["lahti", "Aken on lahti.", "The window is open."],
  ["välja", "Ma lähen välja.", "I am going out."],
  ["sisse", "Tule sisse!", "Come in!"],
  ["üles", "Ärka üles!", "Wake up!"],
  ["maha", "Istu maha.", "Sit down."],
  ["alla", "Ma tulen kohe alla.", "I am coming down right away."],
  ["kokku", "Me saame homme kokku.", "We are meeting tomorrow."],
  ["laiali", "Raamatud on põrandal laiali.", "The books are all over the floor."],
  ["kaasa", "Võta raha kaasa.", "Take some money with you."],
  ["ette", "Auto sõitis maja ette.", "The car pulled up in front of the house."],
  ["taha", "Pane tool laua taha.", "Put the chair behind the table."],
  ["juurde", "Ma lähen arsti juurde.", "I am going to the doctor."],
  ["järele", "Isa tuleb lapsele järele.", "Dad is coming to pick up the child."],
  // abi
  ["abi", "Abi tuleb kohe.", "Help is coming right away."],
  ["aitama", "Kas sa saad mind aidata?", "Can you help me?"],
  ["appi", "Appi, appi!", "Help, help!"],
  ["politsei", "Politsei on siin.", "The police are here."],
  ["kiirabi", "Kiirabi sõidab kiiresti.", "The ambulance is driving fast."],
  ["tuletõrje", "Tuletõrje tuleb kohe.", "The fire brigade is coming right away."],
  ["hädaabi", "Mis on hädaabi number?", "What is the emergency number?"],
  ["apteek", "Kus on apteek?", "Where is the pharmacy?"],
  ["tuli", "Köögis on tuli!", "There is a fire in the kitchen!"],
  ["ohtlik", "See tee on ohtlik.", "This road is dangerous."],
  ["varas", "Varas võttis mu telefoni.", "A thief took my phone."],
  ["eksima", "Ma eksisin linnas.", "I got lost in the town."],
  ["helistama", "Ma helistan sulle homme.", "I will call you tomorrow."],
  ["vaja", "Mul on vaja minna.", "I need to go."],
  // A2: korraldused
  ["lubama", "Ema lubab mul minna.", "Mum lets me go."],
  ["keelama", "Arst keelab mul kohvi juua.", "The doctor forbids me to drink coffee."],
  ["paluma", "Ma palun sind aidata.", "I am asking you to help."],
  ["soovima", "Ma soovin sulle head päeva.", "I wish you a good day."],
  ["käskima", "Õpetaja käsib lapsel istuda.", "The teacher tells the child to sit down."],
  ["proovima", "Proovi seda suppi!", "Try this soup!"],
  ["jätkama", "Homme me jätkame.", "Tomorrow we will carry on."],
  ["peatuma", "Buss peatub siin.", "The bus stops here."],
  ["peatama", "Politsei peatab auto.", "The police stop the car."],
  ["takistama", "Vihm takistab meid minna.", "The rain stops us from going."],
  ["vabandama", "Ma vabandan, et ma hilinen.", "I am sorry that I am late."],
  ["tänama", "Ma tänan sind väga.", "Thank you very much."],
  ["tervitama", "Tervita oma ema!", "Say hello to your mother!"],
  ["tohtima", "Kas ma tohin siin istuda?", "May I sit here?"],
  // A2: minevik
  ["juhtuma", "Mis juhtus?", "What happened?"],
  ["alustama", "Me alustame kell üheksa.", "We start at nine."],
  ["algama", "Tund algab kell kaheksa.", "The lesson starts at eight."],
  ["lõpetama", "Ma lõpetan töö kell viis.", "I finish work at five."],
  ["lõppema", "Tund lõpeb varsti.", "The lesson ends soon."],
  ["unustama", "Ma unustasin võtme koju.", "I left the key at home."],
  ["mäletama", "Kas sa mäletad mind?", "Do you remember me?"],
  ["juhtima", "Isa juhib autot.", "Dad is driving the car."],
  ["kohtuma", "Me kohtume homme kohvikus.", "We are meeting in the café tomorrow."],
  ["sündima", "Ma sündisin Eestis.", "I was born in Estonia."],
  ["surema", "Vanaisa suri eile.", "Grandpa died yesterday."],
  ["kasvama", "Laps kasvab kiiresti.", "The child is growing fast."],
  ["muutuma", "Ilm muutub kiiresti.", "The weather changes fast."],
  ["muutma", "Ma tahan seda muuta.", "I want to change it."],
  // A2: loodus
  ["loodus", "Eestis on ilus loodus.", "Estonia has beautiful nature."],
  ["mets", "Me läheme metsa.", "We are going to the forest."],
  ["meri", "Meri on täna külm.", "The sea is cold today."],
  ["järv", "Järves on palju kala.", "There are a lot of fish in the lake."],
  ["jõgi", "See jõgi on väga pikk.", "This river is very long."],
  ["mägi", "Eestis ei ole mägesid.", "There are no mountains in Estonia."],
  ["maa", "Me elame maal.", "We live in the country."],
  ["puu", "Maja ees on suur puu.", "There is a big tree in front of the house."],
  ["lill", "Ma toon emale lilli.", "I am bringing Mum flowers."],
  ["rohi", "Rohi on märg.", "The grass is wet."],
  ["loom", "Mis loom see on?", "What animal is that?"],
  ["koer", "Meil on väike koer.", "We have a small dog."],
  ["kass", "Kass magab voodil.", "The cat is sleeping on the bed."],
  ["lind", "Puu peal on lind.", "There is a bird in the tree."],
  ["hobune", "Vanaisal on hobune.", "Grandpa has a horse."],
  ["kevad", "Kevadel on ilm soe.", "In spring the weather is warm."],
  ["suvi", "Suvi on ilus aeg.", "Summer is a lovely time."],
  ["sügis", "Sügisel tuleb palju vihma.", "In autumn it rains a lot."],
  ["talv", "Talvel on siin väga külm.", "In winter it is very cold here."],
  // A2: keha-ja-tervis
  ["keha", "Kehale on vaja vett.", "The body needs water."],
  ["käsi", "Mul on külmad käed.", "My hands are cold."],
  ["jalg", "Tal on pikad jalad.", "She has long legs."],
  ["silm", "Tal on sinised silmad.", "She has blue eyes."],
  ["kõrv", "Koeral on suured kõrvad.", "The dog has big ears."],
  ["suu", "Pane suu kinni!", "Close your mouth!"],
  ["nina", "Lapsel on külm nina.", "The child has a cold nose."],
  ["pea", "Pane müts pähe!", "Put your hat on!"],
  ["süda", "Tal on hea süda.", "She has a good heart."],
  ["selg", "Selg on märg.", "My back is wet."],
  ["tervis", "Kuidas su tervis on?", "How is your health?"],
  ["haigus", "See haigus ei ole ohtlik.", "This illness is not dangerous."],
  ["valu", "Mul on suur valu.", "I am in a lot of pain."],
  ["ravim", "Võta see ravim hommikul.", "Take this medicine in the morning."],
  ["palavik", "Lapsel on palavik.", "The child has a fever."],
  ["haige", "Ma olen täna haige.", "I am ill today."],
  ["terve", "Laps on jälle terve.", "The child is well again."],
  ["väsinud", "Ma olen väga väsinud.", "I am very tired."],
  ["valutama", "Mis sul valutab?", "What hurts?"],
  ["tablett", "Võta üks tablett.", "Take one tablet."],
  // A2: kool-ja-keel
  ["sõna", "Ma ei tea seda sõna.", "I do not know this word."],
  ["keel", "Eesti keel on ilus.", "Estonian is a beautiful language."],
  ["lause", "See lause on liiga pikk.", "This sentence is too long."],
  ["küsimus", "Mul on üks küsimus.", "I have a question."],
  ["vastus", "See on õige vastus.", "That is the right answer."],
  ["õppimine", "Õppimine võtab aega.", "Learning takes time."],
  ["harjutus", "See harjutus on lihtne.", "This exercise is easy."],
  ["viga", "Siin on üks viga.", "There is a mistake here."],
  ["näide", "Palun anna mulle üks näide.", "Please give me an example."],
  ["raamatukogu", "Ma lähen raamatukokku.", "I am going to the library."],
  ["ajaleht", "Isa loeb hommikul ajalehte.", "Dad reads the newspaper in the morning."],
  ["uudis", "Mul on sulle hea uudis.", "I have good news for you."],
  ["lugu", "See on väga ilus lugu.", "This is a very beautiful story."],
  ["õpetama", "Ta õpetab koolis eesti keelt.", "She teaches Estonian at school."],
  ["seletama", "Palun seleta mulle uuesti.", "Please explain it to me again."],
  ["kordama", "Palun korda seda sõna.", "Please repeat that word."],
  ["tõlkima", "Kas sa saad seda tõlkida?", "Can you translate this?"],
  // A2: reisimine
  ["reis", "Head reisi!", "Have a good trip!"],
  ["puhkus", "Mul on nüüd puhkus.", "I am on holiday now."],
  ["riik", "Mis riigist sa pärit oled?", "Which country are you from?"],
  ["piir", "Piir on siin lähedal.", "The border is near here."],
  ["lennuk", "Lennuk hilineb.", "The plane is late."],
  ["laev", "Me sõidame laevaga Soome.", "We are going to Finland by ship."],
  ["kaart", "Kas ma saan kaardiga maksta?", "Can I pay by card?"],
  ["kohver", "Minu kohver on väga raske.", "My suitcase is very heavy."],
  ["lendama", "Homme me lendame Rootsi.", "Tomorrow we are flying to Sweden."],
  ["kõndima", "Ma kõnnin iga päev tööle.", "I walk to work every day."],
  ["jooksma", "Laps jookseb kiiresti.", "The child runs fast."],
  ["otsima", "Ma otsin oma võtit.", "I am looking for my key."],
  ["leidma", "Ma leidsin oma telefoni.", "I found my phone."],
  ["jõudma", "Me jõuame koju kell kuus.", "We get home at six."],
  ["broneerima", "Ma tahan broneerida laua.", "I would like to book a table."],
  // A2: kodutood
  ["koristama", "Laupäeval me koristame kodu.", "On Saturday we clean the house."],
  ["pesema", "Pese käed!", "Wash your hands!"],
  ["küpsetama", "Vanaema küpsetab leiba.", "Grandma is baking bread."],
  ["keetma", "Ma keedan kohvi.", "I am making coffee."],
  ["praadima", "Isa praeb kala.", "Dad is frying fish."],
  ["lõikama", "Lõika leib, palun.", "Cut the bread, please."],
  ["parandama", "Isa parandab autot.", "Dad is repairing the car."],
  ["ehitama", "Nad ehitavad uut maja.", "They are building a new house."],
  ["kandma", "Ta kannab punast kleiti.", "She is wearing a red dress."],
  ["hoidma", "Hoia last käest kinni.", "Hold the child by the hand."],
  ["avama", "Ava uks, palun.", "Open the door, please."],
  ["sulgema", "Palun sule aken.", "Please close the window."],
  ["katma", "Ema katab lauda.", "Mum is laying the table."],
  ["riidekapp", "Mantel on riidekapis.", "The coat is in the wardrobe."],
  ["nõu", "Pese nõud.", "Wash the dishes."],
  ["prügi", "Vii prügi välja.", "Take the rubbish out."],
  ["katki", "Minu telefon on katki.", "My phone is broken."],
  // A2: linn-ja-teenused
  ["pank", "Pank on nurga peal.", "The bank is on the corner."],
  ["post", "Kas mulle on posti?", "Is there any post for me?"],
  ["amet", "Mis amet sul on?", "What is your job?"],
  ["arve", "Kas ma saaksin arve?", "Could I have the bill?"],
  ["konto", "Mul on pangas konto.", "I have an account at the bank."],
  ["kaup", "See kaup on odav.", "These goods are cheap."],
  ["klient", "Klient ootab.", "The customer is waiting."],
  ["teenus", "See teenus on kallis.", "This service is expensive."],
  ["järjekord", "Järjekord on väga pikk.", "The queue is very long."],
  ["dokument", "Mul on vaja dokumenti.", "I need a document."],
  ["allkiri", "Siia on vaja allkirja.", "A signature is needed here."],
  ["avaldus", "Ma kirjutan avalduse.", "I am writing an application."],
  ["luba", "Kas sul on luba?", "Do you have permission?"],
  ["täitma", "Palun täida see avaldus.", "Please fill in this application."],
  ["saatma", "Ma saadan sulle raha.", "I will send you money."],
  ["tellima", "Me tellime takso.", "We are ordering a taxi."],
  ["esitama", "Ma esitan avalduse homme.", "I will hand in the application tomorrow."],
  // A2: vaba-aeg
  ["sport", "Mulle meeldib sport.", "I like sport."],
  ["mäng", "See mäng on lihtne.", "This game is easy."],
  ["muusika", "Mulle meeldib see muusika.", "I like this music."],
  ["laul", "See on ilus laul.", "That is a beautiful song."],
  ["tants", "See tants on raske.", "This dance is difficult."],
  ["film", "Film algab kell kaheksa.", "The film starts at eight."],
  ["teater", "Täna õhtul me läheme teatrisse.", "Tonight we are going to the theatre."],
  ["näitus", "Näitus on väga ilus.", "The exhibition is very beautiful."],
  ["pidu", "Laupäeval on pidu.", "There is a party on Saturday."],
  ["reegel", "Mis on mängu reegel?", "What is the rule of the game?"],
  ["võistlus", "Homme on võistlus.", "The competition is tomorrow."],
  ["mängima", "Lapsed mängivad pargis.", "The children are playing in the park."],
  ["laulma", "Ta laulab väga hästi.", "She sings very well."],
  ["tantsima", "Kas sa tahad tantsida?", "Do you want to dance?"],
  ["ujuma", "Suvel me ujume meres.", "In summer we swim in the sea."],
  ["võitma", "Kes võitis?", "Who won?"],
  ["kaotama", "Ma kaotasin oma võtme.", "I lost my key."],
  // A2: restoranis
  ["menüü", "Kas ma saaksin menüü?", "Could I have the menu?"],
  ["roog", "See roog on väga hea.", "This dish is very good."],
  ["eelroog", "Eelroaks võtan supi.", "I will have the soup as a starter."],
  ["magustoit", "Mis on magustoiduks?", "What is for dessert?"],
  ["kaste", "Kaste on liiga kuum.", "The sauce is too hot."],
  ["salat", "Ma võtan salati.", "I will have the salad."],
  ["köögivili", "Lapsed ei taha köögivilju.", "The children do not want vegetables."],
  ["puuvili", "Ma söön iga päev puuvilju.", "I eat fruit every day."],
  ["mari", "Metsas on palju marju.", "There are a lot of berries in the forest."],
  ["seen", "Metsas on palju seeni.", "There are a lot of mushrooms in the forest."],
  ["maitse", "Supil on hea maitse.", "The soup tastes good."],
  ["portsjon", "Palun üks portsjon kala.", "One portion of fish, please."],
  ["soovitama", "Mida te soovitate?", "What do you recommend?"],
  ["maitsma", "Kuidas supp maitseb?", "How does the soup taste?"],
  // A2: vordlemine
  ["tugev", "Ta on väga tugev.", "He is very strong."],
  ["nõrk", "Kohv on liiga nõrk.", "The coffee is too weak."],
  ["lai", "See tänav on lai.", "This street is wide."],
  ["kitsas", "Mu uued püksid on kitsad.", "My new trousers are tight."],
  ["sügav", "Järv on väga sügav.", "The lake is very deep."],
  ["madal", "Siin on meri madal.", "The sea is shallow here."],
  ["kõrge", "See maja on väga kõrge.", "This building is very tall."],
  ["paks", "See raamat on väga paks.", "This book is very thick."],
  ["õhuke", "Leib on õhuke.", "The bread is thin."],
  ["puhas", "Tuba on nüüd puhas.", "The room is clean now."],
  ["määrdunud", "Mu käed on määrdunud.", "My hands are dirty."],
  ["tühi", "Mu klaas on tühi.", "My glass is empty."],
  ["sarnane", "Sa oled oma emaga väga sarnane.", "You look a lot like your mother."],
  ["erinev", "Meil on erinevad õpetajad.", "We have different teachers."],
  // A2: plaanid
  ["plaan", "Mis su plaan on?", "What is your plan?"],
  ["kavatsus", "Mul on kavatsus minna Soome.", "I intend to go to Finland."],
  ["eesmärk", "Minu eesmärk on rääkida eesti keelt.", "My goal is to speak Estonian."],
  ["võimalus", "See on hea võimalus.", "This is a good opportunity."],
  ["otsus", "See on raske otsus.", "It is a difficult decision."],
  ["kavatsema", "Mida sa homme teha kavatsed?", "What are you planning to do tomorrow?"],
  ["planeerima", "Me planeerime reisi.", "We are planning a trip."],
  ["otsustama", "Ma ei saa otsustada.", "I cannot decide."],
  ["valima", "Vali üks!", "Choose one!"],
  ["lootma", "Ma loodan, et sa tuled.", "I hope you will come."],
  ["kartma", "Laps kardab koera.", "The child is afraid of the dog."],
  ["uskuma", "Ma ei usu seda.", "I do not believe it."],
  ["arvama", "Mida sa arvad?", "What do you think?"],
  ["nõustuma", "Ma nõustun sinuga.", "I agree with you."],
  ["nõus", "Ma olen nõus.", "I agree."],
  ["sobima", "Kas homme sobib?", "Does tomorrow suit you?"],
  ["kestma", "Film kestab kaks tundi.", "The film lasts two hours."],
  // A2: suhtlemine
  ["saabuma", "Rong saabub kell kolm.", "The train arrives at three."],
  ["teatama", "Palun teata mulle homme.", "Please let me know tomorrow."],
  ["kutsuma", "Ma kutsun sind sünnipäevale.", "I am inviting you to my birthday."],
  ["kohtumine", "Kohtumine on kell kümme.", "The meeting is at ten."],
  ["sõnum", "Ma saatsin sulle sõnumi.", "I sent you a message."],
  ["kiri", "Mul on sulle kiri.", "I have a letter for you."],
  ["võrk", "Siin ei ole võrku.", "There is no signal here."],
  ["leht", "Puu lehed on kollased.", "The leaves on the tree are yellow."],
  ["parool", "Mis on parool?", "What is the password?"],
  ["heli", "Siin on halb heli.", "The sound is bad here."],
  // A2: tunded
  ["rõõm", "Rõõm sind näha!", "Nice to see you!"],
  ["mure", "Mul on üks mure.", "I have a worry."],
  ["hirm", "Lapsel on hirm.", "The child is scared."],
  ["viha", "Ta ei tunne viha.", "He does not feel anger."],
  ["armastus", "Armastus on ilus.", "Love is beautiful."],
  ["meel", "Mul on hea meel sind näha.", "I am glad to see you."],
  ["tunne", "Mul on hea tunne.", "I have a good feeling."],
  ["õnn", "Palju õnne sünnipäevaks!", "Happy birthday!"],
  ["rahu", "Anna mulle rahu!", "Leave me in peace!"],
  ["rõõmus", "Laps on väga rõõmus.", "The child is very happy."],
  ["kurb", "Miks sa kurb oled?", "Why are you sad?"],
  ["vihane", "Isa on vihane.", "Dad is angry."],
  ["murelik", "Ema on murelik.", "Mum is worried."],
  ["rahulik", "Ole rahulik!", "Stay calm!"],
  ["üllatunud", "Ma olen väga üllatunud.", "I am very surprised."],
  ["tunduma", "See tundub hea.", "That seems good."],
  // A2: kuivord
  ["vähe", "Mul on vähe aega.", "I have little time."],
  ["vähem", "Ma tahan vähem tööd.", "I want less work."],
  ["piisavalt", "Kas sul on piisavalt raha?", "Do you have enough money?"],
  ["osaliselt", "See on osaliselt valmis.", "It is partly ready."],
  ["täielikult", "Ma olen täielikult nõus.", "I completely agree."],
  ["äärmiselt", "See on äärmiselt raske.", "This is extremely difficult."],
  ["lausa", "Täna on lausa kuum.", "It is downright hot today."],
  ["sugugi", "See ei ole sugugi lihtne.", "That is not at all easy."],
  ["hoopis", "Ma võtan hoopis teed.", "I will have tea instead."],
  ["ligi", "Siin elab ligi sada inimest.", "Nearly a hundred people live here."],
  ["üha", "Inimesi tuleb üha juurde.", "More and more people keep coming."],
  ["aina", "Ta räägib aina tööst.", "He talks about work all the time."],
  // B1: inimsuhted
  ["suhe", "Meil on hea suhe.", "We have a good relationship."],
  ["sõprus", "Meie sõprus on väga vana.", "Our friendship is very old."],
  ["usaldus", "Usaldus tuleb ajaga.", "Trust comes with time."],
  ["tüli", "Neil oli eile tüli.", "They had a quarrel yesterday."],
  ["lepitus", "Lepitus võttis kaua aega.", "The reconciliation took a long time."],
  ["abielu", "Nende abielu on väga hea.", "Their marriage is very good."],
  ["usaldama", "Ma usaldan sind.", "I trust you."],
  ["tülitsema", "Lapsed tülitsevad jälle.", "The children are quarrelling again."],
  ["leppima", "Ma lepin sellega.", "I will settle for that."],
  ["toetama", "Pere toetab mind alati.", "My family always supports me."],
  ["hoolima", "Ma hoolin sinust väga.", "I care about you a lot."],
  ["mõistma", "Ma mõistan sind.", "I understand you."],
  ["solvama", "Ma ei tahtnud sind solvata.", "I did not want to offend you."],
  // B1: rektsioon
  ["meeldima", "Mulle meeldib eesti muusika.", "I like Estonian music."],
  ["mõtlema", "Ma mõtlen sinule.", "I am thinking of you."],
  ["armastama", "Ma armastan sind.", "I love you."],
  ["vihkama", "Ma vihkan külma ilma.", "I hate cold weather."],
  ["vajama", "Laps vajab abi.", "The child needs help."],
  ["sõltuma", "See sõltub ilmast.", "It depends on the weather."],
  ["osalema", "Ma osalen võistlusel.", "I am taking part in the competition."],
  ["tegelema", "Millega sa tegeled?", "What do you do?"],
  ["huvituma", "Ta huvitub muusikast.", "She is interested in music."],
  ["loobuma", "Ma loobun sellest plaanist.", "I am giving up this plan."],
  // B1: too-ja-raha
  ["palk", "Palk on väike.", "The pay is low."],
  ["koosolek", "Koosolek algab kell kümme.", "The meeting starts at ten."],
  ["leping", "Leping on laual.", "The contract is on the table."],
  ["toode", "See toode on uus.", "This product is new."],
  ["ettevõte", "Ta töötab väikeses ettevõttes.", "She works at a small company."],
  ["ülesanne", "See ülesanne on raske.", "This task is difficult."],
  ["kogemus", "Mul on selles töös kogemusi.", "I have experience in this work."],
  ["oskus", "Mul ei ole seda oskust.", "I do not have that skill."],
  ["vastutus", "See on suur vastutus.", "It is a big responsibility."],
  ["projekt", "Projekt lõpeb detsembris.", "The project ends in December."],
  ["tähtaeg", "Tähtaeg on reedel.", "The deadline is on Friday."],
  ["aruanne", "Ma kirjutan aruannet.", "I am writing a report."],
  ["kasutama", "Kas ma saan su telefoni kasutada?", "Can I use your phone?"],
  ["korraldama", "Me korraldame peo.", "We are going to throw a party."],
  ["vastutama", "Kes siin vastutab?", "Who is in charge here?"],
  ["saavutama", "Me saavutame oma eesmärgi.", "We will reach our goal."],
  // B1: tingiv
  ["eelistama", "Ma eelistaksin teed.", "I would prefer tea."],
  ["kaaluma", "Ma kaaluksin seda võimalust.", "I would consider that option."],
  ["pakkuma", "Mida ma saaksin teile pakkuda?", "What could I offer you?"],
  ["nõudma", "Ma ei nõuaks sinult liiga palju.", "I would not ask too much of you."],
  ["oletama", "Ma oletaksin, et ta tuleb homme.", "I would guess he is coming tomorrow."],
  ["tingimus", "Selle tingimusega oleksin ma nõus.", "On that condition I would agree."],
  ["juhus", "See oleks küll juhus!", "That really would be a coincidence!"],
  ["olukord", "Mida sa selles olukorras teeksid?", "What would you do in this situation?"],
  ["valik", "Mis oleks sinu valik?", "What would your choice be?"],
  // B1: haridus
  ["haridus", "Tal on hea haridus.", "She has a good education."],
  ["eriala", "Mis on sinu eriala?", "What is your field of study?"],
  ["õppekava", "Koolil on uus õppekava.", "The school has a new curriculum."],
  ["loeng", "Loeng algab kell üheksa.", "The lecture starts at nine."],
  ["seminar", "Homme on seminar.", "There is a seminar tomorrow."],
  ["eksam", "Mul on homme eksam.", "I have an exam tomorrow."],
  ["hinne", "Laps sai hea hinde.", "The child got a good grade."],
  ["tunnistus", "Laps sai hea tunnistuse.", "The child got a good report card."],
  ["stipendium", "Ta sai stipendiumi.", "She got a scholarship."],
  ["teadmine", "Sellest teadmisest on abi.", "That knowledge helps."],
  ["lõpetaja", "Ta on selle kooli lõpetaja.", "He is a graduate of this school."],
  ["sooritama", "Ma sooritasin eksami.", "I passed the exam."],
  ["omandama", "Ta omandab uut keelt.", "She is learning a new language."],
  ["kandideerima", "Ma kandideerin uuele tööle.", "I am applying for a new job."],
  // B1: kesksonad
  ["lahkuma", "Rong lahkub kell kaks.", "The train leaves at two."],
  ["valmima", "Maja valmib sügisel.", "The house will be finished in autumn."],
  ["katkema", "Kas meie sõprus katkeb?", "Is our friendship coming to an end?"],
  ["säilima", "Vana maja on hästi säilinud.", "The old house has been well preserved."],
  ["tekkima", "Mul tekkis küsimus.", "A question came up."],
  ["kaduma", "Minu võti kadus.", "My key has gone missing."],
  ["ilmuma", "Uus raamat ilmub kevadel.", "The new book comes out in spring."],
  ["arenema", "Laps areneb kiiresti.", "The child is developing fast."],
  ["paranema", "Ilm paraneb.", "The weather is getting better."],
  ["halvenema", "Olukord halveneb.", "The situation is getting worse."],
  ["jätkuma", "Vihm jätkub homme.", "The rain will carry on tomorrow."],
  // B1: eluase
  ["üür", "Üür on liiga kõrge.", "The rent is too high."],
  ["üürnik", "Uus üürnik tuleb homme.", "The new tenant is coming tomorrow."],
  ["omanik", "Kes on maja omanik?", "Who owns the house?"],
  ["kolimine", "Kolimine on raske töö.", "Moving house is hard work."],
  ["remont", "Korteris on remont.", "The flat is being renovated."],
  ["mööbel", "Mööbel on vana.", "The furniture is old."],
  ["küte", "Küte ei tööta.", "The heating is not working."],
  ["elekter", "Elekter on kallis.", "Electricity is expensive."],
  ["naaber", "Minu naaber on väga meeldiv.", "My neighbour is very pleasant."],
  ["kord", "Pane oma tuba korda!", "Tidy up your room!"],
  ["ruum", "Selles ruumis on külm.", "It is cold in this room."],
  ["kolima", "Me kolime uude korterisse.", "We are moving into a new flat."],
  ["üürima", "Ma üürin korterit.", "I rent a flat."],
  ["sisustama", "Me sisustame uut kodu.", "We are furnishing our new home."],
  ["lekkima", "Köögis lekib vesi.", "Water is leaking in the kitchen."],
  // B1: iseloom
  ["iseloom", "Tal on hea iseloom.", "He has a good character."],
  ["aus", "Ta on aus inimene.", "She is an honest person."],
  ["sõbralik", "Meie naaber on väga sõbralik.", "Our neighbour is very friendly."],
  ["tagasihoidlik", "Ta on väga tagasihoidlik.", "He is very modest."],
  ["enesekindel", "Ta räägib enesekindlalt.", "She speaks with confidence."],
  ["kannatlik", "Ole kannatlik!", "Be patient!"],
  ["hoolas", "Ta on hoolas õpilane.", "She is a diligent student."],
  ["laisk", "Täna olen ma laisk.", "Today I am lazy."],
  ["julge", "Laps on väga julge.", "The child is very brave."],
  ["arglik", "Ta on natuke arglik.", "He is a little timid."],
  ["helde", "Vanaema on väga helde.", "Grandma is very generous."],
  ["ihne", "Ta on väga ihne.", "He is very stingy."],
  ["range", "Meie õpetaja on range.", "Our teacher is strict."],
  ["leebe", "Talv on sel aastal leebe.", "The winter is mild this year."],
  ["andekas", "Ta on väga andekas laps.", "She is a very talented child."],
  // B1: meedia
  ["ajakirjanik", "Ta töötab ajakirjanikuna.", "She works as a journalist."],
  ["ajakiri", "Ma loen seda ajakirja.", "I read this magazine."],
  ["saade", "Saade algab kell kaheksa.", "The programme starts at eight."],
  ["intervjuu", "Mul on homme intervjuu.", "I have an interview tomorrow."],
  ["allikas", "Mis on selle uudise allikas?", "What is the source of this news?"],
  ["pealkiri", "Pealkiri on liiga pikk.", "The headline is too long."],
  ["artikkel", "Ma kirjutan artiklit.", "I am writing an article."],
  ["reklaam", "Telefonis on liiga palju reklaami.", "There are too many ads on the phone."],
  ["sündmus", "See oli suur sündmus.", "It was a big event."],
  ["teade", "Ma sain teate.", "I got a notice."],
  ["kuulutama", "Ta kuulutab, et pidu algab.", "He announces that the party is starting."],
  ["avaldama", "Ajaleht avaldab artikli homme.", "The newspaper publishes the article tomorrow."],
  ["kajastama", "Ajaleht kajastab seda sündmust.", "The newspaper covers the event."],
  ["kommenteerima", "Ma ei taha seda kommenteerida.", "I do not want to comment on it."],
  ["kinnitama", "Palun kinnita oma aadress.", "Please confirm your address."],
  // B1: tehnoloogia
  ["seade", "See seade on uus.", "This device is new."],
  ["ekraan", "Ekraan on katki.", "The screen is broken."],
  ["klaviatuur", "Klaviatuur ei tööta.", "The keyboard is not working."],
  ["fail", "Saada mulle see fail.", "Send me the file."],
  ["kaust", "Fail on selles kaustas.", "The file is in this folder."],
  ["andmed", "Kus on minu andmed?", "Where is my data?"],
  ["tarkvara", "Arvutis on uus tarkvara.", "The computer has new software."],
  ["rakendus", "See rakendus on väga lihtne.", "This app is very simple."],
  ["turvalisus", "Me hoolime turvalisusest.", "We care about security."],
  ["ühendus", "Ühendus on väga aeglane.", "The connection is very slow."],
  ["salvestama", "Palun salvesta see fail.", "Please save this file."],
  ["kustutama", "Ma kustutasin selle faili.", "I deleted that file."],
  ["laadima", "Ma laen telefoni.", "I am charging my phone."],
  ["uuendama", "Ma pean tarkvara uuendama.", "I have to update the software."],
  ["seadistama", "Isa seadistab uut telefoni.", "Dad is setting up the new phone."],
  // B1: arvamus
  ["arvamus", "Mis on sinu arvamus?", "What is your opinion?"],
  ["seisukoht", "Mul on teine seisukoht.", "I see it differently."],
  ["põhjus", "Mis on selle põhjus?", "What is the reason for this?"],
  ["tagajärg", "Sellel on halb tagajärg.", "This has a bad consequence."],
  ["näiteks", "Ma söön puuvilju, näiteks õunu.", "I eat fruit, apples for example."],
  ["vastuolu", "Siin on vastuolu.", "There is a contradiction here."],
  ["kahtlus", "Mul on kahtlus.", "I have a doubt."],
  ["kinnitus", "Ma ootan kinnitust.", "I am waiting for confirmation."],
  ["väitma", "Ta väidab, et see on õige.", "He claims that it is right."],
  ["vaidlema", "Nad vaidlevad jälle.", "They are arguing again."],
  ["kahtlema", "Ma kahtlen selles.", "I doubt it."],
  ["põhjendama", "Palun põhjenda oma vastust.", "Please give a reason for your answer."],
  ["tõestama", "Kas sa saad seda tõestada?", "Can you prove it?"],
  ["möönma", "Ma möönan, et see on raske.", "I admit that it is hard."],
  // B1: keskkond
  ["keskkond", "Me hoiame keskkonda puhtana.", "We keep the environment clean."],
  ["saaste", "Linnas on palju saastet.", "There is a lot of pollution in the city."],
  ["jäätmed", "Kuhu ma jäätmed panen?", "Where do I put the waste?"],
  ["taaskasutus", "Taaskasutus on keskkonnale hea.", "Recycling is good for the environment."],
  ["energia", "Mul ei ole täna energiat.", "I have no energy today."],
  ["kliima", "Eesti kliima on üsna külm.", "Estonia's climate is fairly cold."],
  ["liik", "Metsas elab palju liike.", "Many species live in the forest."],
  ["kaitse", "Loodus vajab kaitset.", "Nature needs protection."],
  ["ressurss", "Mets on Eesti ressurss.", "The forest is a resource for Estonia."],
  ["tarbimine", "Tarbimine kasvab.", "Consumption is growing."],
  ["säästma", "Me säästame vett.", "We save water."],
  ["kaitsma", "Ema kaitseb last.", "The mother protects the child."],
  ["reostama", "Prügi reostab jõge.", "Rubbish pollutes the river."],
  ["vähendama", "Me vähendame prügi.", "We are cutting down on rubbish."],
  ["sorteerima", "Me sorteerime prügi.", "We sort the rubbish."],
  // B1: probleemid
  ["probleem", "Mul on probleem.", "I have a problem."],
  ["kaebus", "Mul on kaebus.", "I have a complaint."],
  ["lahendus", "See on hea lahendus.", "That is a good solution."],
  ["õnnetus", "Tänaval juhtus õnnetus.", "There was an accident in the street."],
  ["oht", "Siin on oht.", "There is danger here."],
  ["risk", "See on suur risk.", "That is a big risk."],
  ["kahju", "Kui kahju!", "What a pity!"],
  ["hüvitis", "Ma sain hüvitise.", "I got compensation."],
  ["kaebama", "Klient kaebab.", "The customer is complaining."],
  ["lahendama", "Me lahendame selle probleemi.", "We will solve this problem."],
  ["põhjustama", "Vihm põhjustas õnnetuse.", "The rain caused an accident."],
  ["vältima", "Ma väldin kohvi.", "I avoid coffee."],
  ["hoiatama", "Ma hoiatan sind.", "I am warning you."],
  ["tagastama", "Ma tahan selle tagastada.", "I would like to return this."],
  ["puuduma", "Täna puudub kaks õpilast.", "Two students are missing today."],
  // B1: liitverbid
  ["ära tulema", "Tule siit ära!", "Come away from here!"],
  ["üles tõusma", "Ma tõusen kell seitse üles.", "I get up at seven."],
  ["läbi lugema", "Loe see leht läbi.", "Read this page through."],
  ["kokku leppima", "Lepime aja kokku.", "Let's set a time."],
  ["välja nägema", "Sa näed väga hea välja.", "You look very good."],
  ["maha jätma", "Ta jättis töö maha.", "He left his job."],
  ["üle vaatama", "Palun vaata see üle.", "Please look it over."],
  ["ette valmistama", "Ema valmistab söögi ette.", "Mum is preparing the food."],
  ["sisse astuma", "Astu sisse!", "Come in!"],
  ["edasi andma", "Anna see teade edasi.", "Pass on this message."],
  /*
    EVERY ROW ABOVE WAS READ, on 2026-09-26, by the native Estonian speaker
    who develops this app, A1 and A2 first and B1 after, and every change
    asked for is in. A row added below this line is drafted and checked by
    machine and waits for the same reading.
  */
  // The words added to the course on 2026-09-26.
  // vaikesed-sonad
  ["seal", "Ta elab seal.", "She lives there."],
  ["sealt", "Ma tulen sealt.", "I am coming from there."],
  // inimesed
  ["poiss", "See poiss on minu vend.", "That boy is my brother."],
  ["tüdruk", "See tüdruk õpib siin.", "That girl studies here."],
  ["abikaasa", "Minu abikaasa töötab täna.", "My husband is working today."],
  ["onu", "Minu onu elab siin.", "My uncle lives here."],
  ["tädi", "Tädi tuleb täna.", "My aunt is coming today."],
  // veel-verbe
  ["võima", "Kas ma võin tulla?", "May I come?"],
  ["oskama", "Ma oskan eesti keelt.", "I can speak Estonian."],
  ["vaatama", "Vaata seda raamatut!", "Look at this book!"],
  ["kuulama", "Palun kuula mind.", "Please listen to me."],
  ["käima", "Sõber käib täna meil.", "A friend is coming round to ours today."],
  ["hakkama", "Ma hakkan eesti keelt õppima.", "I am going to start learning Estonian."],
  ["näitama", "Näita mulle sinu tuba!", "Show me your room!"],
  ["tähendama", "Mida see tähendab?", "What does that mean?"],
  ["jätma", "Jäta raamat lauale.", "Leave the book on the table."],
  ["toimuma", "Mis siin toimub?", "What is going on here?"],
  // tahtsad-sonad
  ["asi", "See on hea asi.", "That is a good thing."],
  ["elu", "Elu on ilus.", "Life is beautiful."],
  ["osa", "See on minu osa.", "This is my part."],
  ["paar", "Mul on paar raamatut.", "I have a couple of books."],
  ["lõpp", "See on raamatu lõpp.", "This is the end of the book."],
  ["tähtis", "See on väga tähtis.", "This is very important."],
  ["oluline", "See on väga oluline.", "This is very important."],
  ["huvitav", "See raamat on huvitav.", "This book is interesting."],
  ["igav", "Täna on igav päev.", "Today is a boring day."],
  ["õnnelik", "Ma olen väga õnnelik.", "I am very happy."],
  ["vaba", "Kas see tool on vaba?", "Is this chair free?"],
  ["järgmine", "Järgmine tund on kell kaks.", "The next lesson is at two."],
  ["eelmine", "Eelmine nädal oli raske.", "Last week was hard."],
  ["viimane", "See on minu viimane päev siin.", "This is my last day here."],
  ["kindel", "Kas sa oled kindel?", "Are you sure?"],
  ["selge", "Jah, see on selge.", "Yes, that is clear."],
  ["võimalik", "See ei ole võimalik.", "That is not possible."],
  ["tubli", "Sa oled väga tubli!", "Well done, you are doing great!"],
  ["vale", "See on vale number.", "That is the wrong number."],
  ["näljane", "Ma olen väga näljane.", "I am very hungry."],
  // ilm
  ["väljas", "Väljas on külm.", "It is cold outside."],
  ["õues", "Lapsed on õues.", "The children are outside."],
  // kus-ja-kuhu
  ["kaugel", "Kas jaam on kaugel?", "Is the station far away?"],
  // umbmaarased
  ["kogu", "Kogu pere on kodus.", "The whole family is at home."],
  ["selline", "Mul on selline tunne.", "I have that kind of feeling."],
  // kohasonad
  ["eest", "Aitäh selle eest!", "Thank you for that!"],
  // viisisonad
  ["täpselt", "Kell on täpselt kaks.", "It is exactly two o'clock."],
  // vaikesed-sonad, moved from osakesed
  ["ära", "Ära mine veel!", "Do not go yet!"],
  // A2
  ["suutma", "Ma ei suuda enam oodata.", "I cannot wait any longer."],
  ["laskma", "Lase mul minna!", "Let me go!"],
  ["üritama", "Ma üritan homme uuesti.", "I will try again tomorrow."],
  ["nägu", "Tal on ilus nägu.", "She has a lovely face."],
  ["muretsema", "Ema muretseb alati.", "Mum always worries."],
  // B1
  ["tark", "Ta on väga tark.", "She is very clever."],
  ["rumal", "See oli rumal küsimus.", "That was a silly question."],
  ["naljakas", "See film on väga naljakas.", "This film is very funny."],
  ["tõsine", "See on tõsine haigus.", "This is a serious illness."],
  ["lahke", "Te olete väga lahke.", "You are very kind."],
  // The second batch of words added on 2026-09-26.
  ["paistma", "Täna paistab päike.", "The sun is shining today."],
  ["päästma", "Arst päästis tema elu.", "The doctor saved his life."],
  ["koguma", "Ma kogun raha reisiks.", "I am saving money for a trip."],
  ["kohtama", "Ma kohtasin eile vana sõpra.", "I ran into an old friend yesterday."],
  ["mõte", "See on hea mõte.", "That is a good idea."],
  ["idee", "Mul on üks idee.", "I have an idea."],
  ["maailm", "Maailm on suur.", "The world is big."],
  ["jutt", "See on pikk jutt.", "It is a long story."],
  ["tänu", "Suur tänu!", "Many thanks!"],
  ["tähelepanu", "Lapsel on vaja palju tähelepanu.", "The child needs a lot of attention."],
  ["mingi", "Mul on mingi mure.", "Something is worrying me."],
  ["kena", "Sa oled väga kena.", "You are very nice."],
  ["armas", "Teie laps on väga armas.", "Your child is very sweet."],
  ["lõbus", "Meil oli väga lõbus.", "We had great fun."],
  ["imelik", "See on imelik.", "That is strange."],
  ["eriline", "Täna on eriline päev.", "Today is a special day."],
  ["normaalne", "See on täiesti normaalne.", "That is completely normal."],
  ["vaene", "Nad on väga vaesed.", "They are very poor."],
  ["kuulus", "Ta on väga kuulus.", "She is very famous."],
  ["pime", "Väljas on juba pime.", "It is already dark outside."],
  ["ohutu", "See tee on ohutu.", "This road is safe."],
  ["tänulik", "Ma olen sulle väga tänulik.", "I am very grateful to you."],
  ["ettevaatlik", "Ole ettevaatlik!", "Be careful!"],
  ["uhke", "Ma olen sinu üle uhke.", "I am proud of you."],
];
