/**
 * THE WRITTEN SENTENCES FOR A1, BY UNIT IN TEACHING ORDER.
 *
 * Read `lib/dict/authored.ts` before adding a row: what a row may be, what the
 * machine checks, and what only a person can. `npm run check:authored` prints
 * every row that breaks a rule, with the reason.
 *
 * Each row is [the word it is filed under, the Estonian, the English]. Every
 * word of the Estonian is one the course has taught by the evening the word
 * arrives, so a sentence here may only use what comes before it in this file
 * or on the same evening.
 */
import type { AuthoredRow } from "@/lib/dict/authored";

export const AUTHORED_A1: readonly AuthoredRow[] = [
  // vastused
  ["jah", "Jah, muidugi!", "Yes, of course!"],
  ["muidugi", "Muidugi, aitäh!", "Of course, thank you!"],
  ["aitäh", "Jah, aitäh!", "Yes, thank you!"],
  ["ei", "Ei, aitäh.", "No, thank you."],
  // asesonad
  ["mina", "Mina? Jah, mina.", "Me? Yes, me."],
  ["sina", "Sina? Ei, tema.", "You? No, him."],
  ["tema", "Tema? Jah, tema.", "Her? Yes, her."],
  ["meie", "Meie? Ei, teie.", "Us? No, you."],
  ["nemad", "Nemad? Ei, meie.", "Them? No, us."],
  // esimesed-verbid
  ["olema", "See olen mina.", "That is me."],
  ["see", "See on tema.", "This is her."],
  ["too", "Too on tema, see olen mina.", "That one over there is him, and this is me."],
  ["elama", "Mina elan, sina elad.", "I live, you live."],
  ["õppima", "Mina õpin, tema ei õpi.", "I study, he does not."],
  ["rääkima", "Ma tahan rääkida.", "I want to talk."],
  ["töötama", "Ma töötan, tema õpib.", "I work, she studies."],
  ["tahtma", "Ma tahan õppida.", "I want to learn."],
  ["minema", "Ma tahan minna.", "I want to go."],
  ["tulema", "Tema tuleb, mina lähen.", "She is coming, I am going."],
  // vaikesed-sonad
  ["ja", "Ma töötan ja õpin.", "I work and study."],
  ["aga", "Ta õpib, aga ei tööta.", "She studies but does not work."],
  ["ka", "Mina õpin ka.", "I am studying too."],
  ["väga", "Ta räägib väga hästi.", "She speaks very well."],
  ["hästi", "Te räägite hästi.", "You speak well."],
  ["siin", "Ma elan siin.", "I live here."],
  ["siin", "Tema elab ka siin.", "She lives here too."],
  ["nüüd", "Nüüd ma lähen.", "Now I am going."],
  ["täna", "Täna ma töötan.", "Today I am working."],
  ["veel", "Ma õpin veel.", "I am still studying."],
  ["ainult", "Ta tahab ainult õppida.", "He only wants to study."],
  // kusisonad
  ["kes", "Kes sa oled?", "Who are you?"],
  ["mis", "Mis see on?", "What is this?"],
  ["kus", "Kus sa töötad?", "Where do you work?"],
  ["kuhu", "Kuhu te lähete?", "Where are you going?"],
  ["kust", "Kust sa tuled?", "Where are you coming from?"],
  ["millal", "Millal sa tuled?", "When are you coming?"],
  ["miks", "Miks sa eesti keelt õpid?", "Why are you learning Estonian?"],
  ["kuidas", "Kuidas sul läheb?", "How are you?"],
  ["kas", "Kas sa räägid eesti keelt?", "Do you speak Estonian?"],
  ["milline", "Milline see on?", "What is it like?"],
  ["kumb", "Kumb on sinu?", "Which of the two is yours?"],
  ["palju", "Ta räägib palju.", "She talks a lot."],
  ["kui", "Ta räägib, kui ta tahab.", "He talks when he wants to."],
  // inimesed
  ["inimene", "Ta on hea inimene.", "She is a good person."],
  ["naine", "See on minu naine.", "This is my wife."],
  ["mees", "Too mees elab siin.", "That man lives here."],
  ["laps", "Laps tahab minna.", "The child wants to go."],
  ["sõber", "Ta on minu sõber.", "He is my friend."],
  ["ema", "Minu ema elab siin.", "My mother lives here."],
  ["isa", "Isa töötab täna.", "Dad is working today."],
  ["pere", "Meie pere elab siin.", "Our family lives here."],
  ["vend", "Mu vend õpib ka.", "My brother is studying too."],
  ["õde", "Minu õde räägib väga hästi.", "My sister speaks very well."],
  ["tütar", "Meie tütar õpib.", "Our daughter is studying."],
  ["poeg", "Nende poeg töötab.", "Their son works."],
  ["vanaema", "Vanaema tuleb täna.", "Grandma is coming today."],
  ["vanaisa", "Vanaisa elab ka siin.", "Grandpa lives here too."],
  ["nimi", "Mis tema nimi on?", "What is her name?"],
  ["õpetaja", "Ta on õpetaja.", "She is a teacher."],
  ["õpilane", "Mina olen õpilane.", "I am a student."],
  ["arst", "Tema isa on arst.", "His father is a doctor."],
  // tutvumine
  ["eesnimi", "Mis su eesnimi on?", "What is your first name?"],
  ["perekonnanimi", "Mis on teie perekonnanimi?", "What is your surname?"],
  ["aadress", "Mis on sinu aadress?", "What is your address?"],
  ["elukoht", "Kus on teie elukoht?", "Where is your place of residence?"],
  ["sünnikoht", "Mis on teie sünnikoht?", "What is your place of birth?"],
  ["sünniaeg", "Mis on teie sünniaeg?", "What is your date of birth?"],
  ["tutvuma", "Ma tahan temaga tutvuda.", "I want to get to know him."],
  ["tutvustama", "Ta tutvustab mind.", "She is introducing me."],
  ["tuttav", "Ta on minu tuttav.", "He is an acquaintance of mine."],
  ["kolleeg", "See on minu kolleeg.", "This is my colleague."],
  ["sõbranna", "Minu sõbranna elab siin.", "My friend lives here."],
  ["hobi", "Mis on sinu hobi?", "What is your hobby?"],
  ["huvi", "Mul on huvi.", "I am interested."],
  ["meeldiv", "Teie õde on väga meeldiv.", "Your sister is very pleasant."],
  ["abielus", "Kas te olete abielus?", "Are you married?"],
  ["vallaline", "Ma olen vallaline.", "I am single."],
  // arvud
  ["number", "Mis on sinu number?", "What is your number?"],
  ["üks", "Mul on üks vend.", "I have one brother."],
  ["kaks", "Mul on kaks õde.", "I have two sisters."],
  ["kolm", "Meil on kolm last.", "We have three children."],
  ["neli", "Täna tuleb neli sõpra.", "Four friends are coming today."],
  ["viis", "Mul on viis sõpra.", "I have five friends."],
  ["kuus", "Siin elab kuus inimest.", "Six people live here."],
  ["seitse", "Meie peres on seitse inimest.", "There are seven people in our family."],
  ["kaheksa", "Kaheksa last õpib siin.", "Eight children study here."],
  ["üheksa", "Üheksa õpilast tuleb täna.", "Nine students are coming today."],
  ["kümme", "Kümme inimest töötab siin.", "Ten people work here."],
  ["üksteist", "Ta on üksteist.", "She is eleven."],
  ["kaksteist", "Minu poeg on kaksteist.", "My son is twelve."],
  ["kakskümmend", "Mu õde on kakskümmend.", "My sister is twenty."],
  ["kolmkümmend", "Ma olen kolmkümmend.", "I am thirty."],
  ["vanus", "Mis on teie vanus?", "What is your age?"],
  ["sada", "Siin töötab sada inimest.", "A hundred people work here."],
  ["tuhat", "Siin elab tuhat inimest.", "A thousand people live here."],
  ["esimene", "Ta on minu esimene õpetaja.", "She is my first teacher."],
  ["teine", "Mu teine vend elab siin.", "My other brother lives here."],
  ["kolmas", "Ta on meie kolmas laps.", "He is our third child."],
  ["neljas", "Täna on neljas.", "Today is the fourth."],
  ["viies", "Mina olen viies.", "I am fifth."],
  // kodu
  ["kodu", "Minu kodu on siin.", "My home is here."],
  ["maja", "Meie maja on siin.", "Our house is here."],
  ["tuba", "See on minu tuba.", "This is my room."],
  ["köök", "Kus on köök?", "Where is the kitchen?"],
  ["korter", "Me elame korteris.", "We live in a flat."],
  ["uks", "Kus on uks?", "Where is the door?"],
  ["aken", "Toas on üks aken.", "There is one window in the room."],
  ["laud", "Köögis on laud.", "There is a table in the kitchen."],
  ["tool", "Toas on kaks tooli.", "There are two chairs in the room."],
  ["voodi", "Voodi on toas.", "The bed is in the room."],
  ["raamat", "Mis raamat see on?", "What book is that?"],
  ["arvuti", "Kas see on sinu arvuti?", "Is this your computer?"],
  ["telefon", "Kus on minu telefon?", "Where is my phone?"],
  ["võti", "Kus on võti?", "Where is the key?"],
  ["klaas", "Laual on klaas.", "There is a glass on the table."],
  ["tass", "Laual on kaks tassi.", "There are two cups on the table."],
  ["pilt", "Seinal on pilt.", "There is a picture on the wall."],
  ["sein", "Toas on neli seina.", "The room has four walls."],
  ["põrand", "Raamat on põrandal.", "The book is on the floor."],
  ["korrus", "Ma elan teisel korrusel.", "I live on the second floor."],
  // pohiverbid
  ["tegema", "Mida sa teed?", "What are you doing?"],
  ["saama", "Ma ei saa tulla.", "I cannot come."],
  ["pidama", "Ma pean täna töötama.", "I have to work today."],
  ["sööma", "Laps sööb köögis.", "The child is eating in the kitchen."],
  ["jooma", "Mida sa jood?", "What are you drinking?"],
  ["tooma", "Palun too mulle tass.", "Please bring me a cup."],
  ["viima", "Isa viib lapse koju.", "Dad is taking the child home."],
  ["andma", "Anna mulle raamat, palun.", "Give me the book, please."],
  ["võtma", "Võta üks tass.", "Take a cup."],
  ["panema", "Pane tass lauale.", "Put the cup on the table."],
  ["jääma", "Ma jään koju.", "I am staying home."],
  // sook-ja-jook
  ["toit", "Toit on laual.", "The food is on the table."],
  ["söök", "Söök on köögis.", "The meal is in the kitchen."],
  ["jook", "Mis jook see on?", "What drink is this?"],
  ["leib", "Ma söön leiba.", "I am eating bread."],
  ["sai", "Laps tahab saia.", "The child wants some white bread."],
  ["kohv", "Kas sa tahad kohvi?", "Do you want coffee?"],
  ["vesi", "Palun anna mulle vett.", "Please give me some water."],
  ["piim", "Laps joob piima.", "The child is drinking milk."],
  ["mahl", "Mul on klaas mahla.", "I have a glass of juice."],
  ["liha", "Ma ei söö liha.", "I do not eat meat."],
  ["kala", "Täna sööme kala.", "Today we are eating fish."],
  ["õun", "Laual on kaks õuna.", "There are two apples on the table."],
  ["kartul", "Me sööme kartulit.", "We are eating potatoes."],
  ["juust", "Ma võtan leiba ja juustu.", "I will take bread and cheese."],
  ["muna", "Isa sööb muna.", "Dad is eating an egg."],
  ["või", "Pane leivale võid.", "Put some butter on the bread."],
  ["sool", "Kus on sool?", "Where is the salt?"],
  ["suhkur", "Kas sa võtad suhkrut?", "Do you take sugar?"],
  ["supp", "Supp on väga hea.", "The soup is very good."],
  // aeg
  ["aeg", "Mul ei ole aega.", "I do not have time."],
  ["päev", "Täna on hea päev.", "Today is a good day."],
  ["öö", "Head ööd!", "Good night!"],
  ["hommik", "Täna hommikul ma töötan.", "This morning I am working."],
  ["õhtu", "Õhtul ma olen kodus.", "In the evening I am at home."],
  ["nädal", "Nädalas on seitse päeva.", "A week has seven days."],
  ["kuu", "Ma olen siin kaks kuud.", "I have been here for two months."],
  ["aasta", "Aastas on kaksteist kuud.", "A year has twelve months."],
  ["tund", "Ma töötan kaheksa tundi.", "I work eight hours."],
  ["minut", "Üks minut, palun!", "One minute, please!"],
  ["kell", "Kell on kaks.", "It is two o'clock."],
  ["esmaspäev", "Esmaspäeval ma töötan.", "On Monday I work."],
  ["teisipäev", "Teisipäeval ma õpin eesti keelt.", "On Tuesday I study Estonian."],
  ["kolmapäev", "Kolmapäeval tuleb vanaema.", "Grandma comes on Wednesday."],
  ["neljapäev", "Neljapäeval me sööme kala.", "On Thursday we eat fish."],
  ["reede", "Reedel ma ei tööta.", "On Friday I do not work."],
  ["laupäev", "Laupäeval me oleme kodus.", "On Saturday we are at home."],
  ["pühapäev", "Pühapäeval tulevad sõbrad.", "Friends come on Sunday."],
  ["pool", "Kell on pool kaks.", "It is half past one."],
  ["hetk", "Üks hetk, palun!", "One moment, please!"],
  // iga-paev
  ["teadma", "Ma tean, kus ta elab.", "I know where she lives."],
  ["tundma", "Kas sa tunned teda?", "Do you know him?"],
  ["nägema", "Ma näen sind.", "I can see you."],
  ["kuulma", "Kas sa kuuled mind?", "Can you hear me?"],
  ["ütlema", "Mida ta ütleb?", "What is he saying?"],
  ["küsima", "Ta küsib, kus sa elad.", "She is asking where you live."],
  ["vastama", "Palun vasta mulle.", "Please answer me."],
  ["lugema", "Õhtul ma loen.", "In the evening I read."],
  ["kirjutama", "Laps kirjutab hästi.", "The child writes well."],
  ["magama", "Laps magab toas.", "The child is sleeping in the room."],
  ["ärkama", "Ma ärkan kell seitse.", "I wake up at seven."],
  ["istuma", "Istu, palun!", "Sit down, please!"],
  ["seisma", "Ta seisab köögis.", "She is standing in the kitchen."],
  // omadussonad
  ["suur", "Meie maja on suur.", "Our house is big."],
  ["väike", "Minu tuba on väike.", "My room is small."],
  ["hea", "See on hea raamat.", "This is a good book."],
  ["halb", "Täna on halb päev.", "Today is a bad day."],
  ["uus", "Mul on uus telefon.", "I have a new phone."],
  ["vana", "See maja on vana.", "This house is old."],
  ["noor", "Meie õpetaja on noor.", "Our teacher is young."],
  ["pikk", "Mu vend on pikk.", "My brother is tall."],
  ["lühike", "See raamat on lühike.", "This book is short."],
  ["kiire", "Mul on kiire.", "I am in a hurry."],
  ["aeglane", "Minu arvuti on aeglane.", "My computer is slow."],
  ["kallis", "See telefon on kallis.", "This phone is expensive."],
  ["odav", "Leib on odav.", "Bread is cheap."],
  ["ilus", "Sinu tuba on ilus.", "Your room is beautiful."],
  ["tore", "See on tore!", "That is great!"],
  ["raske", "Eesti keelt on raske õppida.", "Estonian is hard to learn."],
  ["kerge", "See tool on kerge.", "This chair is light."],
  ["lihtne", "See on väga lihtne.", "This is very simple."],
  ["valmis", "Söök on valmis.", "The food is ready."],
  ["keeruline", "See on keeruline.", "It is complicated."],
  // varvid
  ["värv", "Mis värv see on?", "What colour is it?"],
  ["punane", "Minu telefon on punane.", "My phone is red."],
  ["sinine", "Uks on sinine.", "The door is blue."],
  ["roheline", "Roheline tass on minu.", "The green cup is mine."],
  ["kollane", "Köök on kollane.", "The kitchen is yellow."],
  ["must", "Ma joon musta kohvi.", "I drink black coffee."],
  ["valge", "Seinad on valged.", "The walls are white."],
  ["hall", "Täna on hall päev.", "Today is a grey day."],
  ["pruun", "Laud on pruun.", "The table is brown."],
  ["roosa", "Tütre tuba on roosa.", "The daughter's room is pink."],
  ["lilla", "Mul on lilla tass.", "I have a purple cup."],
  ["hele", "Tuba on hele.", "The room is bright."],
  ["tume", "Tume leib on hea.", "Dark bread is good."],
  // riided
  ["särk", "Mul on uus särk.", "I have a new shirt."],
  ["kleit", "See kleit on väga ilus.", "This dress is very pretty."],
  ["seelik", "Tal on punane seelik.", "She has a red skirt."],
  ["king", "Kus on minu kingad?", "Where are my shoes?"],
  ["sokk", "Kus on mu sokid?", "Where are my socks?"],
  ["müts", "Mul on must müts.", "I have a black hat."],
  ["mantel", "Minu mantel on vana.", "My coat is old."],
  ["jope", "See jope on odav.", "This jacket is cheap."],
  ["sall", "Kas see sall on sinu?", "Is this scarf yours?"],
  ["kinnas", "Kus on minu kindad?", "Where are my gloves?"],
  ["taskurätik", "Kas sul on taskurätik?", "Do you have a handkerchief?"],
  ["vöö", "See vöö on pruun.", "This belt is brown."],
  ["riie", "See riie on hea.", "This fabric is good."],
  ["suurus", "Mis suurus see on?", "What size is this?"],
  ["püksid", "Mul on uued püksid.", "I have new trousers."],
  ["kampsun", "Mul on sinine kampsun.", "I have a blue sweater."],
  ["saabas", "Mul on uued saapad.", "I have new boots."],
  // ilm
  ["ilm", "Mis ilm täna on?", "What is the weather like today?"],
  ["päike", "Ma näen päikest.", "I can see the sun."],
  ["vihm", "Täna tuleb vihma.", "It is going to rain today."],
  ["lumi", "Täna tuleb lund.", "It is going to snow today."],
  ["tuul", "Täna on suur tuul.", "There is a strong wind today."],
  ["pilv", "Täna on palju pilvi.", "There are a lot of clouds today."],
  ["torm", "Täna on torm.", "There is a storm today."],
  ["jää", "Ma tahan vett ja jääd.", "I want water and ice."],
  ["udu", "Täna hommikul on udu.", "There is fog this morning."],
  ["kraad", "Täna on kümme kraadi.", "It is ten degrees today."],
  ["külm", "Mul on külm.", "I am cold."],
  ["soe", "Täna on soe.", "It is warm today."],
  ["kuum", "Supp on kuum.", "The soup is hot."],
  ["märg", "Mu mantel on märg.", "My coat is wet."],
  ["kuiv", "Leib on kuiv.", "The bread is dry."],
  // suured-arvud
  ["kolmteist", "Ta on kolmteist.", "He is thirteen."],
  ["neliteist", "Mu tütar on neliteist.", "My daughter is fourteen."],
  ["viisteist", "Kell on viisteist.", "It is three in the afternoon."],
  ["kuusteist", "Meil on kuusteist tooli.", "We have sixteen chairs."],
  ["seitseteist", "Täna on seitseteist kraadi.", "It is seventeen degrees today."],
  ["kaheksateist", "Mu vend on kaheksateist.", "My brother is eighteen."],
  ["üheksateist", "Kell on üheksateist.", "It is seven in the evening."],
  ["nelikümmend", "Ma olen nelikümmend.", "I am forty."],
  ["viiskümmend", "Isa on viiskümmend.", "Dad is fifty."],
  ["kuuskümmend", "Tunnis on kuuskümmend minutit.", "An hour has sixty minutes."],
  ["seitsekümmend", "Vanaema on seitsekümmend.", "Grandma is seventy."],
  ["kaheksakümmend", "Vanaisa on kaheksakümmend.", "Grandpa is eighty."],
  ["üheksakümmend", "Siin elab üheksakümmend inimest.", "Ninety people live here."],
  ["kuues", "Ma elan kuuendal korrusel.", "I live on the sixth floor."],
  ["seitsmes", "Ta elab seitsmendal korrusel.", "She lives on the seventh floor."],
  ["kaheksas", "Ta elab kaheksandal korrusel.", "He lives on the eighth floor."],
  ["üheksas", "Täna on üheksas.", "Today is the ninth."],
  ["kümnes", "Ta on kümnes õpilane.", "She is the tenth student."],
  ["miljon", "Tal on miljon sõpra.", "She has a million friends."],
  // ostmine
  ["pood", "Ma lähen poodi.", "I am going to the shop."],
  ["turg", "Laupäeval me läheme turule.", "On Saturday we are going to the market."],
  ["raha", "Mul ei ole raha.", "I do not have any money."],
  ["sularaha", "Kas teil on sularaha?", "Do you have cash?"],
  ["hind", "Hind on hea.", "The price is good."],
  ["pilet", "Mul on kaks piletit.", "I have two tickets."],
  ["ostma", "Ma tahan osta leiba.", "I want to buy bread."],
  ["müüma", "Ta müüb turul kala.", "She sells fish at the market."],
  ["maksma", "Ma maksan sularahas.", "I will pay in cash."],
  ["linn", "See linn on väga ilus.", "This town is very beautiful."],
  ["tänav", "Ma elan sellel tänaval.", "I live on this street."],
  ["tee", "Kas sa tahad teed?", "Do you want tea?"],
  ["buss", "Millal buss tuleb?", "When is the bus coming?"],
  ["rong", "Rong on kiire.", "The train is fast."],
  ["auto", "Meil on uus auto.", "We have a new car."],
  ["jaam", "Kus on jaam?", "Where is the station?"],
  ["park", "Park on väga ilus.", "The park is very beautiful."],
  ["euro", "See maksab kaks eurot.", "It costs two euros."],
  // kus-ja-kuhu
  ["koht", "See on hea koht.", "This is a good place."],
  ["kesklinn", "Ma töötan kesklinnas.", "I work in the city centre."],
  ["väljak", "Väljakul on palju inimesi.", "There are a lot of people on the square."],
  ["sild", "See sild on väga vana.", "This bridge is very old."],
  ["nurk", "Laud on nurgas.", "The table is in the corner."],
  ["kool", "Laps on koolis.", "The child is at school."],
  ["töö", "Ma lähen tööle.", "I am going to work."],
  ["haigla", "Isa töötab haiglas.", "Dad works at the hospital."],
  ["kirik", "Pühapäeval me läheme kirikusse.", "On Sunday we go to church."],
  ["rand", "Täna me läheme randa.", "Today we are going to the beach."],
  ["ülikool", "Mu õde õpib ülikoolis.", "My sister studies at university."],
  ["kohvik", "Me joome kohvikus kohvi.", "We are drinking coffee in the café."],
  ["restoran", "See restoran on kallis.", "This restaurant is expensive."],
  ["hotell", "Kus on hotell?", "Where is the hotel?"],
  ["vasakul", "Pood on vasakul.", "The shop is on the left."],
  ["paremal", "Kool on paremal.", "The school is on the right."],
  ["otse", "Mine otse!", "Go straight on!"],
  ["edasi", "Ma lähen edasi.", "I am going on."],
  ["tagasi", "Ta tuleb täna tagasi.", "She is coming back today."],
  ["asuma", "Kus asub jaam?", "Where is the station?"],
  ["mujal", "Ta elab mujal.", "He lives somewhere else."],
  ["siia", "Palun tule siia.", "Please come here."],
  // transport
  ["sõitma", "Ma sõidan bussiga.", "I go by bus."],
  ["tramm", "Me sõidame trammiga.", "We go by tram."],
  ["troll", "Kas see troll läheb kesklinna?", "Does this trolleybus go to the city centre?"],
  ["takso", "Ma võtan takso.", "I will take a taxi."],
  ["peatus", "Peatus on paremal.", "The stop is on the right."],
  ["bussijaam", "Bussijaam on kesklinnas.", "The bus station is in the city centre."],
  ["lennujaam", "Ma sõidan lennujaama.", "I am driving to the airport."],
  ["sadam", "Isa töötab sadamas.", "Dad works at the port."],
  ["jalgratas", "Ma sõidan jalgrattaga.", "I ride a bike."],
  ["sõit", "Head sõitu!", "Have a good trip!"],
  ["väljuma", "Ma väljun siin.", "I am getting off here."],
  ["sisenema", "Me siseneme majja.", "We go into the house."],
  ["väljapääs", "Kus on väljapääs?", "Where is the exit?"],
  ["sõiduplaan", "Kas sul on sõiduplaan?", "Do you have the timetable?"],
  ["hilinema", "Buss hilineb.", "The bus is late."],
  ["ootama", "Ma ootan bussi.", "I am waiting for the bus."],
  ["foor", "Foor on punane.", "The traffic light is red."],
  ["kõnnitee", "Laps on kõnniteel.", "The child is on the pavement."],
  ["jalgsi", "Ma lähen jalgsi.", "I am going on foot."],
  ["ühistransport", "Ma sõidan ühistranspordiga.", "I use public transport."],
  // umbmaarased
  ["ise", "Ma teen seda ise.", "I will do it myself."],
  ["keegi", "Keegi tuleb.", "Someone is coming."],
  ["kõik", "Kõik on hästi.", "Everything is fine."],
  ["igaüks", "Igaüks teab seda.", "Everyone knows that."],
  ["mõni", "Mõni päev on raske.", "Some days are hard."],
  ["iga", "Ma ärkan iga päev kell seitse.", "I wake up at seven every day."],
  ["oma", "Ma elan oma korteris.", "I live in my own flat."],
  // millal
  ["homme", "Homme ma ei tööta.", "Tomorrow I am not working."],
  ["eile", "Eile oli külm.", "It was cold yesterday."],
  ["ülehomme", "Ülehomme tuleb vanaema.", "Grandma is coming the day after tomorrow."],
  ["üleeile", "Üleeile oli torm.", "There was a storm the day before yesterday."],
  ["praegu", "Praegu ma olen tööl.", "Right now I am at work."],
  ["kohe", "Ma tulen kohe.", "I am coming right away."],
  ["varsti", "Buss tuleb varsti.", "The bus is coming soon."],
  ["hiljem", "Räägime hiljem.", "Let's talk later."],
  ["alati", "Ta räägib alati palju.", "He always talks a lot."],
  ["tihti", "Ma söön tihti kala.", "I often eat fish."],
  ["sageli", "Vihma tuleb sageli.", "It often rains."],
  ["harva", "Ma joon harva kohvi.", "I rarely drink coffee."],
  ["mõnikord", "Mõnikord ma töötan kodus.", "Sometimes I work at home."],
  ["kunagi", "Ma ei söö kunagi liha.", "I never eat meat."],
  ["juba", "Ma olen juba kodus.", "I am already home."],
  ["jälle", "Täna tuleb jälle vihma.", "It is raining again today."],
  ["ammu", "Ma elan siin juba ammu.", "I have lived here for a long time."],
  ["vanasti", "Vanasti elas siin palju inimesi.", "In the old days many people lived here."],
  // kohasonad
  ["peal", "Raamat on laua peal.", "The book is on the table."],
  ["all", "Kingad on voodi all.", "The shoes are under the bed."],
  ["ees", "Auto on maja ees.", "The car is in front of the house."],
  ["taga", "Park on maja taga.", "The park is behind the house."],
  ["kõrval", "Kool on kiriku kõrval.", "The school is next to the church."],
  ["juures", "Ma olen arsti juures.", "I am at the doctor's."],
  ["vahel", "Laud on kahe tooli vahel.", "The table is between two chairs."],
  ["sees", "Mis selle sees on?", "What is inside it?"],
  ["keskel", "Laud on toa keskel.", "The table is in the middle of the room."],
  ["vastas", "Pood on meie maja vastas.", "The shop is opposite our house."],
  ["ümber", "Maja ümber on park.", "There is a park around the house."],
  ["üle", "Mine üle tee.", "Cross the road."],
  ["läbi", "Me läheme pargi läbi.", "We are going through the park."],
  ["koos", "Me sööme koos.", "We eat together."],
  ["ilma", "Ma joon kohvi ilma suhkruta.", "I drink coffee without sugar."],
  ["enne", "Tule enne kella kolme.", "Come before three o'clock."],
  ["pärast", "Tule pärast tööd.", "Come after work."],
  ["lähedal", "Pood on väga lähedal.", "The shop is very close."],
  ["kohal", "Pilt on laua kohal.", "The picture is above the table."],
  ["mööda", "Mine mööda tänavat.", "Go along the street."],
  ["alates", "Alates esmaspäevast töötan ma.", "From Monday I am working."],
  ["kaasas", "Kas sul on raha kaasas?", "Do you have money on you?"],
  ["vastu", "Ma olen vastu.", "I am against it."],
  // sidesonad
  ["ning", "Ma söön leiba ning juustu.", "I am eating bread and cheese."],
  ["vaid", "Ma ei joo kohvi, vaid teed.", "I do not drink coffee, but tea."],
  ["et", "Ma tean, et ta tuleb.", "I know that she is coming."],
  ["sest", "Ma jään koju, sest mul on külm.", "I am staying home because I am cold."],
  ["kuna", "Kuna täna tuleb vihma, jään ma koju.", "Since it is raining today, I am staying home."],
  ["ega", "Ma ei söö liha ega kala.", "I eat neither meat nor fish."],
  ["või", "Kas sa tahad kohvi või teed?", "Do you want coffee or tea?"],
  ["ehk", "Ehk ta tuleb homme.", "Perhaps he will come tomorrow."],
  ["kuni", "Ma ootan, kuni sa tuled.", "I will wait until you come."],
  ["nagu", "Ta räägib nagu õpetaja.", "She talks like a teacher."],
  ["sellepärast", "Mul on külm, sellepärast ma jään koju.", "I am cold, so I am staying home."],
  ["seega", "Buss hilineb, seega ma võtan takso.", "The bus is late, so I will take a taxi."],
  ["siis", "Kui sa tuled, siis me sööme koos.", "If you come, then we will eat together."],
  ["nii", "Sa räägid nii hästi!", "You speak so well!"],
  ["mitte", "Mitte täna, vaid homme.", "Not today, but tomorrow."],
  ["kuigi", "Ma lähen tööle, kuigi on külm.", "I am going to work, although it is cold."],
  // kindlus
  ["kindlasti", "Ma tulen kindlasti.", "I will definitely come."],
  ["vist", "Ta on vist kodus.", "I think he is at home."],
  ["äkki", "Äkki ta ei tule.", "Maybe she will not come."],
  ["küll", "Ta tuleb küll.", "He will come, you will see."],
  ["eks", "Sa tuled homme, eks?", "You are coming tomorrow, right?"],
  ["tõesti", "Kas see on tõesti sinu?", "Is this really yours?"],
  ["tegelikult", "Tegelikult ma ei tea.", "Actually, I do not know."],
  ["õige", "See on õige tee.", "This is the right way."],
  // maaramine
  ["ju", "Sa ju tead seda.", "You know that, don't you."],
  ["just", "Ta tuli just koju.", "She has just come home."],
  ["enam", "Ma ei tööta enam.", "I do not work any more."],
  ["isegi", "Isegi laps teab seda.", "Even a child knows that."],
  ["ikka", "Ma elan ikka siin.", "I still live here."],
  ["rohkem", "Palun anna mulle rohkem vett.", "Please give me more water."],
  ["liiga", "See on liiga kallis.", "This is too expensive."],
  ["päris", "Täna on päris külm.", "It is quite cold today."],
  ["natuke", "Ma räägin natuke eesti keelt.", "I speak a little Estonian."],
  ["üldse", "Ma ei tea üldse.", "I have no idea at all."],
  ["eriti", "Täna on eriti külm.", "It is especially cold today."],
  ["sama", "Meil on sama õpetaja.", "We have the same teacher."],
  ["uuesti", "Palun ütle uuesti.", "Please say it again."],
  ["varem", "Ma ärkan täna varem.", "I am waking up earlier today."],
  ["kaua", "Kui kaua sa siin elad?", "How long have you lived here?"],
  ["siit", "Kas buss läheb siit?", "Does the bus leave from here?"],
  ["sinna", "Ma lähen sinna homme.", "I am going there tomorrow."],
  ["üksi", "Ma elan üksi.", "I live alone."],
  ["aeglaselt", "Palun räägi aeglaselt.", "Please speak slowly."],
  // kuud
  ["jaanuar", "Jaanuaris on väga külm.", "It is very cold in January."],
  ["veebruar", "Veebruaris tuleb palju lund.", "A lot of snow falls in February."],
  ["märts", "Märtsis on veel külm.", "It is still cold in March."],
  ["aprill", "Aprillis tuleb tihti vihma.", "It often rains in April."],
  ["mai", "Mais on ilm juba soe.", "In May the weather is already warm."],
  ["juuni", "Juunis me läheme randa.", "In June we go to the beach."],
  ["juuli", "Juulis on väga soe.", "It is very warm in July."],
  ["august", "Augustis me oleme kodus.", "In August we are at home."],
  ["september", "Septembris lähevad lapsed kooli.", "In September children go to school."],
  ["oktoober", "Oktoobris on palju vihma.", "There is a lot of rain in October."],
  ["november", "Novembris on hall ilm.", "The weather is grey in November."],
  ["detsember", "Detsembris tuleb lund.", "It snows in December."],
  ["kuupäev", "Mis kuupäev täna on?", "What is the date today?"],
  ["sünnipäev", "Täna on minu sünnipäev.", "Today is my birthday."],
  ["tähtpäev", "Täna on tähtpäev.", "Today is a special day."],
  ["jaanipäev", "Jaanipäeval me oleme rannas.", "At Midsummer we are at the beach."],
  ["nädalavahetus", "Head nädalavahetust!", "Have a good weekend!"],
  ["puhkepäev", "Pühapäev on minu puhkepäev.", "Sunday is my day off."],
  // riigid
  ["Eesti", "Ma elan Eestis.", "I live in Estonia."],
  ["Soome", "Mu vend elab Soomes.", "My brother lives in Finland."],
  ["Läti", "Me sõidame homme Lätti.", "We are going to Latvia tomorrow."],
  ["Venemaa", "Ta sõidab homme Venemaale.", "She is going to Russia tomorrow."],
  ["Rootsi", "Mu õde elab Rootsis.", "My sister lives in Sweden."],
  ["Saksamaa", "Mu sõber töötab Saksamaal.", "My friend works in Germany."],
  ["Inglismaa", "Ta õpib Inglismaal.", "She studies in England."],
  ["Ameerika", "Tema isa elab Ameerikas.", "Her father lives in America."],
  ["Euroopa", "Eesti on Euroopas.", "Estonia is in Europe."],
  ["eestlane", "Ma olen eestlane.", "I am Estonian."],
  ["soomlane", "Tema naine on soomlane.", "His wife is Finnish."],
  ["lätlane", "Minu kolleeg on lätlane.", "My colleague is Latvian."],
  ["venelane", "Ta on venelane, aga elab Eestis.", "He is Russian but lives in Estonia."],
  ["rootslane", "Meie õpetaja on rootslane.", "Our teacher is Swedish."],
  ["sakslane", "Minu õpetaja on sakslane.", "My teacher is German."],
  ["inglane", "Ta on inglane.", "He is English."],
  ["ameeriklane", "Kas sa oled ameeriklane?", "Are you American?"],
  ["välismaalane", "Ma olen välismaalane.", "I am a foreigner."],
  ["kodumaa", "Eesti on minu kodumaa.", "Estonia is my homeland."],
  ["rahvus", "Mis rahvus sa oled?", "What nationality are you?"],
  ["pärit", "Kust sa pärit oled?", "Where are you from?"],
  ["vene", "Ma räägin vene keelt.", "I speak Russian."],
  ["prantsuse", "Ta õpib prantsuse keelt.", "She is learning French."],
  ["Prantsusmaa", "Ma tahan minna Prantsusmaale.", "I want to go to France."],
  // viisisonad
  ["kiiresti", "Ta räägib väga kiiresti.", "She speaks very fast."],
  ["kergesti", "Laps õpib kergesti.", "The child learns easily."],
  ["kõvasti", "Räägi palun kõvasti.", "Please speak loudly."],
  ["halvasti", "Ma magasin halvasti.", "I slept badly."],
  ["tavaliselt", "Tavaliselt ma ärkan kell seitse.", "I usually wake up at seven."],
  ["enamasti", "Enamasti ma sõidan bussiga.", "Mostly I go by bus."],
  ["pidevalt", "Ta räägib pidevalt.", "He talks all the time."],
  ["umbes", "See maksab umbes kümme eurot.", "It costs about ten euros."],
  ["peaaegu", "Söök on peaaegu valmis.", "The food is almost ready."],
  ["üsna", "Täna on üsna soe.", "It is fairly warm today."],
  ["täiesti", "See on täiesti õige.", "That is completely right."],
  ["veidi", "Oota veidi, palun.", "Wait a little, please."],
  ["pisut", "Mul on pisut külm.", "I am a little cold."],
  ["vähemalt", "Ma magan vähemalt kaheksa tundi.", "I sleep at least eight hours."],
  ["alles", "Kell on alles seitse.", "It is only seven o'clock."],
  ["taas", "Täna on taas külm.", "It is cold again today."],
  ["pigem", "Ma joon pigem teed.", "I would rather drink tea."],
  // osakesed
  ["kinni", "Pane uks kinni.", "Close the door."],
  ["lahti", "Aken on lahti.", "The window is open."],
  ["välja", "Ma lähen välja.", "I am going out."],
  ["sisse", "Tule sisse!", "Come in!"],
  ["üles", "Ärka üles!", "Wake up!"],
  ["maha", "Istu maha.", "Sit down."],
  ["alla", "Ma tulen kohe alla.", "I am coming down right away."],
  ["kokku", "Me saame homme kokku.", "We are meeting tomorrow."],
  ["laiali", "Raamatud on põrandal laiali.", "The books are all over the floor."],
  ["kaasa", "Võta raha kaasa.", "Take some money with you."],
  ["ette", "Auto sõitis maja ette.", "The car pulled up in front of the house."],
  ["taha", "Pane tool laua taha.", "Put the chair behind the table."],
  ["juurde", "Ma lähen arsti juurde.", "I am going to the doctor."],
  ["järele", "Isa tuleb lapsele järele.", "Dad is coming to pick up the child."],
  // abi
  ["abi", "Abi tuleb kohe.", "Help is coming right away."],
  ["aitama", "Kas sa saad mind aidata?", "Can you help me?"],
  ["appi", "Appi, appi!", "Help, help!"],
  ["politsei", "Politsei on siin.", "The police are here."],
  ["kiirabi", "Kiirabi sõidab kiiresti.", "The ambulance is driving fast."],
  ["tuletõrje", "Tuletõrje tuleb kohe.", "The fire brigade is coming right away."],
  ["hädaabi", "Mis on hädaabi number?", "What is the emergency number?"],
  ["apteek", "Kus on apteek?", "Where is the pharmacy?"],
  ["tuli", "Köögis on tuli!", "There is a fire in the kitchen!"],
  ["ohtlik", "See tee on ohtlik.", "This road is dangerous."],
  ["varas", "Varas võttis mu telefoni.", "A thief took my phone."],
  ["eksima", "Ma eksisin linnas.", "I got lost in the town."],
  ["helistama", "Ma helistan sulle homme.", "I will call you tomorrow."],
  ["vaja", "Mul on vaja minna.", "I need to go."],
];
