import ENGLISH from "@/prisma/data/example-english.json";

/**
 * WHAT EACH SENTENCE THE DICTIONARY SHIPS MEANS, READ OFF ONE FILE.
 *
 * Ekilex records no English against a usage on a reader key, so every recorded
 * sentence in this app arrived bare: a learner met `jah`, read "yes", and read
 * `Sina jah.` underneath with nothing to say what it was. Every screen that
 * shows a sentence now asks for its English and stores what comes back, which
 * fixes it for a deployment that has a model key and does nothing at all for
 * the default one, which has none. A rule that only holds where somebody is
 * paying for it is not the rule this app said it had.
 *
 * So the English ships, built once by `npm run translate:examples` and read
 * here. It is a file keyed on the sentence rather than a column on the entry,
 * for two reasons that are both about where a fact belongs. A translation is a
 * fact about the sentence: `lib/dict/borrow.ts` lends one word's usages to
 * another and they mean the same thing under both, so a copy per entry is a
 * copy that goes stale on one side. And `prisma/data/harvested.ts` is
 * generated by `npm run harvest` and rewritten whole on every run, so an
 * English column in it would be deleted by the next harvest, silently, in the
 * file nobody re-reads.
 *
 * THE VOICE RULES REACH THE DASH AND NOTHING ELSE HERE, and that is measured
 * rather than assumed. A dash used as a clause break is the loudest tell that
 * a sentence was generated, so a translation carrying one its own Estonian
 * does not is refused on the way in; one the lexicographer wrote (a street
 * number, a range of years) is the sentence rather than the model and stays.
 * The phrase rules are deliberately *not* swept over this file: the two hits
 * in 9,504 answers were `Lõpetuseks` rendered as `In conclusion` and `mitte
 * lihtsalt` as `not just`, which is what those Estonian words mean, and a
 * check that fires on honest copy is a check everybody learns to waive. This
 * is a translation of somebody else's sentence, not this app's own voice.
 *
 * NOTHING HERE IS ESTONIAN AND NOTHING HERE WRITES ANY. The keys are sentences
 * a lexicographer recorded, unchanged; the values are English, in the one
 * direction ADR-005 permits a model to work. A sentence with no line in the
 * file is left without one rather than given a guess, which is the state every
 * sentence was in before this existed, and the runtime ask still fills that in
 * for a learner's own added sentence or a word looked up live.
 */
const TABLE: Readonly<Record<string, string>> = ENGLISH;

/** The English for one recorded sentence, or null where none was built. */
export function englishFor(sentence: string): string | null {
  return TABLE[sentence] ?? null;
}

/** How many sentences the shipped table covers, for the audit that counts them. */
export function englishCount(): number {
  return Object.keys(TABLE).length;
}
